### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by hjorvari** [srid/neuron#10]
Initially I was lazy and tried to just: `nix-env -if https://github.com/srid/neuron/tarball/master` but it doesn't bring `neuron` into your env, rather it brings `sridca` from the example and it's not immediately obvious how to modify things so that you get the functionality described in https://www.srid.ca/2010101.html

I thought this was a cli for interacting with the zettelkasten? I figured it'd be a bit like xmonad for notes?

Edit: cool project thanks for sharing!

**Comment by srid** [comment]
Hi! Neuron is not *yet* installable as a standalone program, but I'm working on preparing it for such a purpose. 

And yes, describing it as "xmonad for notes" is actually close to the mark!

**Comment by ibnuda** [comment]
thank you for your work, bhai. i'm watching this repo closely.

**Comment by srid** [comment]
@hjorvari Take a look at the new README. It contains instructions on how to build and run neuron. There is also a sample zettelkasten at `./guide`; which you may use as a base for building your own zettelkasten.

**Comment by srid** [comment]
And here's some documentation: https://neuron.srid.ca/

**Comment by srid** [comment]
I've now added a tutorial: https://neuron.srid.ca/2011502.html

**Comment by hjorvari** [comment]
Sweet, thank you! I'll look closer at this :)

**Comment by hjorvari** [comment]
I noticed a small typo in the install note, `:%s/close/clone/`.
