### ISSUE TITLE
Alternative instructions for installation

### ISSUE THREAD

**Issue by luc-tielen** [srid/neuron#103]
A couple of days ago I mentioned neuron to a friend of mine (@hanskenis) who became enthousiastic about it. However today he tried installing it on MacOSX Catalina (which has issues with nix) and he immediately became stuck.. and the enthousiasm quickly dissapeared. 😞 

Is it possible to have instructions for a cabal / stack install as well? 
I think it would open up neuron for a much bigger audience.

**Comment by srid** [comment]
@luc-tielen Could you encourage your friend to try [these instructions](https://github.com/NixOS/nix/issues/2925#issuecomment-539570232) for Catalina. I'm sure it will be a smooth ride afterwards. 

> Is it possible to have instructions for a cabal / stack install as well?

Yes, it is possible. We need to get `rib` into stackage, and then the `which` package as well. Finally the neuron package (all of this will also automatically make it available in nixpkgs). This is tracked in #45

**Comment by luc-tielen** [comment]
I did suggest it to him but he ended up finding it too much work (since he's not normally a nix user). Once the packages are in stackage he might try installing it again.

**Comment by srid** [comment]
If anybody wants to try it, here is way to "try before you buy it" neuron. You only need to have docker installed:

```
docker run --rm \
  -v ~/zettelkasten:/root/zettelkasten \
  -p 8080:8080 \
  sridca/neuron:test \
  neuron rib -o /tmp/site -ws 0.0.0.0:8080
```

**Comment by luc-tielen** [comment]
Ah, I didn't even think of Docker.. guess that's what happens if you use nix for too long 😄. I can confirm that it works, nice addition!

**Comment by srid** [comment]
Alright, I'm going to close this.

- I realized only over time that Nix is integral to neuron development (for eg., `neuron-search` relies on Nix), so stack-based install is unlikely to happen.
- If people don't want to use Nix, they can use Docker (the alternative install option) after #146 is done.

**Comment by luc-tielen** [comment]
That's ok, I think Docker is a good alternative that a lot of people have installed already.
