### ISSUE TITLE
display Markdown source line for zettel linking errors

### ISSUE THREAD

**Issue by ceedubs** [srid/neuron#104]
As mentioned in #102.

Currently if you write invalid Markdown in a zettel, the error message helpfully provides details:

```
user error (2014103.md:11:17:
   |
11 |   * [2014405(z:)
   |                 ^
unexpected end of inline block
expecting ']' or inline content
)
```

However, if you try to link to a nonexistent zettel ID, the ZettelStore raises an error and no Markdown source information is given: `No such zettel: ZettelDateID 2021-04-08 5` (message improved after #102). It would be nice if invalid links resulted in error messages with a similar level of detail to the above Markdown parsing error message.

**Comment by srid** [comment]
This is going to be tricky to implement (assuming it is even possible without forking `mmark`).

Invalid Markdown is handled by the `mmark` parser, which uses `megaparsec` - and that provides nice error messages including source line no. on parser errors.

Neuron's link action uses `mmark-ext` which works on the *post*-parsed structure that has no line number information.

**Comment by srid** [comment]
> It would be nice if invalid links resulted in error messages with a similar level of detail to the above Markdown parsing error message.

Errors for invalid links (among others) are now rendered inline in the generated HTML. See https://github.com/srid/neuron/issues/201#issuecomment-633062878
