### ISSUE TITLE
Rewrite search.js in Haskell

### ISSUE THREAD

**Issue by srid** [srid/neuron#108]
Rewrite search.js in ~~PureScript~~GHCJS (reflex). But instead of a dedicated `search.html` integrate search directly into the z-index.

Client-side code can be used to basically search the z-index cluster trees, and filter their view to show the results.

**Comment by srid** [comment]
For search there are a few options:

* Write FFI for [js-search](https://github.com/bvaughn/js-search) (which `search.js` already uses)
* Use one of these purescript libraries:
  * https://pursuit.purescript.org/packages/purescript-search/3.0.0
  * https://pursuit.purescript.org/packages/purescript-fuzzy/0.2.1/docs/Data.Fuzzy

**Comment by gillchristian** [comment]
Questions about the approach you have in mind for this feature.

Should we go for a full FE rendering and rebuild the page with PS? Or just interact with the generated DOM and filter that? Since my work is mostly on React I'd be inclined to the first option.

Since z-index is a tree view of each cluster instead of a list of results like the current search. Should the parent paths of a node in the results be displayed as well? If so maybe actual matches could be highlighted.

**Comment by srid** [comment]
What's "FE rendering"?

**Comment by gillchristian** [comment]
Fixed. I meant client side rendering.

**Comment by srid** [comment]
> Should we go for a full client side rendering and rebuild the page with PS?

Nope. The generated site should be lightweight, as it is something I publish online as well (not just used internally). Eg: https://haskell.zettel.page/ and https://www.srid.ca/

I don't want the generated site to rely on JavaScript, which should only be used for dynamic stuff (like search) that can't be done in static site generation.

> Or just interact with the generated DOM and filter that? 

Right, this would be my preference for the z-index. 

> Should the parent paths of a node in the results be displayed as well? If so maybe actual matches could be highlighted.

I suppose, yea.

**Comment by Nadrieril** [comment]
> pursuit.purescript.org/packages/purescript-fuzzy/0.2.1/docs/Data.Fuzzy

Fuzzy search would be amazing !

**Comment by srid** [comment]
Doing this in GHCJS should now be fairly straightforward, building on top of https://github.com/srid/reflex-stone

Here's an approach:

- Have neuron write a `graph.json` to the output directory. This should contain the entire graph, including tags and other metadata (but no text content, of course)
- Create a repo based on reflex-stone; use neuron as a library; and make a HTTP request to `./graph.json`, then do the whole search UI & interaction in Reflex, before rendering the actual links using the existing UI functions in neuron.
- Produce the compiled JS (`nix-build site.nix`) once, and have `neuron rib` copy that to the output directory's `./search` folder (should contain index.html and all.js). 
- As the user, access the search page at `/search` (instead of `/search.js`)

We can follow the same approach for other interactive tasks like #99

**Comment by jaygray0919** [comment]
can't wait to see this ...

**Comment by srid** [comment]
My plan: replace both search.html and z-index.html with one dynamic view (displays the "index" that can be filtered by interactive search) built with GHCJS.

**Comment by srid** [comment]
Demo: https://www.srid.ca/impulse.html
