### ISSUE TITLE
Feature Request: Add builtin optional metadata: author and date

### ISSUE THREAD

**Issue by michelk** [srid/neuron#113]
I would be nice if the author and the date of last change would be rendered small at the bottom of the page.

**Comment by srid** [comment]
Note that the date of last change is different from the zettel date (which is date of its creation). It is indeed a good feature to include the last modified date in the footer.

I'm curious about author, though. Do you have you a zettelkasten with multiple authors? There is already an author field in configuration (neuron.dhall); it is used only in OpenGraph meta tags.

**Comment by michelk** [comment]
For community zettelkästen or enterprise knowledge bases this would be
a helpful feature.

**Comment by michelk** [comment]
What do you think about rendering all (custom) meta-data entries at the footer of the page?

**Comment by srid** [comment]
> What do you think about rendering all (custom) meta-data entries at the footer of the page?

That may not be a bad idea. But I'd be wary of rendering *all* custom meta-data by default. Not sure if that's desirable.

If author is the only thing you'd like to be rendered, why not make it a tag like:

```
title: My zettel
tags:
  - author/michelk
```

?

With the upcoming #121 you could do nifty things like show a list of all authors, with a link to a page that shows all zettels by them.

**Comment by michelk** [comment]
Sounds like a good idea.

**Comment by srid** [comment]
Date of zettel creation is now displayed at the bottom, in 8acef9594a4edc02b4a828df5d54bf587f2d0395
