### ISSUE TITLE
problem installing neuron under WSL

### ISSUE THREAD

**Issue by jaygray0919** [srid/neuron#122]
am running the latest windows 10 pro: version 1909 OS build 18363.778
have installed Windows Subsystem for Linux (WSL)

have successfully installed the ubuntu distro
have updated and upgraded ubuntu

have edited `nix.conf` and installed `nix`

have tested nix using
  `nix-shell -p busybox --run 'echo $PATH'`

have installed `cachix` and set
  `cachix use srid`

but have a problem installing the latest development version of `neuron`

When using this command string:
  `nix-env -iE '_: let src = builtins.fetchGit { url = "https://github.com/srid/neuron"; ref = "master"; }; in import src.outPath { gitRev = src.shortRev; }' --option tarball-ttl 0`

am getting the following error:
  `error: executing 'git': No such file or directory`
  `error: program 'git' failed with exit code 1`

am i doing something wrong? is there an alternative method for installing `neuron`

thanks for help here.

/jay gray

**Comment by srid** [comment]
@jaygray0919 Can you try after installing git? You can install it in one of the following ways:

- Use nix: `nix-env -i git`
- Use ubuntu's package manager: `apt-get install git`

**Comment by jaygray0919** [comment]
Done! neuron-0.3.1.0 ++ successfully installed.
Aside: I have **never** seen a build of this size, with so many dependencies, work so smoothly - frickin' incredible.
Will work on the next steps later today.
Thank you.
