### ISSUE TITLE
additional install error

### ISSUE THREAD

**Issue by jaygray0919** [srid/neuron#127]
have successfully installed `neuron` (a beautiful experience!)

can run this command:
  `neuron --version`

response:
  `0.3.1.0 (03c5fe8)`

however, when running this command
  `git clone https://github.com/srid/neuron.git`

am seeing this message:
  `fatal: could not create work tree dir 'neuron': permission denied`

tried this approach
  `sudo git clone https://github.com/srid/neuron.git`

but `sudo` does not see `git`
  `sudo: git: command not found`

am running a new install of the ubuntu distro under Win10 `WSL` and have some directory access and profile issues from the default install.

is there an alternative way to execute
  `git clone https://github.com/srid/neuron.git`

that does not encounter this problem:
  `fatal: could not create work tree dir 'neuron': permission denied`

/jay

**Comment by srid** [comment]
This looks like a system issue with WSL. You don't have permission to write to your local directory?

Are you in the user's home directory? What is the output of `pwd`? Run `cd` once before retrying with the clone.

**Comment by jaygray0919** [comment]
rookie mistake (was parked in /etc)
now:
  `cd $home`
re-ran command (success)
next:
  `cd neuron`
then:
  `neuron -d ./guide rib -wS`
am looking at:
  `http://localhost:8080/`
which looks exactly like https://neuron.zettel.page/

thanks for guidance. will now take next steps to `Create your own Zettelkasten`

/jay

**Comment by jaygray0919** [comment]
have created my own zettelkasten.
am running local
next step: create and link files
then we'll move it to our AWS EC2 server.
thanks again for guidance.
