### ISSUE TITLE
Week number in Zettel ID

### ISSUE THREAD

**Issue by specdrake** [srid/neuron#128]
I have found an issue with week numbers in the default Zettel ID generated by `neuron new <title>`. As mentioned in [Zettel ID(Neuron)](https://neuron.zettel.page/2011403.html) neuron follows the **ISO week date** standard to generate week numbers. But the week number doesn't match with that calculated using the algorithm specified on this [Wikipedia page](https://en.wikipedia.org/wiki/ISO_week_date#Algorithms) and neither with that found using online services like Google Calendar or http://week-number.net/.
As an example, I created a new zettel at 4:38 PM UTC on 21 April 2020
![Screenshot from 2020-04-21 22-08-47](https://user-images.githubusercontent.com/13088104/79890215-cc508080-841c-11ea-9045-1d9286ff72bd.png)
neuron created a new zettel with ID 20**16**201, hence week number is 16 according to it.
But according to the algorithm described above and various other sources, the week number is 17.
![Screenshot from 2020-04-21 22-13-18](https://user-images.githubusercontent.com/13088104/79890814-aaa3c900-841d-11ea-8e42-8c8da5682d65.png)

**Comment by srid** [comment]
I've updated the documentation on the site. Basically, neuron's week number is offset by `-1` to ISO week number. The first week number is considered to be 0. 

Yea, this is not strictly according to the ISO spec, but that's what Haskell uses (see `%W` in [`formatTime`](https://hackage.haskell.org/package/time-1.10/docs/Data-Time-Format.html#v:formatTime):

> %W 
  week of year where weeks start on Monday (as mondayStartWeek), 0-padded to two chars, 00 - 53

Note however that all date calculation from the ID however should be accurate. It is only the ID representation that differs. 

643a44a9f71e40cba3aa1484d73ca2d17a7238d9
