### ISSUE TITLE
Embedding images

### ISSUE THREAD

**Issue by michelk** [srid/neuron#129]
Currently, 

```markdown
![Image](./figures/rose.png)
```
renders to 

```html
<img src="./figures/rose.png">
```
Since the output directory is usually `.neuron/output`, the image won't be rendered. To fix it, the image path should be adapted according to the html output directory.

**Comment by srid** [comment]
A directory named `static` is copied as-is to the output directory. If you put your images in it, and reference it like:

```markdown
![Image](./static/figures/rose.png)
```

it should work.

**Comment by michelk** [comment]
ok, thanks. 

I wrote a zettel about it (#133).

**Comment by michelk** [comment]
The images are quite small, about 50% textwidth. It would be nice to be able to add properties like in pandoc. 

![Rose](./(static/rose.png){ width=100% }

**Comment by michelk** [comment]
Btw, why aren't you using [commonmark-hs](https://github.com/jgm/commonmark-hs)

**Comment by srid** [comment]
@michelk I hadn't come across it before, but it looks to be lighter weight than Pandoc, which is a good thing, and has an extension mechanism. I won't be opposed to switching to different markdown parser, but it will require some evaluation first.

---

As for images, I didn't know that Pandoc supported image properties. Meanwhile we could just fix the neuron CSS to remove the 50% width.

**Comment by srid** [comment]
@michelk For image properties, see #176
