### ISSUE TITLE
Feature Request: Support for citations

### ISSUE THREAD

**Issue by michelk** [srid/neuron#134]
It would be good to be able to use [pandoc-citations](https://pandoc.org/MANUAL.html#citations).

In pandoc it is possible to use either a common  `references.yaml`-file to  which all Zettels could refer to. Or specify the reference in the meta-data field. 

```markdown
---
title: Zettel title
tags: 
- science/biology
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose
    nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
...


Like Watson and Crick [@WatsonCrick1953] said, ...
```

**Comment by srid** [comment]
Depends on #137

**Comment by srid** [comment]
This now depends on a commonmark extension: https://github.com/jgm/commonmark-hs/issues/15

**Comment by samwalls** [comment]
I made [this](https://github.com/samwalls/neuron-citation) for my own purposes. Probably not a complete solution like you want here, but might help inform what does/doesn't work well.

**Comment by samwalls** [comment]
Here's an example site using citations: https://samwalls.github.io/neuron-citation/3889a3b1.

**Comment by mickael-menu** [comment]
@samwalls You should add it to [the list of user-contributed tools](https://github.com/srid/neuron/blob/master/doc/Guide/extras.md) 👍

**Comment by srid** [comment]
@samwalls FYI, new version of pandoc got released with this syntax change: https://github.com/jgm/pandoc/commit/3f09f53459b877f53072efbf57dec21fa37280b5

**Comment by srid** [comment]
Given [neuron's status](https://neuron.zettel.page/next) - this feature request is now moved to https://github.com/srid/emanote/discussions/124 (Please continue discussion over there)
