### ISSUE TITLE
Change default ZettelDateId to use %y%M%d as default format for formatDay

### ISSUE THREAD

**Issue by theNerd247** [srid/neuron#135]
Currently "%y%W%a" is being used and then appended with a modification to use numbers as apposed to weekdays. I would propose to use something more along the lines of `%y%m%d-<n>` where `<n>` is a natural number indexing over the Zettels created for that particular date. My reasoning is that this provides a more human friendly way to read ZettelIds as they appear in the rendered website. To be specific it's hard to remember that `201641` means "the first Zettel created on 2020 on April 23". Where as `20200423` is much easier to read. (Maybe it would be better to include a dash for the index? `20200423-1`? 

I attempted to introduce an addition to the config in the dhall config where users could optionally introduce their own custom format. However this would require threading the new config to parts of the code that don't rely on it as of yet (particularly the `To/FromJSON` instances for `ZettelId`.

I'd be happy to hear your thoughts on this and to contribute!

**Comment by srid** [comment]
Adding a new date ID format would be challenging for backwards compat. Even if we make it configurable, what would happen if I switch my existing Zettelkasten to use the new date ID format? Wouldn't that invalid the dates of existing zettels, and lead to inconsistencies? 

I think it may be better to directly address the original desire:

>  My reasoning is that this provides a more human friendly way to read ZettelIds as they appear in the rendered website.

In my mind a zettel ID is some opaque (and unique) identifier, one that is not necessarily human readable (other than visually indicating, at first glance, that it points to a zettel). If you would like the zettel creation date to be displayed, there is the (not yet documented) `?linkTheme=withDate` option which I use [here](https://www.srid.ca/) to list timeline zettels. It will show the human readable date encoded in the ID, like:

![image](https://user-images.githubusercontent.com/3998/80156225-62a5b300-8591-11ea-84c2-7e6561aa1c50.png)

I have so far not found myself wanting to know the creation date of zettels (that kind of goes against the philosophy of general note taking); and have dates shown only in places where they make sense (such as a blog-like timeline).

**Comment by theNerd247** [comment]
That makes sense. I guess I just needed a bit of a perspective change. I'll work on a PR documenting the addition to links.

**Comment by srid** [comment]
Great, I'll close this.
