### ISSUE TITLE
Cannot Start nix-shell

### ISSUE THREAD

**Issue by theNerd247** [srid/neuron#139]
I'm trying to write the following nix-shell file so I don't have to add neuron to home-manager etc. and can just drop into a nix-shell when I need to do some work. However I get the following error:

```
bash: /nix/store/zari0sl3xh70x9cw6f4kwsif8kr29clk-ghc-8.8.3-with-packages: Is a directory
```
when running `nix-shell ./shell.nix` where `shell.nix` is:

```
{pkgs ? import <nixpkgs> {}}:

with pkgs;

let
  neuronGit = builtins.fetchGit 
  { url = "https://github.com/srid/neuron"; 
    rev = "274bcafe85fc2bae0a348ab91818d21c72d786db"; 
  };
  
  neuron = import neuronGit.outPath 
  { inherit pkgs;
    gitRev = neuronGit.shortRev; 
  };
in

mkShell
{ buildInputs = [ neuron ];
}
```

**Comment by srid** [comment]
neuron and rib uses `developPackage` which detects if we are in shell automatically. This looks like the same issue as https://github.com/NixOS/nixpkgs/issues/9438

Meanwhile here's a workaround:

```nix
{pkgs ? import <nixpkgs> {}}:

with pkgs;

let
  neuronGit = builtins.fetchGit
  { url = "https://github.com/srid/neuron";
    rev = "274bcafe85fc2bae0a348ab91818d21c72d786db";
  };

  neuron = import neuronGit.outPath
  { gitRev = neuronGit.shortRev;
  };

  wrapper = writeShellScriptBin "neuron-wrapper"
    ''
    ${neuron}/bin/neuron $*
    '';
in

mkShell
  { buildInputs = [wrapper];
  }
```

**Comment by srid** [comment]
Oh that didn't work. Nevermind.

**Comment by theNerd247** [comment]
I tried to create a package overrides using `haskellPackages.override` and then `import <nixpkgs> { inherit config}` as shown at @Gabriel439  tutorial: https://github.com/Gabriel439/haskell-nix/tree/master/project2. However this resulted in the same error. Could this be an upstream issue with the way developPackage works?

**Comment by srid** [comment]
`developPackage` will return the ghc environment if invoked from shell, which would explain the issue. 

See https://github.com/NixOS/nixpkgs/blob/d13a19cfbaf43b1ad2fcf835b1a05410c2f98bcb/pkgs/development/haskell-modules/make-package-set.nix#L231-L244

Can you try the following:

1. Clone this repo
2. Run `nix run` on it
3. Neuron should be in PATH

**Comment by srid** [comment]
And one solution for that is to pass the `returnShellEnv` argument explicitly. This will have be threaded from through the default.nix of both neuron and rib. PR for this welcome.

**Comment by theNerd247** [comment]
👍  I'll give it a shot.

**Comment by theNerd247** [comment]
Just a thought but what would  be the disadvantages of not using `developPackage`? I get the feeling that threading arguments across derivations isn't a good approach.

**Comment by srid** [comment]
At this point I think we can deviate away from `developPackage`, and drop one level lower as it where. See here for an example: https://github.com/kowainik/summoner/blob/60de4f2f087e5bd2beaad9253e7eded731cfbaaf/default.nix

Especially the last line:
```
if pkgs.lib.inNixShell then projectShell else projectDrv
```

You'd still have to handle the "in nix shell" or not case.

**Comment by srid** [comment]
> You'd still have to handle the "in nix shell" or not case.

In which case, we might as well continue to use `developPackage`.

**Comment by theNerd247** [comment]
Hmm...just thinking out loud here: the point of the `if pkgs.lib.inNixShell then projectShell else projectDrv` line is for convenience when someone wants to work on that package. This creates issues when someone wants to import their derivation because they have no control over whether they get a shell-derivation or the package-derivation. Paramerizing `pkgs.lib.inNixShell` would also just push the problem further up the dependency chain where transitive dependencies now have this extra argument to worry about. I'd be happy to rewrite the `default.nix` for both `rib` and `neuron` to be more consumer friendly if you'd like.

**Comment by srid** [comment]
> I'd be happy to rewrite the default.nix for both rib and neuron to be more consumer friendly if you'd like.

@theNerd247 Feel free to give that a try. I don't imagine it will be a radical change .. and will probably be along the lines of summoner's old default.nix linked above, though I suppose we could also create a dedicated `shell.nix` that imports `default.nix` and returns the project shell. So default.nix remains consumer friendly (nix-build and importing from config), while shell.nix is used when one wants to use nix-shell.

**Comment by srid** [comment]
Just a note: #172 rewrites pretty much all of default.nix, and it will soon be merged to `master`. And it works well with nix-shell, so you should give it a try after it gets merged.

**Comment by srid** [comment]
@theNerd247 You can now start the nix-shell like this:

```sh
# Run from the repo
nix-shell -p "import ./."
```

Or simply:
```sh
nix-shell -p 'import (builtins.fetchTarball "https://github.com/srid/neuron/archive/master.tar.gz")'
```

**Comment by theNerd247** [comment]
Excellent! Thanks!
