### ISSUE TITLE
Zettel search in CLI

### ISSUE THREAD

**Issue by srid** [srid/neuron#14]
A command that searches zettels by title (or content) and outputs the filepath of the selected zettel. Use `fzf` and `ripgrep` (made available via static [which](https://github.com/obsidiansystems/which)) to implement.

CLI - `neuron search`. Direct edit CLI: `vim $(neuron search)`.

**Comment by gillchristian** [comment]
Hi srid, I just found out about neuron and really like the idea! 👏

Do you envision search to also be possible on the rendered version?

Eg.

- Filtering on the `z-index` view by title.
- A dedicate search view and the results could show some info of the linkex zettles.

**Comment by srid** [comment]
Hey @gillchristian - the rendered version is currently statically generated HTML (by [rib](https://github.com/srid/rib)). I suppose we can add some sort of _client-side_ full-text search to neuron (eg: [js-search](https://github.com/bvaughn/js-search), which arrived at the top of my search results).

For now, I use the browser's `Ctrl+F` to find relevant zettel at z-index by its title. Or, if I'm in the CLI, I have a script that will search zettels and print the matching filename (to be opened in vim or whatever). It looks like this:

```bash
#!/usr/bin/env bash
set -euo pipefail

cd ./a

rg --no-heading --no-line-number --sort path "title:" *.md \
  | fzf --tac --no-sort -d ':' -n 3.. \
    --preview 'bat --style=plain --color=always {1}' \
    --bind 'ctrl-j:execute(google-chrome-stable https://self.srid.ca/notes/(echo {1} | sed "s/\.md/.html/g"))+abort' \
  | awk -F: '{printf "%s", $1}'
```

The purpose of this issue is to have `neuron search` do what this script effectively does.

> EDIT: this is not a feature request, I'd be interested on contributing to build such feature.

Sure, feel free to open a new issue to write your proposal. :-)

**Comment by gillchristian** [comment]
Agree, terminal command should take priority. I'll open an issue when I have a more specific suggestion or proposal in mind.
