### ISSUE TITLE
Clean HTML output when zettels are deleted

### ISSUE THREAD

**Issue by felko** [srid/neuron#141]
Currently `neuron rib` adds .html files from new zettels, but never deletes files from the `.neuron/output` directory. Could `neuron rib` take care of deleting previously generated HTML files that no longer have an associated zettel? Unused HTML files might clutter disk space. Maybe something like `neuron rib --clean`?
(Maybe this should be a rib issue?)

**Comment by srid** [comment]
> Maybe this should be a rib issue?

Yes. See https://github.com/srid/rib/issues/155. PR welcome. :-)

**Comment by srid** [comment]
Workaround in the interim:

```bash
rm -rf .neuron/{.shake,output}
neuron rib 
```

**Comment by srid** [comment]
This can now be simply done here (by comparing the old hashmap with the new one)

https://github.com/srid/neuron/blob/4473dc1ddcb2a96915272b6023919b5c58d12e1b/neuron/src/app/Neuron/Reactor.hs#L87-L89
