### ISSUE TITLE
Date ID conflicts in community zettelkastens

### ISSUE THREAD

**Issue by srid** [srid/neuron#148]
_Originally posted by @michelk in https://github.com/srid/neuron/issues/59#issuecomment-621047640_

> We should keep in mind that the current zettel-id-scheme is not ideal for community zettelkästen, since multiple users can generate the same zettel-id on the same day, which results in annoying merge conflicts. 

> Some sort of random hash would be more appropriate for that.

**Comment by srid** [comment]
@michelk Yes, that's a real problem in community zettelkastens (not so much in personal zettelkastens, however, which I imagine would be the most common use case). 

I don't really like forcing users to always use long random hashes, so here's a way to solve the problem:

1. Provide first-class support custom alpha numeric IDs. Today you can link to a zettel as `<FooBar>`, but it is not supported throughout neuron. We can change this and have, for example, `neuron new --id=FooBar` create a zettel with a custom ID.

1. Since custom IDs don't encode date, let's support a `date` field in the Markdown metadata where the user specifies the creation date (`neuron new` can automatically do this). So that things like `?linkTheme=withDate` will work for all types of ID.

With that in place, if someone is working on a branch of their community zettelkasten, they can create zettels using the custom ID to avoid unnecessary conflicts. If they wish, they can use random hashes, using `neuron new --id=$(openssl rand -hex 8)`, and neuron wouldn't care about the format of IDs as long as it contains only alpha numeric letters.

**Comment by srid** [comment]
We could go one step further and deprecate (not drop) support for date IDs altogether, while also changing the appearance of zettel links to be more Roam like (i.e., link text being set to zettel title).

**Comment by srid** [comment]
@michelk Could you give the latest `master` branch a try? You can use the `neuron new --id-hash` command to use IDs based on a random hash. I am yet to make it the default; but let me know how it works out for you and others.

**Comment by srid** [comment]
Resolved. See #151 for a migration script, though it is not necessary.

**Comment by michelk** [comment]
Cool. Thanks a lot. 

There are some pitfalls in the migration-script, when there are `<>` symbols, e.g. `import <nixpkgs>`.

Otherwise works great.
