### ISSUE TITLE
Deprecate date IDs and use regular link style

### ISSUE THREAD

**Issue by srid** [srid/neuron#151]
This resolves #148, as well as simplifies things a bit.

1. [x] Switch to using short random hash (eg: `b6f044c8`) as the default zettel filename. This is same as the current custom ID type (arbitrary length of alpha numeric letters with hyphens and underscores). Date ID will be supported, but won't be the default in `neuron new`.
    - [x] Add random hash support
    - [x] Make random hash the default
    - [x] ~~Migrate neuron.zettel.page IDs to be consistent?~~ (cancelled; not to break URLs)

2. [x] Add an (optional) "date" metadata field to the zettels to indicate the creation date of the Zettel (populated by `neuron new`).

3. [x] Switch zettel link style to be like regular links, i.e, instead of the ID put the title as the link text (with ID not appearing at all, but only as hover text). It will look like this:

![image](https://user-images.githubusercontent.com/3998/80667052-187a7100-8a6c-11ea-9f1b-e21e8c6041ee.png)

Since custom IDs can be of arbitrary length it makes little sense to try to visually emphasize them in the UI, hence no. 3.

**Comment by felko** [comment]
Here is a script that might help the migration <https://gist.github.com/felko/f71582747ea9bab8ef2f38e7730991b6>. It replaces file names and short links, and adds a date field in the metadata of each zettel. Usage: `python3.8 migrate.py source_zettelkasten_dir target_zettelkasten_dir`

**Comment by srid** [comment]
I've adapted this script with a few changes:

* Limit the script to zettels created with date ID only (so existing zettels using custom or hash ID are left alone)
* Use creation date encoded in the date ID instead of filesystem `stat` (which would be inaccurate in git checkouts)
* Delete original zettel as soon as the new one is successfully written. You can do a `git add .` afterwards and do a `git status` to see what's changed.

https://gist.github.com/srid/a1321d559fd1a5fe464bb20c1a536107

**Comment by srid** [comment]
All done.
