### ISSUE TITLE
Mention Windows support

### ISSUE THREAD

**Issue by srid** [srid/neuron#156]
I tried out neuron on Windows via WSL. This is the only workaround needed: https://github.com/NixOS/nix/issues/2292#issuecomment-443933924

And neuron works fine.

Might want to look into how to install and setup Doom Emacs with neuron-mode.

**Comment by RoyiAvital** [comment]
Please consider native support.
Your applications looks so promising and many of us are using Windows.

If Pandoc can create single binary form Haskell I guess it is doable. Right?

**Comment by srid** [comment]
Contributions are welcome for that.
