### ISSUE TITLE
Query results as connections

### ISSUE THREAD

**Issue by michelk** [srid/neuron#160]
When there is a query like `<z:zettels?tag=walkthrough&cf>` this should also show up as connections in the graph.

**Comment by srid** [comment]
I don't understand. They already do indeed become part of the graph. If you remove the `&cf`, they will belong to the category tree (z-index) as well.

**Comment by michelk** [comment]
Ahh, ok. In my Zettelkasten, I had (maybe the old) syntax  `[.](zcfquery://search?tag=science*)`.

Thanks for the hint.
