### ISSUE TITLE
Idea: User interface inspired by git

### ISSUE THREAD

**Issue by michelk** [srid/neuron#161]
Following suggestions for the user-interface
- Switch program name from `neuron` to `zk` for faster typing
- Have a default Zettelkasten directory per project e.g. `.zk/`
- Use per default the  Zettelkasten (`.zk`) directory, by searching in the descending directory tree
- Each project then could have its own zettelkasten and `zk` automatically finds it.

**Comment by srid** [comment]
I like the idea of obviating the `-d ..` argument when working on multiple Zettelkastens, but I'm not sure about this approach. What would the workflow be like for someone that uses neuron to manage a _single_ zettelkasten, at ~/zettelkasten (i.e., no project directories)?

**Comment by maralorn** [comment]
> What would the workflow be like for someone that uses neuron to manage a _single_ zettelkasten, at ~/zettelkasten (i.e., no project directories)?

One idea in two different versions:

1. `.zk` can contain a link to a different root for the project. Then `~/.zk` can somehow point to `~/zettelkasten`.
2. Configure a default zettelkasten to use when not finding a `.zk`.

**Comment by srid** [comment]
Here's another point of confusion: zettelkasten notes are not necessarily associated with a (software?) project. 

For example, here are two zettelkastens:

* https://github.com/srid/haskell.zettel.page
* https://github.com/srid/emacs.zettel.page

They are just git repos with note files. Where would the `.zk` directory fit in here?

---

As an aside, there is the optional [`neuron.dhall`](https://neuron.zettel.page/2011701.html) configuration file, which could perhaps be used to automatically designate a directory to be a zettelkasten directory. Though it is not clear how this would solve the goal of obviating `-d`.

**Comment by michelk** [comment]
I would still keep the  (then optional) `-d`flag. So the current workflow doesn't change. Just when it is omitted, search for a conventional zettelkasten directory name (`.zk` or `.neuron`) in the descending directory tree, like `git` does.

I think `neuron` is extremely helpful in (collaborative) project work. And each of my software and client-projects could contain a zettelkasten-directory to initially document bits and aspects of the work done. This then easily compiles to a technical report or software-tutorial or whatever.  Thanks @srid here for the great work.

Therefor, dealing with multiple zettelkästen, my `.zshrc` has multiple statements like e.g.

```zsh
alias zk="neuron -d ~/zettelkasten"
alias zkhs="neuron -d ~/doc/haskell-zettelkasten"
```
But this gets tiresome, when project-zettelkästen are added. Because of that, it would be more comfortable to be able to do e.g.

```
cd projects/path/to/somewhere
do some work
zk new -e "Done this and that"
```
with zettelkasten-directory `projects/.zk` (or `projects/.neuron` if you like)

It would also be neat, if we had a `~/.config/neuron.dhall` to specify e.g. the editor.

In my opinion we also should make the `-e` flag in `new` and `search` the default and use another flag to just emit the zettel-id-file.

**Comment by srid** [comment]
> with zettelkasten-directory `projects/.zk` (or `projects/.neuron` if you like)

The proposal is not yet fully clear to me.  There is already a `.neuron` directory, which holds the internal Shake database as well as the generated HTML files (which `neuron open` uses). Can you provide a detailed example, like the one below?

```bash
$ mkdir /tmp/zk1
$ neuron -d /tmp/zk1 new "First zettel"
/tmp/zk1/cbcebe33.md
$ neuron -d /tmp/zk1 rib
[Rib] Generating /tmp/zk1/ (rebuildAll=False)
# /tmp/zk1/cbcebe33.md
+ /tmp/zk1/.neuron/output/cbcebe33.html
+ /tmp/zk1/.neuron/output/z-index.html
+ /tmp/zk1/.neuron/output/search.html
+ /tmp/zk1/.neuron/output/index.html
$ tree /tmp/zk1/.neuron
/tmp/zk1/.neuron
└── output
    ├── cbcebe33.html
    ├── index.html
    ├── search.html
    └── z-index.html

1 directory, 4 files
$
```

**Comment by srid** [comment]
Take the neuron project as an example. Its zettelkasten is at the `./guide` directory (with the associated `.neuron` directory at `./guide/.neuron`). What would be the exact algorithm that neuron should use in order to automatically "detect" the default zettelkasten it should use?

**Comment by maralorn** [comment]
I understood it this way. When neuron is called (don‘t know if I care about renaming it too zk), the following algorithm looks for the zettelkasten.

1. Use the directory given with -d, if given.
2. Check if the current directory contains a `.neuron` directory. If yes use this directory.
3. Go one directory up and go to 2. If `/` is reached continue.
4. Check if there is a default directory defined in a neuron.dhall config file somewhere. Use that if given.
5. Use ~/zettelkasten.

> Take the neuron project as an example. Its zettelkasten is at the `./guide` directory (with the associated `.neuron` directory at `./guide/.neuron`). What would be the exact algorithm that neuron should use in order to automatically "detect" the default zettelkasten it should use?

That‘s I think something which does not really fit the `git` analogy.

But what you do think about using symlinks? You could have a `.neuron -> guide/.neuron` symlink in the repo and neuron understands the symlink and finds the Zettelkasten that way?

This could also be an additional or alternative way for point 4. in my List. Just have a `.neuron` symlink in your home-dir pointing to the `.neuron` of your Zettelkasten.

Just an idea. Maybe we can do better.

We would also need something like `neuron init` for this to work nicely.

**Comment by srid** [comment]
Okay, step 1,2,3,5 make sense. Not step 4 - because neuron.dhall is a _per_-zettelkasten config that lies in the _very_ zettelkasten directory we are trying to locate.

> But what you do think about using symlinks? You could have a `.neuron -> guide/.neuron` symlink in the repo and neuron understands the symlink and finds the Zettelkasten that way?

Yes, I think that's a good idea.

> We would also need something like `neuron init` for this to work nicely.

Right; `neuron init` should create the first zettel file, as well as run `neuron rib` on it, so that `.neuron` gets created (for the first time). Additionally, it could generate the `neuron.dhall` file; in which case, the proposal receives the option of searching for `neuron.dhall` (file or symlink) instead of `.neuron`.

PR welcome!

**Comment by maralorn** [comment]
Okay sorry for mixing up the `neuron.dhall`, I actually haven‘t used `neuron` productively so I didn‘t know how it works.

So as far as I understand `.neuron` only contains cached data until now and therefore is kinda an implementation detail the user shouldn‘t care about?

So I think we should center around the `neuron.dhall` file? But if we wanna go full git mode we could make it `.neuron/config.dhall`. I kinda like that idea. But it‘s your call.

**Comment by maralorn** [comment]
Also maybe @michelk wants to voice an opinion here. I kinda hijacked their suggestion.^^

**Comment by michelk** [comment]
Well my original  thought was to have something like below, where the `.neuron` directory contains all zettels and the generated site. And calling `neuron` say from `/tmp/project1/app` finds `/tmp/project1/.neuron` as zettel-directory.

```
/tmp/project1
├── app
├── .neuron
│   ├── 47c953f2.md
│   ├── 78377b7b.md
│   ├── 99d3a398.md
│   ├── index.md
│   ├── neuron.dhall
│   ├── .shake
│   │   ├── .shake.database
│   │   └── .shake.lock
│   └── _site
│       ├── 47c953f2.html
│       ├── 78377b7b.html
│       ├── 99d3a398.html
│       ├── index.html
│       ├── search.html
│       └── z-index.html
├── nix
├── src
└── test
/tmp/project2
├── app
├── .neuron
│   ├── 0a9e0b82.md
│   ├── 1b5549b1.md
│   ├── e7db5bf1.md
│   ├── index.md
│   ├── neuron.dhall
│   ├── .shake
│   │   ├── .shake.database
│   │   └── .shake.lock
│   └── _site
│       ├── 0a9e0b82.html
│       ├── 1b5549b1.html
│       ├── e7db5bf1.html
│       ├── index.html
│       ├── search.html
│       └── z-index.html
├── nix
├── src
└── test
/tmp/project3
├── app
├── .neuron
│   ├── 66274493.md
│   ├── a7dc6556.md
│   ├── c2c76b5e.md
│   ├── index.md
│   ├── neuron.dhall
│   ├── .shake
│   │   ├── .shake.database
│   │   └── .shake.lock
│   └── _site
│       ├── 66274493.html
│       ├── a7dc6556.html
│       ├── c2c76b5e.html
│       ├── index.html
│       ├── search.html
│       └── z-index.html
├── nix
├── src
└── test

```

**Comment by Nadrieril** [comment]
I don't like that the directory should start with a dot. The convention is that

**Comment by michelk** [comment]
In my opinion, it is in that sense more `gitish` as you usually don't interact directly with the zettelkasten directory; and all actions are done with the `neuron` command line tool (`new`, `search`, `open`, `edit` ...).   

And I think, it is unlike `doc`, where the filenames make sense (e.g. `tutorialA.md`, `introduction.md`).

**Comment by maralorn** [comment]
Well I at least plan to give my neuron files names which make sense. So there seem to be different usecases.

Also sometimes I imagine people use a zettelkasten without any other files in it. Wouldn‘t it be a bit weird it your zettelkasten where only an "empty" dir containing just a hidden dir?

**Comment by michelk** [comment]
... and it is still possible to do

```bash
ln -s ~/.neuron ~/zettelkasten
```

or 

```bash
ln -s projectA/.neuron projectA/doc
```

**Comment by michelk** [comment]
[Here](https://gist.github.com/michelk/76c5d86cd158cc3d2cc955ae6adc1dff)'s a little wrapper program, that does what I want.

**Comment by srid** [comment]
I can't explain why, but something about using symlinks in this proposal makes me feel uncomfortable. 

An alternative to consider in the proposal is to add an extra field to `neuron.dhall` that will explicitly specify the path to the notes (defaulting to same directory).This way you can put neuron.dhall at the top-level of the project repository, and add a `path` field to it pointing to a relative path like `./guide`.

**Comment by leira** [comment]
> Following suggestions for the user-interface
> 
> * Switch program name from `neuron` to `zk` for faster typing

It is a good idea to use a shorter program name. I like `zk`.

> * Have a default Zettelkasten directory per project e.g. `.zk/`
> * Use per default the  Zettelkasten (`.zk`) directory, by searching in the descending directory tree
> * Each project then could have its own zettelkasten and `zk` automatically finds it.

Why does one need so many Zettelkästen? It seems kinda defeat the purpose. Can you please elaborate on the use cases? Or are you suggest just use neuron as a documentation system?

**Comment by srid** [comment]
I manage quite a few disparate sites using neuron:

- my private zettelkasten (personal notes)
- https://www.srid.ca/ (neuron as personal blog/website)
- https://alien-psychology.zettel.page/ (special interest site)
- https://guide.cerveau.app/ (neuron as product documentation)
- https://neuron.zettel.page/ (neuron as project documentation)

(Incidentally, except the last, I manage them all in the web browser through [Cerveau](https://neuron.zettel.page/041726b3.html)).

**Comment by michelk** [comment]
@leira We are doing numeric modeling. For every client project I have a zettelkasten for an initial documentation of bits and pieces. Neuron is very handy for that; I do everything from the command-line.

**Comment by srid** [comment]
Given that neuron doesn't do sub-directories, I see no reason why we should do the whole parent-directory dance? 

Here's what I think we should do (unless I'm missing something):

- Look for neuron.dhall in $PWD
- If it exists, use $PWD as zettelkasten directory
- If not, error out.

Basically, behave like git, using `./neuron.dhall` instead of `./.git`.

**Comment by srid** [comment]
Closing in favour of #389
