### ISSUE TITLE
Problems installing Neuron on Windows and Amazon Linux

### ISSUE THREAD

**Issue by ankitadhandha** [srid/neuron#162]
We can successfully install `neuron` on Windows 10 WSL and Amazon Linux following these steps:

<https://neuron.zettel.page/2011501.html>

When we run: 

`neuron --help`

or

`neuron -d zettlekasten rib -wS`

`neuron` prints the message indicating that it is loaded. 

But when we run <http://localhost:8080> or the AWS-EC2-IP-address:8080, `neuron` prints following message:

> Error: This site can’t be reached localhost refused to connect.

Note: we have added firewall rule for port 8080.

If we curl <http://localhost:8080>, it prints correct html.

A second, and probably related, issue is that the install did not create a `neuron` folder in $home directory.

What have we done wrong? Our mistake seems to be the same for WSL and AWS/Linux.

We want to test using WSL, but deploy on AWS/Linux.

Thanks for guidance here.

/ankita dhandha

**Comment by f-f** [comment]
Have you tried with `neuron -d zettelkasten rib -w -S 0.0.0.0:8080`?

**Comment by ankitadhandha** [comment]
After running this:

`neuron -d zettelkasten rib -w -S 0.0.0.0:8080`

Getting error:
Invalid argument `0.0.0.0:8080'

Usage: neuron [--version] [-d|--zettelkasten-dir NOTESDIR] COMMAND
  Neuron, a Zettelkasten CLI <https://neuron.zettel.page/>

**Comment by srid** [comment]
It should be `s`, not `S`.

i.e., `neuron rib -ws 0.0.0.0:8080`

**Comment by srid** [comment]
> A second, and probably related, issue is that the install did not create a neuron folder in $home directory.

Hmm, why would you expect it to create `$HOME/neuron`? The default notes directory is `$HOME/zettelkasten` (which has to be manually created). The generated files go to `$HOME/zettelkasten/.neuron/output`.

> We want to test using WSL, but deploy on AWS/Linux.

Note that you can also deploy the generated HTML files in `.neuron/output` to any static site host, including [Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html).

**Comment by jaygray0919** [comment]
Isn't the directory `neuron` in $HOME created for the neuron `guide`?

Understood (and completed):
>The default notes directory is `$HOME/zettelkasten` (which has to be manually created). The generated files go to `$HOME/zettelkasten/.neuron/output`.

**Comment by ankitadhandha** [comment]
`rib` seems to correctly generate HTML files from MD files
they are in $home/zettelkasten/.neuron/output
but it seems some system configuration problem.

Thanks
