### ISSUE TITLE
Idea: other types of links

### ISSUE THREAD

**Issue by Nadrieril** [srid/neuron#165]
When I link from one zettel to another the links don't always mean the same thing. For example a thing I often do is start a zettel B by mentioning another zettel A that sparked the thought for B. But with the current tree view, I get A shown under B.

There are two kinds of links I think would be cool additions:
- Reversed links, that make an edge in the graph directed the other way. Applied to my example, that would make B shown under A
- Sibling links, that indicate that the two notes follow each other sequentially. That would make A and B show up at the same level. We would have a distinction between forward and backward siblings to control the ordering. That would complicate the graph quite a bit, but I think sequences are a distinguishing feature of Zettelkasten that are difficult to do with neuron currently.

**Comment by srid** [comment]
> Reversed links

So something like:

```markdown
<feb32b3s?reversed> 
```

> Sibling links, that indicate that the two notes follow each other sequentially. That would make A and B show up at the same level. 

_Under_ what zettel parent note, however, would A and B show up? A detailed example would be more illustrative. 

> I think sequences are a distinguishing feature of Zettelkasten that are difficult to do with neuron currently.

Hmm, I don't understand what you mean by difficult. To link to a sequence of zettels, can't you just use a list of links, like [this zettel](https://neuron.zettel.page/2011402.html) does?

**Comment by Nadrieril** [comment]
> > Sibling links, that indicate that the two notes follow each other sequentially. That would make A and B show up at the same level.
> 
> _Under_ what zettel parent note, however, would A and B show up? A detailed example would be more illustrative.

The idea I had was that if B says that A should precede it as a sibling, then whenever A appears as a child of a node in the tree, then B should appear after it as another child of that same node. The idea would be that I have a train of thought on a particular idea, and that train is made up of siblings so that they appear together when I link to the first.

> > I think sequences are a distinguishing feature of Zettelkasten that are difficult to do with neuron currently.
> 
> Hmm, I don't understand what you mean by difficult. To link to a sequence of zettels, can't you just use a list of links, like [this zettel](https://neuron.zettel.page/2011402.html) does?

Well, it's annoying to edit a different zettel from the one you are currently editing. And maybe the list of links makes it more hierarchical than it's meant to? Also I was thinking it could make navigation easier, but that depends on how the backlinks are displayed.

All in all I have to say I'm not entirely convinced this is a useful idea, I haven't yet figured out how to structure my zettelkasten effectively.

**Comment by jaygray0919** [comment]
Graphs are hard. If there is a move to add formalism to zettel `types` and zettel `relationships`, we suggest a light-weight implementation of the schema.org ontology and JSON-LD syntax. The benefit to using schema.org/JSON-LD v. another `ontology` is that many developers already use it on their web pages. For example, it's easy to express `@Class` hierarchies in schema - or just use the hierarchies that schema has already defined.
But this move might `complexify` a simple, easy-to-use, easy-to-organize architecture.
The proposal is logical and understandable, but something that should be considered **after** the fundamental architecture - as designed - gains traction.

**Comment by srid** [comment]
FWIW, the generated HTML already contains JSON-LD breadcrumbs (see #147), which show up in google search (see below. Adding structured markup (#27) is in the roadmap. @jaygray0919 Any specific schema.org/JSON-LD we can use in order to describe relationships? Could you link me to some documentation on "`@Class hierarchies in schema"?

![image](https://user-images.githubusercontent.com/3998/82108612-95a91580-96fd-11ea-80fa-513d2fd65991.png)

**Comment by Nadrieril** [comment]
After reading [Andy's notes](https://www.reddit.com/r/Zettelkasten/comments/gmso12/a_brilliant_and_actionable_guide_to_better/), I have changed how I think about how to organize my Zettelkasten and I don't desire this feature anymore. Roughly my main way of navigating my notes used to be through the z-index, and those link types were meant to help curate that tree. Now I understand what "densely linked" means so I don't need the z-index as much.
I'm closing the issue, but if someone still wants that feature it can be reopened.

**Comment by srid** [comment]
This resurfaced on Matrix forum: https://app.element.io#/room/#neuron:matrix.org/$RbOb7aFPv8tG8GXmImYGXn-dWjgl36W8iAb3fo9kq98

**Comment by srid** [comment]
@Nadrieril Take a look at recent proposals. "Reversed link" is conceptually the same as tagging (where tag == zettel). See #514
