### ISSUE TITLE
neuron issue with file descriptor

### ISSUE THREAD

**Issue by smunix** [srid/neuron#171]
`neuron -d . rib -wS` with ongoing directory change monitoring ended up with:

`neuron: file descriptor 98098248 out of range for select (0--1024)`

**Comment by srid** [comment]
Is that the only error, or were there more output from neuron? Can you provide some specifics of your Zettelkasten? Are you able to reproduce this consistently?

**Comment by srid** [comment]
https://gitlab.haskell.org/ghc/ghc/issues/4351

**Comment by smunix** [comment]
> https://gitlab.haskell.org/ghc/ghc/issues/4351

spot on! unfortunately, it has only happened once and doesn't occur consistently. There was no coredump generated either, I couldn't search the stack track.

If your suspicion is right on it being an RTS issue, after looking into neuron.cabal, there's no -threaded option passed to ghc option.

I didn't compile/install neuron as per [Install Neuron](https://neuron.zettel.page/2011501.html), i.e.

```sh
nix-env -iE '_: 
  let src = builtins.fetchGit { 
    url = "https://github.com/srid/neuron"; ref = "master"; }; 
  in import src.outPath { gitRev = src.shortRev; }'
```

As to what's specific about my Zettelkasten, I was making changes to it for some time, while a `neuron -d . rib -wS` kept reacting to new file changes.

I'll let you know if I can hit this issue again and can pull further details out of it.

**Comment by smunix** [comment]
It happened again. Here's my Zettelkasten, [smunix.gitlab.io](https://smunix.gitlab.io/)

There's a suggestion to recompile with `-threaded` to work around this.

```
[Rib] Generating zettelkasten/ (rebuildAll=False)
# zettelkasten/d62235d4.md
+ zettelkasten/.neuron/output/75c581f8.html
+ zettelkasten/.neuron/output/d62235d4.html
+ zettelkasten/.neuron/output/z-index.html
A /home/smunix/Documents/Zettelkasten/smunix.gitlab.io/zettelkasten/.#d62235d4.md
[Rib] Generating zettelkasten/ (rebuildAll=False)
M /home/smunix/Documents/Zettelkasten/smunix.gitlab.io/zettelkasten/d62235d4.md
D /home/smunix/Documents/Zettelkasten/smunix.gitlab.io/zettelkasten/.#d62235d4.md
[Rib] Generating zettelkasten/ (rebuildAll=False)
# zettelkasten/d62235d4.md
+ zettelkasten/.neuron/output/d62235d4.html
neuron: file descriptor 148609888 out of range for select (0--1024).
Recompile with -threaded to work around this.
```

**Comment by srid** [comment]
@smunix Just enabled `-threaded` on latest `master`; give that a try.

**Comment by smunix** [comment]
ack, thanks !

**Comment by smunix** [comment]
This hasn't happened in the last 10 days after your last fix, @srid. I'm closing this for now.
