### ISSUE TITLE
`---` in yaml header breaks parsing

### ISSUE THREAD

**Issue by Nadrieril** [srid/neuron#173]
I have the following file:
```markdown
---
title: 'Some long title ---
  example.com'
---

Blah
```

The parser chokes on the `---` encountered here. Interestingly, the error didn't point to the file responsible for this, I had to bisect through all my zettels. The error was:
```
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:
  at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.18.5-FiYl23VJG3R4szXGah8kHH:Development.Shake.Forward
* Raised the exception:
user error ((Pos {posByteOffset = 60, posCharOffset = 60, posLine = 1, posColumn = 60},"Unexpected end of input"))
```

**Comment by srid** [comment]
Seems to be a bug in `partitionMarkdown` not being able to split the yaml from markdown body.

https://github.com/srid/neuron/blob/d588b60070bced347015d7e6b0df19c4d971a6ad/src/lib/Neuron/Markdown.hs#L60-L72

**Comment by Nadrieril** [comment]
Can you ensure that the `---` is at the start of a line? Assuming `M.eol` captures an eol char, `separatorP = void $ M.eol *> M.string "---" <* M.eol` might work.

**Comment by srid** [comment]
> Can you ensure that the --- is at the start of a line? 

That sounds like the way to fix it.

I've addressed the error message in https://github.com/srid/neuron/commit/f80ee01e50b3893069a52f9d9368b8c0ef49318b
