### ISSUE TITLE
Derivations for `shell.nix` not present on your cachix

### ISSUE THREAD

**Issue by Nadrieril** [srid/neuron#174]
Using your cachix instance, I can build the `neuron` package without having to rebuild ghc and many other things, and that's great! However, if I want to hack on neuron using `shell.nix`, then I end up having to rebuild countless things, including for example `/nix/store/72qbp1ss0plkf1g01c41z866xcn7m4gd-Cabal-3.0.0.0.drv` which keeps getting OOMed before completing.
Would it be possible to include those artifacts on your cachix as well?

**Comment by srid** [comment]
Oh, that's bad developer experience. How much memory do you have?

I've jush pushed nix-shell derivations to cachix; give it a try.

If that works, I'll have to add this to the CI so the cache updates automatically.

**Comment by Nadrieril** [comment]
I have 8G but was running other things, and I think it got to ~4G before getting killed.
Yep that works, I was just able to use the nix-shell in under a few minutes! Thanks
