### ISSUE TITLE
Document commonmark attributes extension

### ISSUE THREAD

**Issue by srid** [srid/neuron#176]
Explain how to add custom HTML attributes to the various elements using [commonmark attributes](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/attributes.md), including images.

For example,

```markdown
![](https://srid.keybase.pub/me.jpeg){#avatar .ui .left .floated .small .image}
```

Also reference [Semantic UI](https://fomantic-ui.com/) documentation for the potential list of classes one could use.

Dependent tasks:

- [x] Have reflex-dom-pandoc render table attributes (eg: `{.ui .basic .table} suffix`)

**Comment by srid** [comment]
Should also document GFM extensions.

**Comment by RoyiAvital** [comment]
If one can not add custom CSS, what's the point?

When I say custom CSS I mean in addition to and not instead.
I want to use the current template, I just want to be able to customize it.

**Comment by srid** [comment]
You can add custom CSS in `head.html`. https://neuron.zettel.page/examples

**Comment by RoyiAvital** [comment]
We have talked about this.
The problem is you allow `head.html` to replace the default one while we need a way to extend it.

**Comment by srid** [comment]
You are talking about #253

**Comment by srid** [comment]
You are talking about #253?

No, head.html does not replace the default one. The default CSS is still in use (except for Prism and Mathjax; which should be included https://neuron.zettel.page/custom-head )

**Comment by RoyiAvital** [comment]
I am saying the current approach is having `head.html` to add something to `<head>`.
Moreover, you generate the default `<head>` in the Neuron code.

Now, assume I created my own `head.html` and I'm using version `2`.
When you releases version `2.1` you added very new cool feature through `<head>` and I won't have it.

So, my suggestion is either:
1. Have an option in Neuron to use `head.html` as an addition (Inject Text) and not as a replacement.
2. Each release will have its default `<head>` as a file in the Neuron folder for the user to edit.

**Comment by srid** [comment]
@RoyiAvital Please move this discussion to https://github.com/srid/neuron/discussions. In general, you should always use the discussions forum, and comment on issues only if it is directly relevant to the issue in question.

As to your suggestion 1, it was discussed here #579 - and your suggestion 2 will require a specific proposal as to their UX. Again, please write this in the discussions forum.
