### ISSUE TITLE
neuron 0.4 upgrade documentation

### ISSUE THREAD

**Issue by jaygray0919** [srid/neuron#179]
Is there documentation for upgrading to 0.4 on WSL?
would like to avoid doing anything stupid.
/jay gray

**Comment by srid** [comment]
You run the same command.

* To upgrade to 0.4:

```
nix-env -iE '_: 
  let src = builtins.fetchGit { 
    url = "https://github.com/srid/neuron"; ref = "master"; }; 
  in import src.outPath { gitRev = src.shortRev; }'
```

* To upgrade to the latest (0.5 -- development version, which has better markdown support):

```
nix-env -if https://github.com/srid/neuron/archive/master.tar.gz
```

**Comment by srid** [comment]
@jaygray0919 I'd recommend using the latest; i.e., that second command.

**Comment by jaygray0919** [comment]
another flawless install! watching a neuron install is a lesson in software distribution; i've never seen anything like it. from one perspective: 'jeez there are a lot of dependencies.' from another perspective: 'jeez, i could never build anything with so many dependencies - it would overwhelm my mental model of an application.'

thanks srid.
