### ISSUE TITLE
Cluster detection

### ISSUE THREAD

**Issue by srid** [srid/neuron#18]
As the Zettelkasten grows, notes will naturally belong to specific clusters. For eg., science-related notes would be part of one cluster, whereas personal journal-related notes would be in an entirely different cluster. 

In computer science, we call this a [connected component](https://en.wikipedia.org/wiki/Component_(graph_theory)) of a graph. Pictured below is a graph with three connected components.

Neuron's z-index should distinctly display these components. If there are three components, for example, there should be three separate trees/forests.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Pseudoforest.svg/480px-Pseudoforest.svg.png)

**Comment by gillchristian** [comment]
I was wondering how to add multiple "entry points" to the `z-index`, the the moment only `index.md` is considered one.

Would this _solve_ that?

**Comment by srid** [comment]
At the moment, my multiple entry points are all linked from the top-level entry point `index.md`. 

With this feature, however, I hope to obviate `index.md` and have these entry points naturally emerge from the zettelkasten connections (i.e., without _explicitly_ designing them as an "entry point").

I am yet to fully flesh this feature out, but I imagine each cluster to have an (optional) single entry point -- i.e., if there is exactly one [mother vertex](https://www.geeksforgeeks.org/find-a-mother-vertex-in-a-graph/), it can automatically be promoted to be its entry point.
