### ISSUE TITLE
Cache does not work on macOS

### ISSUE THREAD

**Issue by srid** [srid/neuron#180]
I should set up a Mac CI agent for Hercules for this to work.

**Comment by srid** [comment]
I'm working on doing a fresh install of macOS on my mac. And then hookup hercules-ci to it.

**Comment by srid** [comment]
Until this gets fixed, users can setup the reflex-platform cache using these instructions https://github.com/obsidiansystems/obelisk#installing-obelisk on their mac ... it'll cut down the build time drastically, but there will still be some substantial amount of compiling from sources.

**Comment by srid** [comment]
I've manually pushed the macOS cache, if you anybody would like to test.

CI is still broken, however.

**Comment by felko** [comment]
Worked for me 👍
