### ISSUE TITLE
Web app for neuron

### ISSUE THREAD

**Issue by tchoutri** [srid/neuron#182]
Hi! First of all thank you very much for this project.
I wanted to suggest the implementation of zettel creation and edition from the web interface.
Indeed, I intend to use Neuron on a server of mine and I would love to be able to edit my zettels from mobile devices, or just be able to provide Zettelkasten hosting to people who cannot have the workflow that is currently required.

I could help you implement it, if you do not mind a bit of hand-holding since the codebase is mostly foreign to me right now. :)

Cheers!

**Comment by srid** [comment]
I'm already working on a project like this. Stay tuned for updates!

(For now though, you can store your zettels in a Git repo, and edit them on GitHub; and have your server do 'git pull && neuron rib' on regular basis, while serving the .neuron/output directory via nginx or something).

**Comment by tchoutri** [comment]
Thank you very much! :)
I'll wait for the proper implementation to come around then!

**Comment by srid** [comment]
For those wondering: <http://www.cerveau.app>

**Comment by srid** [comment]
Cerveau is now in public beta; anybody can now try it out!

Here's the announcement post: https://www.srid.ca/689c4a39.html
