### ISSUE TITLE
Connection labels

### ISSUE THREAD

**Issue by srid** [srid/neuron#185]
If zettel A links to zettel B, it would be nice if there was a way to write down notes on *why* such a connection exists. And then this "why" (typically a small blurb of text) can be displayed as a tooltip or something next to the link itself, which is especially useful when looking at the backlinks.

```markdown
<ef73jsj3>{reason="A growth mindset is essential for learning"}
```

^ This uses the [attributes](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/attributes.md) extension, and sets a "reason" attribute on the Pandoc Link AST node.

**Comment by srid** [comment]
It should probably also apply to tagging. That is, to answer "Why was this zettel tagged with this tag?"

```markdown
---
title: Frustrated regarding macOS Nix CI
tags:
  - journal/mindset{reason="Anger throws one off the learning mindset"}
  - journal/ikigai{reason="Feeling of rushing/impatience dislodges us from a state of flow"}
--- 
```

So the reason appears alongside the results of say the `<z:zettels?tag=journal/mindset>` query (that is used in the "Mindset" zettel)

**Comment by Nadrieril** [comment]
An alternative would be to include the context of a link (i.e. surrounding text) when displaying backlinks, like what is done here https://notes.andymatuschak.org/z3SjnvsB5aR2ddsycyXofbYR7fCxo7RmKW2be

**Comment by srid** [comment]
I suppose if you are careful enough to make the surrounding text give the full context of the link in a concise enough manner, then it would work better than an explicitly stated context (connection label).

This doesn't do anything for tags. But, we can address that by supporting "inline tags", and then use *its* surrounding context in query links. For example,

```markdown
Anger throws one off the learning #mindset. 

Feeling of rushing/impatience dislodges us from a 
state of flow, which is essential for #ikigai
```

These #-prefixed inline tags would obviate (even deprecate) the metadata tags we have currently.

**Comment by Nadrieril** [comment]
I like this approach to tags. This would make them closer to a normal zettel, where the # works as a reversed link

**Comment by srid** [comment]
Alright, it is good to see better ideas evolve out of this proposal. Closing this in favour of #190 which I feel is better.
