### ISSUE TITLE
Some text is invisible when using the "black" theme

### ISSUE THREAD

**Issue by srid** [srid/neuron#187]
![image](https://user-images.githubusercontent.com/3998/82053723-cd777500-968b-11ea-8967-bc06bfb24d51.png)

**Comment by srid** [comment]
Gray this has a similar problem, where the links are not very visually distinctive from the surrounding text:

![image](https://user-images.githubusercontent.com/3998/82092119-a68a6480-96c6-11ea-84c9-5eddce612254.png)

**Comment by Nadrieril** [comment]
Blue theme has a problem similar to black theme: in the z-index, the text of root nodes is sometimes difficult to make out
