### ISSUE TITLE
Inline tags

### ISSUE THREAD

**Issue by srid** [srid/neuron#189]
Allow using tags inline in the zettel content.

Example:

> Gaslighting is enabled by the victim's **@psychology/cognitive-distortion**
without which the victimizer is rendered powerless to influence their victim.

Meta tags should be supported, but now we parse for `@<tag>` in the body as well.

**Comment by geier** [comment]
I'd like to put `#<tag>` forward as an alternative option. Not only have twitter and similar service made the `#<tag>` syntax ubiquitous, but also other note taking apps such as [vscode-markdown-notes](https://github.com/kortina/vscode-markdown-notes#find-all-references-to-tag) (used by foam), [Zettlr](https://www.zettlr.com/features), [Obsidian](https://obsidian.md/features),  [Roam Research](https://roamresearch.com/) and probably many more use it.

**Comment by srid** [comment]
Note to self: internally, tags should be represented as yet another query -- no different from regular link queries. Just as links establish edges on the graph, so too will tags introduce a tag-labelled edge.

For example, the inline text `#daily` can be transformed internally into `<z:tag/daily>`, and then neuron can process tags in the same manner as links. Incidentally this makes implementing inline tags simpler.

It was @jared-w who prompted me into thinking about this, and maybe he has further ideas.
