### ISSUE TITLE
Styling suggestions for web interface

### ISSUE THREAD

**Issue by EyebrowHairs** [srid/neuron#194]
Just gotta say, it looks pretty great already! I just had a few suggestions after playing around with it on https://reddit.zettel.page/.

Main body:
* [ ] slightly more white space between text and edges

Navigation pane:
* [ ] split and place the up/down links to the sides of the note (on desktop) - this can make it more obvious that the note is coming from x notes, and leads to other notes (in my mind at least, it may look too cluttered too)
* [x] if not that, reverse their placement, so that the uplinks are on the left, and downlinks are on the right (like clicking the back or forward buttons on a browser)

Tool bar:
* [x] place the bottom tool bar near the top, or side, so one doesn't have to scroll all the way down a (potentially) long page to navigate
* [x] place the home button/toolbar on the z-index and search pages (to navigate back more easily)

**Comment by srid** [comment]
> split and place the up/down links to the sides of the note (on desktop) 

Yea, this would be better in desktop. While I think of a good UI layout for that, let's go with reversing the placement for now. What about using this opportunity to also rename the section titles to be a little more obvious? Example:

![image](https://user-images.githubusercontent.com/3998/82161882-5c43e780-986e-11ea-99bd-dc8278a55552.png)

**Comment by srid** [comment]
> place the home button/toolbar on the z-index and search pages (to navigate back more easily)

**Comment by srid** [comment]
Specific suggestions have now been applied. The left/right navigation stuff can be done in a separate issue.
