### ISSUE TITLE
Fancy titles

### ISSUE THREAD

**Issue by Nadrieril** [srid/neuron#196]
I'd like to include math in the title of my zettels, but currently the title is copied as-is. Would it be possible to simply pass the title through the same parsing phase as the body?
One would need to be slightly careful because a title could then reference other zettels (which is cool!), and in particular it might reference itself, creating an infinite loop.

**Comment by srid** [comment]
A better approach would be to deprecate the `title` field in the metadata, and re-use the actual Markdown title (`# A title`) when that metadata does not exist (this title can be formatted however you wish, as it will be parsed into pandoc AST). This along with #181 can all be done in one change.

**Comment by Nadrieril** [comment]
Closing in favor of https://github.com/srid/neuron/issues/181

**Comment by srid** [comment]
Re-opening this because the PR for #181 won't cover this part.

**Comment by srid** [comment]
Ah, but that PR does allow H1 formatting in the zettel view. It just won't show up in z-index or link title text to zettels. Anyway, re-open if you see issues after that PR gets merged.
