### ISSUE TITLE
Support for org, RST, etc.

### ISSUE THREAD

**Issue by srid** [srid/neuron#197]
Support other text formats (starting with reStructuredText and orgmode) in neuron, as an optional feature to be enabled manually.

Should be easily doable in neuron >=0.5, which operates on Pandoc AST directly. We mainly need to write the parser that builds the AST with correct autolink nodes for the zettel links.

Markdown will remain the default and the only format (opinionated default); but other formats can be manually enabled in neuron.dhall.

**Comment by srid** [comment]
@michelk expressed interest on this in [the ZuriHac 2020 discord](https://discord.com/channels/701454007775920128/712562695194542091). I'll be happy to help.

**Comment by srid** [comment]
Gonna close this as org support as landed in. RST can be added later. 

Speaking of RST, if anybody has ideas on how to support autolinks please let me know.

**Comment by michelk** [comment]
ok. thanks.
