### ISSUE TITLE
Set up neuron in home-manager possible ?

### ISSUE THREAD

**Issue by 573** [srid/neuron#21]
I am convinced by the Zettelkasten method and wanted to integrate in my setup.

I am pretty much new to nix and as I saw you are using nix for continuous integration wanted to ask for help integrating neuron to my configuration.
This is what I have so far, is home-manager-based but should be not that different to regular nix:

    { config, pkgs, ... }:
	with import <nixpkgs> {};
	with builtins;
	with lib;let
	neuron = stdenv.mkDerivation {
	   name = "neuron";
	   src = fetchFromGitHub {
		 owner = "srid";
		 repo = "neuron";
		 rev = "dd900dd249742aabfb1dba89f498b6afdb7f4531";
		 sha256 = "1zcgd46hjjhsj1g2sifx0hp1cvmd3nssn3nvw48vb5k40sfslkdq";
	   };
	   phases = [ "installPhase" ];
	   buildInputs = [ makeWrapper ];
	   installPhase = ''
		 mkdir -p $out/bin
		 makeWrapper $out/neuron $out/bin/neuron
	   '';
	};
	in
	{
      home.packages = with pkgs; [
        neuron
      ];
    }

I am getting:

> these derivations will be built:
  /nix/store/flz6zqa1hjpjqmhgiba7z7l6jp0d1ygx-neuron.drv
  /nix/store/rdqc7dzmm230w0bxcn7ylds756s6qjrq-home-manager-path.drv
  /nix/store/2pww4m99hmh5bmjk0xlall9n91l7wd5m-activation-script.drv
  /nix/store/idjl4rvj15s0fa2fcyi6hngzrdixmx4i-hm_fontconfigconf.d10hmfonts.conf.drv
  /nix/store/s32pcgy9xp21x9pakhimlcxgr078m6hm-home-manager-files.drv
  /nix/store/yhmxwcq4vihrkclr9v53qfcb7rnf6yi7-home-manager-generation.drv
building '/nix/store/flz6zqa1hjpjqmhgiba7z7l6jp0d1ygx-neuron.drv'...
installing
>
> Builder called die: Cannot wrap '/nix/store/3ca7lxvvd50sgs4l6743fhx1a0fnyqf4-neuron/neuron' because it is not an executable file
Backtrace:
7 assertExecutable /nix/store/06nq4z17fh43wrbn6hl1yq7bzs99lpr1-hook/nix-support/setup-hook
39 makeWrapper /nix/store/06nq4z17fh43wrbn6hl1yq7bzs99lpr1-hook/nix-support/setup-hook
1326 genericBuild /nix/store/qghrkvk86f9llfkcr1bxsypqbw1a4qmw-stdenv-linux/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh

**Comment by 573** [comment]
Seems like callPackage is a candidate, grepping @srid's [nix-config](https://github.com/srid/nix-config/blob/8b4719e8c562311d242ab874b035bb3606418136/nix/home/gotty.nix#L8) helped. See as well [fetchGH](https://github.com/srid/nix-config/blob/06a0cb1a5b3f8e9a1874e991823bac509baf94f4/nix/home.nix#L29).

What I have for now is:

```
# user/me.nix
{ config, pkgs, fetchGH, ... }:
with import <nixpkgs> {};
with builtins;
with lib;
# https://discourse.nixos.org/t/home-manager-real-dry-run/5663/3
let
  neuron = fetchGH "srid/neuron" "dd900dd249742aabfb1dba89f498b6afdb7f4531";
in
{
  home.packages = with pkgs; [
    (callPackage neuron {})
  ];
}
```

```
# home.nix
{ config, pkgs, ... }:
let
  fetchGH = fq: rev: builtins.fetchTarball ("https://github.com/" + fq + "/archive/" + rev + ".tar.gz");
in
{
  imports = [
    ./user/me.nix
  ];
  
  _module.args = {
    inherit fetchGH;
  };
}
```

Still not there though:

> copying path '/nix/store/63mbvpg4rf54g2f5gy2szifxh5yazx53-cabal2nix-2.15.0' from 'https://cache.nixos.org'...
building '/nix/store/f3c65lpfkaaa09d99v9yhf5lmm5h6f4m-cabal2nix-neuron.drv'...
installing
unpacking...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
error: program 'tar' failed with exit code 2
error: unable to download '/nix/store/hphb0p7cm6bjb6m21k7x718milzlc514-root-6.12.06': URL using bad/illegal format or missing URL (3)
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
cabal2nix: user error (Failed to fetch source. Does this source exist? Source {sourceUrl = "/nix/store/hphb0p7cm6bjb6m21k7x718milzlc514-root-6.12.06", sourceRevision = "", sourceHash = Guess "", sourceCabalDir = ""})
killing process 2544: No such process
builder for '/nix/store/f3c65lpfkaaa09d99v9yhf5lmm5h6f4m-cabal2nix-neuron.drv' failed with exit code 1
error: build of '/nix/store/f3c65lpfkaaa09d99v9yhf5lmm5h6f4m-cabal2nix-neuron.drv' failed
(use '--show-trace' to show detailed location information)

**Comment by srid** [comment]
I'll take a look, but for now, can you try the following @573 -

```nix
(callPackage neuron { name = "neuron"; })
```

**Comment by srid** [comment]
@573 Replace `callPackage` with `import`, and it should work.

**Comment by 573** [comment]
Thanks @srid, I have 

```
# user/me.nix
{ config, pkgs, fetchGH, ... }:
let
  neuron = fetchGH "srid/neuron" "dd900dd249742aabfb1dba89f498b6afdb7f4531";
in
{
  home.packages = with pkgs; [
    (import neuron {name = "neuron";})
  ];
}
```

and neuron is built.

**Comment by srid** [comment]
> `import neuron {name = "neuron";}`

You can remove the `name = "neuron";` part; it is not necessary.

**Comment by srid** [comment]
For posterity, home-manage install instructions have been documented here: https://neuron.srid.ca/2012401.html
