### ISSUE TITLE
Switch to KaTeX

### ISSUE THREAD

**Issue by felko** [srid/neuron#212]
Neuron currently uses MathJax. [KaTeX](https://github.com/KaTeX/KaTeX) appears to be faster, and supports pre-rendering of TeX expressions in plain HTML, which might be interesting for offline browsing, as long as the output size is reasonable (unless #96 is implemented, which would bundle KaTeX with neuron anyway).
KaTeX is already [supported in pandoc](https://hackage.haskell.org/package/pandoc-2.9.2.1/docs/Text-Pandoc-Options.html#t:HTMLMathMethod) so the implementation should be easy.

**Comment by RyanGreenup** [comment]
It’s worth mentioning that KaTeX doesn’t have a way to automatically number Equations. 

But numbering equations with mathjax using `align `  is inconsistent with latex which can make pandoc tricky to use to get a PDF so katex might be better anyway.

**Comment by srid** [comment]
Another reason to switch to KaTeX, for smoother math rendering in Cerveau: https://twitter.com/sridca/status/1304468929428021251

**Comment by srid** [comment]
Users can use KaTex in #385. Might just have to document, if we aren't switching from MathJS to KaTeX by default.

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next 

When using Emanote, you get to choose the Math library as it doesn't hardcode anything for you.
