### ISSUE TITLE
Configurable theme colors

### ISSUE THREAD

**Issue by srid** [srid/neuron#22]
Allow some basic customization of the CSS (via `neuron.dhall`) so that not all Zettelkastens appear with *teal* as the primary color.

Might as well normalize heading colors as part of this work.

**Comment by srid** [comment]
https://neuron.srid.ca/2014601.html

**Comment by seekr** [comment]
hi, how can we pick one of those themes from the screenshots? setting color name in neuron.dhall only changes the heading color...

**Comment by srid** [comment]
@seekr Those screenshots were taken in version 0.4, and are thus outdated for the development version in which the UI layout has changed somewhat substantially. Notably, the color-rich "connections panel" got replaced by a backlink tree (while the former is pretty-looking, the latter is conceptually more interesting and useful to get a bird's eye view).  See #195 

When you set the color name in neuron.dhall, it will change the color of heading, as well as the color of zettel links (and the left menu icon colors on hover). 

As an aside: I really should rename this feature to "color schemes" - and reserve "theme" for true theme support (where one can customize the style by doing more than switching colors)

**Comment by seekr** [comment]
@srid thanks for clarifying, is there a way to customize the markup and css generated at compilation?

**Comment by srid** [comment]
@seekr What level of customization are you looking for? CSS is straightforward to be made customizable (and FWIW, neuron uses [semantic ui](https://semantic-ui.com/) as the base, which I recommend retaining for the 'css class library' alluded to in #176); HTML structure is very trick.

**Comment by seekr** [comment]
@srid I was thinking of customizing font to start with, eventually the layout of the page.

It would required me forking the base code and recompile it, right?

**Comment by srid** [comment]
@seekr We can make fonts, as well as CSS, configurable in `neuron.dhall`. I'm curious to see what kind of layout changes you would be doing. It could help inform me as to how to better design a theming system for neuron. 

> It would required me forking the base code and recompile it, right?

Just clone it locally and then run `bin/run rib -wS` while you go about modifying the layout/css in `./neuron/src`; your zettelkasten site should update automatically as you change the code (no need to do a full compile).

**Comment by seekr** [comment]
I'm curious myself ;) I'm very new to zettelkasten and much more to neuron, so I'm trying to experiment for now. I look forward to propose (maybe even contribute?) to neuron as I explore this more! thank you!

**Comment by srid** [comment]
Let's continue this in #253 @seekr
