### ISSUE TITLE
-e options fails if $EDITOR is a shell command

### ISSUE THREAD

**Issue by TheAceShinigami** [srid/neuron#224]
I was following the tutorial, but when I tried to do `neuron new "My first zettel" -e` I got the error

```
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:
  at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.18.5-FiYl23VJG3R4szXGah8kHH:Development.Shake.Forward
* Raised the exception:
TERM=xterm-16color emacsclient -c -q -a='vim': executeFile: does not exist (No such file or directory)
```

I'm on macOS  Catalina 10.15.5, and my text editor is emacs (using the emacs server)

**Comment by srid** [comment]
It looks like your $EDITOR is set to `TERM=xterm-16color emacsclient -c -q -a='vim'`, which neuron tries to execute (as if it is a binary executable) and fails. 

As a workaround meanwhile, you can try replacing `-e` with xargs:

```
neuron new "My first zettel" | xargs $EDITOR
```

**Comment by TheAceShinigami** [comment]
This doesn't quite work because xargs need to be passed a command as it's first non option argument, and `TERM=xterm-16color` is not a command. It's easily fixable in a number of different ways though.

**Comment by srid** [comment]
Fixed in https://github.com/srid/neuron/pull/227
