### ISSUE TITLE
Best way to use Neuron alongside Obsidian?

### ISSUE THREAD

**Issue by SquareBottle** [srid/neuron#229]
Ever come across something that you love at first sight, only to find that some tiny issues keep you from using it? That's where I am. Neuron looks amazing, but it just doesn't seem like it was designed for people who already use Obsidian, Zettlr, etc. to make Zettelkastens.

I have a small Zettelkasten that I've made with Obsidian and Zettlr. I was hoping that using Neuron would be as simple as telling it to use my existing Zettelkasten directory.

1. It seems like the standard way of linking is [[note id]], but Neuron uses <note id> instead. Fortunately, Zettlr has an option to change the link tag, but Obsidian has no such option. But still, why doesn't Neuron just use [[note id]] like the others?

2. Obsidian and Zettlr have nice options for exporting markdown notes to PDF, but the way Neuron demands YAML at the top messes up that export functionality because the title ends up appearing twice unless the markdown header is removed (which makes Neuron pages appear nice, but isn't so nice for PDF exports) or the YAML is removed (which breaks Neuron).

This is as far as I've gotten with playing with Neuron. If there are ways to make it "play nice" with Obsidian and Zettlr, then I'd absolutely love to know what they are!

I realize that we can still use Obsidian and Zettlr to edit the markdown files for Neuron, technically. When I talk about making it "play nice," what I mean is not breaking syntax highlighting, not breaking link functionality, not messing up the display of PDF exports, and otherwise not breaking any of the features that make Obsidian and Zettlr better than MS Notepad. I hope that makes sense!

Again, I think Neuron looks absolutely incredible, and I'd really love to use it. I just wish I could use it and still take advantage of what Obsidian and Zettlr offer. If there's a workflow that would solve these issues, I'd love to know it! And if not, then please consider this a feature request for better compatibility with Obsidian, Zettlr, etc.

Thank you for hearing me out. I hope I've made sense.

**Comment by Nadrieril** [comment]
Once we get https://github.com/srid/neuron/issues/181, the yaml header will be optional. That should fix your 2.
Regarding links, the reason neuron doesn't use `[[id]]` is that it's not valid markdown. We now have a more flexible parser however, so it's at least technically feasible to support this link syntax. I'll let @srid decide on whether we want that.

**Comment by srid** [comment]
I have not used those apps, but I understand that it would be nice be able to edit neuron notes in them.

As Nadrieril commented, Neuron does not have any special Markdown syntax for links, as it piggybacks on commonmark [autolinks](https://spec.commonmark.org/0.16/#autolinks) syntax, which IMO is a simpler and sufficient choice than having to introduce custom syntax.

Assuming `[[note id]]` in Obsidian and Zettlr links to a file named `note id.md` (i.e., they don't do anything fancy like searching by title), supporting this additional linking syntax in neuron should satisfy your point no. (1). I'd be open to that, as long as it is an optional feature (to be enabled by the user in neuron.dhall). 

To implement this you may have to write a commonmark inline parser (similar to [the current one](https://github.com/srid/neuron/blob/81e69150bb1a61d755b3ffdd1683b7d27f0843bf/neuron/src/lib/Neuron/Markdown.hs#L152-L153)), and convert `[[...]]` to Pandoc's `Link` AST node similar to what `<..>` currently generates.

**Comment by srid** [comment]
> Once we get #181, the yaml header will be optional. That should fix your 2.

Done in `master`. @SquareBottle Can you give it a try?

**Comment by SquareBottle** [comment]
> > Once we get #181, the yaml header will be optional. That should fix your 2.
> 
> Done in `master`. @SquareBottle Can you give it a try?

2 appears fixed. Thanks!

> Assuming [[note id]] in Obsidian and Zettlr links to a file named note id.md (i.e., they don't do anything fancy like searching by title), supporting this additional linking syntax in neuron should satisfy your point no. (1). I'd be open to that, as long as it is an optional feature (to be enabled by the user in neuron.dhall).

Yes, I think this would do the trick! I'd be very grateful if you'd implement it. In a nutshell, it's currently the _only_ thing holding me back from using Neuron.

In neuron.dhall, would/will it be as simple as changing a boolean, deleting a comment tag, or something equally simple? Is that the solution you're envisioning?

**Comment by srid** [comment]
> In neuron.dhall, would/will it be as simple as changing a boolean

Yup. 

Now, we *could* just make it the default (so that no configuration is required), but I'll have to think of the implications first (is it going to break existing Markdown files?).

> Yes, I think this would do the trick! I'd be very grateful if you'd implement it

That's good to know. I'm busy with so many things (including [cerveau](http://www.cerveau.app/)) - however I'd be happy to guide anyone through implementing this<sup>[1]</sup>. As a first stage of 'minimum viable feature', in the PR one could just modify [`angleBracketLinkP`](https://github.com/srid/neuron/blob/master/neuron/src/lib/Neuron/Markdown.hs#L186-L191) to use `[[..]]` instead of `<..>`, while you test if that branch works with your Obsidian notes. 

<sup>[1] [Developing](https://github.com/srid/neuron#developing) on neuron should be a smooth process, and [a couple of folks](https://www.srid.ca/2016101.html) (one of them not familiar with Haskell) found it to work surprisingly well.</sup>

**Comment by srid** [comment]
@SquareBottle I've added wiki-style links in #237. Can you give it a try and let me know if it works for you? 

I don't see any harm in making it the default.

**Comment by srid** [comment]
I'm noticing however that Zettlr breaks if you use `cf` links, eg: `[[ef3kdk4?cf]]`. So this is not going to work 100%, unless Zettlr gets a change to ignore queries in the link URI. Since Zettlr is open source, someone can perhaps just open a PR and convince the maintainer of its value.

Although I haven't tried it, the same issue might existing on Obsidian (which is not open source).

**Comment by SquareBottle** [comment]
I've reached an unexpected impasse. In my terminal, I've started getting this response whenever I try to use nix:

    zsh: command not found: nix-env

I just went through the instructions for installing nix on macOS again, and it's still saying that. I have no idea what is causing this. But yeah, as I temporarily can't update Neuron, I temporarily can't give #237 a try. I feel guilty since you've put your time and effort into this, but I don't have any idea what to do about this. Nix worked without any issues until now.

Is it possible that the latest update to macOS (10.5.5) has broken Nix? If so, do I basically just need to sit tight until it's fixed? :(

**Comment by NullSense** [comment]
> I'm noticing however that Zettlr breaks if you use `cf` links, eg: `[[ef3kdk4?cf]]`. So this is not going to work 100%, unless Zettlr gets a change to ignore queries in the link URI. Since Zettlr is open source, someone can perhaps just open a PR and convince the maintainer of its value.
> 
> Although I haven't tried it, the same issue might also exist on Obsidian (which is not open source).

Another way to do this would be making a tertiary script to remove the `?cf` queries. I was thinking of writing a few scripts to do this for a lot of formats to standardize everything. Something like a gateway to a Zettelkasten format would be nice. Unfortunately no Zettelkasten format exists.

**Comment by srid** [comment]
@SquareBottle Looks like your shell is not sourcing the init scripts? What's in `/etc/bashrc`? Or `~/profile`? You should see something like this:

```bash
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
``

**Comment by srid** [comment]
Obsidian is even more troublesome. See https://funprog.srid.ca/neuron/obsidian.html#201374004

I'm going to close it (but feel free to continue the discussion). If you have concrete proposals on interoperability, open them as individual issues.

**Comment by SquareBottle** [comment]
Just to be super clear, there is no reason to believe that anything related to Neuron caused my issues with Nix! My current best guess is that an update caused this.

MacOS switched to zsh a few versions ago, so I'd hope that the Nix team would've taken that into account (assuming they intend for Nix to work on macOS, as opposed to it working on macOS by happy coincidence up to now). So, if you think that it'd be safer to have the Nix installation run using bash, would it be a good idea to update the Neuron installation instructions to that effect?
