### ISSUE TITLE
Add IDE support in Nix, for development

### ISSUE THREAD

**Issue by srid** [srid/neuron#231]
Probably via [ghcide](https://github.com/digital-asset/ghcide).

If someone uses VS code, for example, then `nix-shell --run "code ."` should launch VS code with everything configured. See [Obelisk's workflow](https://haskell.zettel.page/299f86f5.html) for inspiration.

There is already a hie.yaml in the repo (and `nix-shell` includes ghcide), but it is a WIP:

- [x] ghcide works for `./neuron/lib`
- [ ] ghcide works for `./neuron/app`
- [x] Obviate global ghcide install (use upstream nixpkgs ghcide)

**Comment by clojj** [comment]
@srid 
Hi, can you provide an example command (run from this repos root dir), that launches vscode (with ghcide) for neuron lib (the part that  is working) ?

**Comment by srid** [comment]
@clojj IIRC, this is what I did:

* install ghcide by following instructions at <https://github.com/cachix/ghcide-nix>
  * make sure that `ghcide` is in PATH
* launch vscode from neuron's project root as `nix-shell --run "code ."`

**Comment by srid** [comment]
Just a note: `ghcide` is now included in neuron's `nix-shell`. All that's left to figure out here is how to make ghcide process `src/app` (executable) in addition to `src/lib` (library). Right now it only recognizes the latter, but not the former for some reason.

**Comment by srid** [comment]
Ah, figured it out! ghcide now recognizes lib, exe and tests. Just run your text editor from within a `nix-shell`, and it should just work.

**Comment by clojj** [comment]
very nice!

**Comment by clojj** [comment]
Do I have to install cabal though ?
I get "Launching server using command ghcide failed." when I run "nix-shell --run "code ." in the cloned /neuron directory

**Comment by srid** [comment]
@clojj What's the output of `nix-shell --run ghcide`?
