### ISSUE TITLE
Task list checkbox styling is bad

### ISSUE THREAD

**Issue by srid** [srid/neuron#233]
This:

```markdown
- [ ] Foo
- bar
- baz
- [ ] Foo 2
- bar
```

produces list items with differing margins:
![ink](https://user-images.githubusercontent.com/3998/84576826-8614ff00-ad85-11ea-8c09-43beba4c20dd.png)

**Comment by srid** [comment]
Need to fix the checkbox right margin as well:

![image](https://user-images.githubusercontent.com/3998/88466793-04dd7b80-ce9e-11ea-888f-70b292e5b84a.png)

**Comment by srid** [comment]
Okay, so the original issue -- of producing list items with differing margins -- is because Pandoc creates a new list AST where you start or stop using task lists. Apparently Pandoc considers a task list to be a single list only if all items in it contains the checkbox.  So neuron will treat it as a limitation of Pandoc and mark it as "wontfix". 

However the alignment issue mentioned in the comment above is fixed in 0b36bd840525f8daa69aa6aea43c61676e0dd83d via https://github.com/srid/reflex-dom-pandoc/commit/d40dedc286762f6cca82b615b433f211c3494f31

![image](https://user-images.githubusercontent.com/3998/88487560-3c0e6400-cf54-11ea-8730-5f757ddf90c1.png)

**Comment by dariusf** [comment]
There seems to have been a regression here (development version from yesterday).
<img width="109" alt="Screenshot 2020-09-09 at 12 37 14 PM" src="https://user-images.githubusercontent.com/4328341/92555060-69f7ff80-f299-11ea-9562-bb7d364e2694.png">
Adding `vertical-align: middle;` to the [surrounding div](https://github.com/srid/neuron/blob/0195b16ab25c48f10e00630e38ac6ce17f1313f4/neuron/src/lib/Neuron/Web/Zettel/CSS.hs#L45) is one way to fix this.

**Comment by srid** [comment]
@dariusf I can't reproduce. If you can, open a new issue pasting the Zettel markdown that triggers this.

**Comment by dariusf** [comment]
Right, it's a Firefox thing... opened an issue.
