### ISSUE TITLE
Error message in search-preview

### ISSUE THREAD

**Issue by clojj** [srid/neuron#234]
- installed neuron 0.5.5.0 with nix-commands as proposed in the Install section
- default ~/zettelkasten with 2 files

With a search like `neuron search -a`, there is always a message "[bat error]: ... No such file or directory (os error 2) in the (right hand) preview panel

![neuron-search](https://user-images.githubusercontent.com/4367963/84597008-373c9780-ae61-11ea-89e5-c4fa9f8fdccb.png)

(using latest Fedora 32)

**Comment by srid** [comment]
Regression introduced by #230

**Comment by clojj** [comment]
The nix-env upgrade worked like a charm, thx for the quick fix !
