### ISSUE TITLE
Use neuron as a dependency in stack project

### ISSUE THREAD

**Issue by clojj** [srid/neuron#242]
I know that the 'stack or not-stack' issue is not a trivial thing right now (as I understand because of which and rib packages ?)

Still I'd love to use neuron as a package in a new stack project (preferably of course with current Stackage LTS 16.1), and then develop with the very nice VSCode + ghcide setup (which depends very much on a stack-based installation of ghcide)

So maybe, a stack-based neuron package can be provided ?
Or maybe, some hint on how to setup ghcide with Nix could help also... bu I am a Nix newcomer, so I don't know...

**Comment by srid** [comment]
I don't use stack myself. Even if someone contributes a stack.yaml -- which I'd *normally* be happy to accept -- there is no guarantee that it will continue to remain up to date. So what I recommend folks is to give Nix a try.

As for IDE support, I got it working half way in `master`. If you run `nix-shell --run "code ."`, ghcide will recognize ./neuron/neuron/src/lib but not ./neuron/neuron/src/app. Fixing that is what's left in #231 - if you would like to take a look?

**Comment by Nadrieril** [comment]
@srid Are you still planning on putting neuron on hackage? That should be enough for it to eventually be usable by a stack project I think

**Comment by srid** [comment]
Putting it on Hackage won't be enough. You'd have to do that (stack support) for every dependency (notably, reflex, reflex-dom, commonmark, etc.) of neuron that is pinned. That's not easy work, compared to just using Nix.

I'm going to close this issue, as the only actional work is on #231.
