### ISSUE TITLE
Any options other than Nix?

### ISSUE THREAD

**Issue by mtnygard** [srid/neuron#243]
Don't get me wrong, the Nix install worked great on my main development machine. But I just got a Pinebook Pro to use as a distraction-free writing machine. It's good enough for text editing but not video or video games. :-)

The problem is that it only comes with a 64GB root volume. 

The install step of

```
nix-env -iA cachix -f https://cachix.org/api/v1/install
```

fills up the root volume while installing GHC, then aborts and reverts.

I'd like to use neuron on that little box. Is there an option to get the binary without unpacking more than 40 GB of software? (I fully recognize that I am a Nix-noob and may be doing something wrong.) I can't just copy the binary from my other machine because one is x86-64 while the Pinebook is Aarch64.

**Comment by srid** [comment]
This question comes up [every once in a while](https://github.com/srid/neuron/issues?q=label%3Asuch-is-nix+). Nix is the only way to install the software, until #183 is done. 

For aarch64 in particular, see #66.

**Comment by srid** [comment]
Is docker a viable option on Pinebook Pro? If so, try https://neuron.zettel.page/c6176636.html
