### ISSUE TITLE
Code elements in title are ignored

### ISSUE THREAD

**Issue by srid** [srid/neuron#244]
For a zettel like:

```markdown
# The `Has` pattern
```

neuron deduces the title "The pattern" for use in the graph data structure.

**Comment by Nadrieril** [comment]
The title
```markdown
# Foo | bar
```
is also not recognized as a title, I don't know if that's related

**Comment by srid** [comment]
The bug is in [`plainify`](https://github.com/srid/neuron/blob/master/neuron/src/lib/Neuron/Markdown.hs#L128-L132), which should be handling more than the `Str` node.

**Comment by srid** [comment]
> `# Foo | bar`

This looks to be unrelated. It breaks the Markdown parser (parsing of H1) for some reason.

**Comment by felko** [comment]
I noticed a similar issue when typing TeX inside titles. I thought MathJax just didn't render it in the z-index (though it is displayed correctly in the zettel view) but given that the problem also appears with code elements it seems to be caused by something else.

**Comment by srid** [comment]
@felko Try this fix. 

@Nadrieril Escaping the `|` with a `\` works (i.e.: `# Foo \| bar`). Looks like a commonmark-hs issue (maybe some extension is getting the way). In any case, this is unrelated to the current bug.

**Comment by felko** [comment]
Thanks, Tex code inside titles is now recognized. However it is not rendered in the z-index.

**Comment by srid** [comment]
How do I reproduce that?

**Comment by felko** [comment]
If I type TeX inside a title, like
```
# Elias $\gamma$ code
```
Then it will render as `Elias \gamma code` in the z-index, though it correctly renders the code in the zettel body.
