### ISSUE TITLE
Minimum neuron version

### ISSUE THREAD

**Issue by srid** [srid/neuron#26]
Requires #40 

Allow user zettelkastens to specify the minimum neuron version they require to function correctly. Specify this version in the configuration file `neuron.dhall`. Example:

```dhall
{ neuronVersionMinimum = "0.2"
, ...
}
```

**Open questions:** 
- Should there be an upper bound as well? (`neuronVersion = ">= 0.2 && < 0.3"`)

**Comment by luc-tielen** [comment]
For now, only add a minimum constraint and try to stay as forward compatible as possible? 
This will allow users to keep upgrading neuron or they risk staying stuck on older versions?
