### ISSUE TITLE
Switch from reflex-platform to direct nixpkgs

### ISSUE THREAD

**Issue by srid** [srid/neuron#262]
Go back to how it was pre-reflex-platform days, but use reflex-dom-core, reflex, and friends from nixpkgs (instead of reflex-platform). 

Replace project.nix & ./dep/* with a new default.nix.

The following should continue to work:

- [x] `bin/run` & `bin/test` scripts should continue to reload when any of the source files change
- [x] `nix-build` when run a second time should not build anything new
- [x] neuron [install command](https://neuron.zettel.page/2011501.html) should not regress to installing more than needed ([see here](https://github.com/srid/neuron/blob/4b29d4081daa0d460a540e5e4846cd52ce9ddb83/default.nix#L6-L30))
  - On a fresh VM, installing neuron produces a /nix that weighs ~1.9G.
- [x] ci.nix should handle both `nix-build` and `nix-shell` cases for cache
- [x] Adjust "Developing on reflex-dom-pandoc" section of README accordingly

/cc @maralorn

**Comment by srid** [comment]
This is done #280, so I'll close.

@maralorn AFAIU, only rib and commonmark needs to be released to hackage before neuron can be updated on nixpkgs, right?

**Comment by maralorn** [comment]
@srid, and reflex-dom-pandoc, if it isn't already.
