### ISSUE TITLE
Inline comments

### ISSUE THREAD

**Issue by srid** [srid/neuron#269]
According to [this](https://talk.commonmark.org/t/method-for-comments-especially-multiline/208/6), Pandoc supports YAML blocks anywhere *inside* (not just at beginning) the text, which could serve as comments for Markdown.

```markdown
---
# comment
# comment
---
```

**Comment by Nadrieril** [comment]
That seems like a significant deviation from markdown spec. Doesn't markdown support html comments usually? As in `<!-- comment -->`

**Comment by srid** [comment]
Indeed that's better as it can also work inline instead of being forced as a block.
