### ISSUE TITLE
`neuron new` incorrectly handles non-ASCII characters in title

### ISSUE THREAD

**Issue by TheMatten** [srid/neuron#273]
Running
```bash
$ neuron new "Najneobhospodárovateľnejší"
```
This is the output I get as a file
```markdown
---
date: "2020-07-06"
---

# Najneobhospod��rovate��nej����
```

At quick glance, problem doesn't seem to be related to parsing/writing - `strArgument` used to get title calls `fromString` to `Text`, which seems to work just fine from my testing, same for `Data.Text.IO.writeFile`, for which `writeFileText` is just it's lifted version.

**Comment by srid** [comment]
Wild guess: need a `decodeUtf8` in the result of `strArgument`?

**Comment by srid** [comment]
I can't reproduce this.

<img width="642" alt="Screen Shot 2020-08-15 at 10 31 06 PM" src="https://user-images.githubusercontent.com/3998/90325235-0f43e000-df47-11ea-8b1b-032daf67a440.png">

**Comment by srid** [comment]
Please reopen if you do!
