### ISSUE TITLE
Neuron search, Org format not recognized

### ISSUE THREAD

**Issue by Whil-** [srid/neuron#275]
Hi again =)

Trying out the Neuron CLI. And it seems `neuron search` won't recognize files in Org format.

Zettelkasten folder content:
```
gustav@Kontor:~/zettelkasten$ ls -l
total 0
-rw-rw-rw- 1 gustav gustav  96 Jul  6 21:17 06ae322c.md
-rw-rw-rw- 1 gustav gustav  92 Jul  6 21:55 8a15ec9a.org
-rw-rw-rw- 1 gustav gustav  70 Jul  6 21:17 a29e0fde.md
-rw-rw-rw- 1 gustav gustav 145 Jul  6 21:45 neuron.dhall
```

And `neuron search` will only list the two markdown files. Same result with `--full-text` added to the command.

**Comment by srid** [comment]
This script https://github.com/srid/neuron/blob/master/neuron/src-bash/neuron-search should be made to take the `*.md` as an argument.

**Comment by clojj** [comment]
trying to test this.. got this problem:
running `bin/run -d $(pwd)/guide search -a` gives me this error
![grafik](https://user-images.githubusercontent.com/4367963/90392335-f34b5600-e08e-11ea-9c84-7cd3383061cd.png)

**Comment by clojj** [comment]
in a clean branch, I could not start bin/run ... search 
maybe because of the bash script, this command can only be tested with a neuron executable?

**Comment by srid** [comment]
I don't see that compile error; in any case, you don't really want to use bin/run to run interactive commands like `search`, because ghcid doesn't seem to handle that well. Run `nix-build` and test `./result/bin/neuron`.

**Comment by srid** [comment]
Closing, and moving what's left to #422
