### ISSUE TITLE
Error message should show line of error

### ISSUE THREAD

**Issue by maralorn** [srid/neuron#278]
Look at an error message for a missing link:
```
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:
  at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.19.1-F2oa7ITr3lwIYbMrmURf15:Development.Shake.Forward
* Raised the exception:
user error (
  Zettel file "index.md" is malformed:
    Zettel test1 does not exist
)
```
I suggest
1.  to show line and line number where the missing link is declared
2.  hide the shake exception, which is not useful to the user.

**Comment by srid** [comment]
@maralorn Are you on 0.4?

This is already addressed (except the line number part) in development version, which displays:

```
[..]
E index.html
  - links to non-existant zettel: test1
```

**Comment by maralorn** [comment]
Oh, I am sorry. I hadn‘t tried develop.

otoh: I don‘t see a line number in what you printed, so that only affects the 2. point of my issue. The first seems more important to me.

It's obviously not urgent, but it would be very nice to have.

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, in the context of Emanote, [post here](https://github.com/srid/emanote/issues/new/choose).

Note: Emanote is actually pretty lenient when it comes missing links and errors like that. It doesn't crash, and instead offers a way to render them in an user customizable fashion.
