### ISSUE TITLE
Open-sourcing

### ISSUE THREAD

**Issue by humaidq** [srid/neuron#28]
I have been integrating neuron in my daily workflow, it is the best note-taking system I have used so far.

It would be great if this software is released under an open-source license.

**Comment by srid** [comment]
Hey, thanks for your comment! :-)

Neuron _is_ open-source; and I've just added a LICENSE file to the repo to make that explicit. b6644b8658035be4874839de852c307ee2df95be

I will also be cutting the first official public release (`0.2`) pretty soon.
