### ISSUE TITLE
neuron new should use correct day respecting system timezone

### ISSUE THREAD

**Issue by maralorn** [srid/neuron#285]
I was right now very confused, when neuron made me a note with date of yesterday. This happened because I don't live in UTC. 

The culprit seems to be this line:

https://github.com/srid/neuron/blob/0b387635fb7d989cb06421f248a4e29e23500642/neuron/src/app/Neuron/CLI.hs#L37

Looks like it's really easy to fix.

**Comment by srid** [comment]
Agreed, it should just use local time. 

(UTC was chosen for date IDs, but we don't use that anymore by default).

Somewhat related: #257

**Comment by maralorn** [comment]
Nice! Thank you!
