### ISSUE TITLE
date field might have unclear semantics on webpages

### ISSUE THREAD

**Issue by maralorn** [srid/neuron#286]
When writing a blogpost or a note belonging to some day or event the semantics of the date field are kinda clear.
The date signifies to which day the zettel belongs/was created.

But when browsing the guide online I had the situation where I thought: Hm, is this information up-to-date? From when is this post and when was it modified? (e.g. [the Installing page in the guide](https://neuron.zettel.page/2011405.html))

Of course I can guess that the date was manually entered on creation and not changed since. But for visitors of the page not knowing how the date field there is populated that is not apparent at all.

**Comment by srid** [comment]
Aside from removing the date metadata from the ./guide notes - what would you like to happen here?

**Comment by maralorn** [comment]
I don‘t know. I was first stating an observation. If this is not actionable enough for you be free to close it.

But I can brainstorm a bit other possibilities: add a (potentially optional) "Created at" label to the date. Perhaps make a "datelabel:" field, that you could either set per zettel in neuron.dhall. Also we could consider offering a "modified:" label which would maybe work very well together with #203 .

Do you like any of those ideas?

**Comment by maralorn** [comment]
Of course deleting this on guide pages would be a very good solution and enough to close this issue from my perspective.

**Comment by srid** [comment]
Just realized you can't remove date from a zettel that has a date ID. 

Anyway, I'll add a "Created at" prefix to the HTML. Long-run, we will rename "date" to "created" to avoid confusion.
