### ISSUE TITLE
How can I disable AutoScroll?

### ISSUE THREAD

**Issue by b0o** [srid/neuron#294]
I'm not a huge fan of the AutoScroll behavior since when editing a note I often refresh the web page and want to keep the same scroll position. 

I found [this commit](https://github.com/srid/neuron/commit/f414fc9a7841fd924c248c6a00be22ea02d75a1f) ([latest version](https://github.com/srid/neuron/blob/a70a532f06d54fdc13510a711a110c3fe41f9e02/neuron/src/lib/Neuron/Web/Widget/AutoScroll.hs#L11)) which claims to allow disabling AutoScroll but I'm not sure how to accomplish this. I've tried adding the following to `neuron.dhall` to no avail:

```dhall
{
...
, autoScroll =
    None Text
}
```

**Comment by srid** [comment]
That commit allows disabling auto scroll programmatically only (it was added for use from cerveau). There is no way to use it from neuron.dhall.

However, it looks like [there is a way](https://stackoverflow.com/a/36444134/55246) to detect if a page is being _reloaded_ in JavaScript, and then toggle it off if it is a reload. It seems like this would satisfy your use case. Exposing auto scroll to neuron.dhall would just be unnecessary detail.

**Comment by srid** [comment]
I suppose another approach is to auto scroll only if the [current scroll position](https://stackoverflow.com/a/2481370/55246) is at the top. Not sure how that would play with reloaded page though ...

**Comment by srid** [comment]
@b0o Give this a try. I've tested it to work on Chrome atleast.

**Comment by b0o** [comment]
@srid That works perfectly on Firefox, thank you!
