### ISSUE TITLE
Advice on linking by ID / not having note title in the source file

### ISSUE THREAD

**Issue by vcavallo** [srid/neuron#306]
I'm loving neuron so far, thanks so much @srid !

I know that emacs supports `neuron-mode`whereby the note title "virtually" appears in the the editor, while the source file only contains the `<abc123>` link markup. There's no similar mechanism for Vim (or other text editors). 

I would like for my future-proof, atomic notes to contain the relevant context along with the mechanical link - that is:
1. `this relates to <abc123> Some Other Note` (contains the note title) rather than...
2. `this relates to <abc123>` (no note title)

`1` above is preferable for the future-proofness and readability of the notes, but when doing that the web view _doubles up the note title_ (it would render as `this relates to [Some Other Note] Some Other Note`, where the first one is a hyperlink and the second one is plain text). This has me using `2` to avoid the web weirdness, but leaves the text of my zettles less useful without Neuron's web view help.

What is the best way to work around this? Thanks!

**Comment by srid** [comment]
I'm pretty sure neuron.vim supports virtual title next to ID, as you can see from the screenshot in the README https://github.com/ihsanturk/neuron.vim - thought it is [limited](https://github.com/ihsanturk/neuron.vim/issues/26) compared to what you would get in emacs.

> `1` above is preferable for the future-proofness and readability of the notes

I don't understand this. There is no need to duplicate the note title in all the places you link to it. 

The problem with duplication is that - when you change your note title down the line, you would have to remember to change all the backlinks to use the new title, and this is an annoying and error prone process.

> This has me using `2` to avoid the web weirdness, but leaves the text of my zettles less useful without Neuron's web view help.

That is true -- and I don't think there is any perfect solution to this problem. You can get away with using even notepad.exe (hence future-proof) as long as you rely on the auto-generated web interface. Alternatively you can use a text-editor with explicit neuron support; and https://github.com/srid/neuron/issues/213 is supposed to make that better.

**Comment by vcavallo** [comment]
Thanks for getting back to me!

I'm in the process of installing neovim now. As far as I can tell, it's only neovim that supports the virtual title (I have neuron.vim installed (with standard vim) and while everything else is working, the virtual title doesn't).

I do see what you mean about changing the note titles / duplication. Here's my thought and a suggestion:

- Say I have a note with ID <123> and title "How to Shave a Dog" all about dog haircuts
- I want to write, in another note, this in a paragraph: `Elsewhere I've written about <123?cf> haircuts.` 
- I'll end up with `Elsewhere I've written about [How to Shave a Dog] haircuts` in the web view.

Perhaps what would be helpful is an additional flag in the link anchor like `<123?cf&notitle>` which would tell the web renderer to avoid adding the title to this link (it could just use the ID verbatim, maybe)? 
I'm on-board with the strategy of avoiding renaming and updating notes in the future, but I'm not thrilled about having the rendered prose of my notes necessarily including titles that I don't want breaking up the flow of sentence where a link is present.

I think this is only an issue when links are included inline in a sentence. If they're just spit out at the bottom of a page there's no issue.

**Comment by srid** [comment]
I see. It looks like it might just make sense after all to allow the user to *override* a link title. Something like:

```markdown
This is how you [shave a dog](z:/abc123)
```

Or:

```markdown
This is how you [[shave a dog | abc123]]
```

That would address your problem, as well as provide users with a general ability to use a custom title for their link.

**Comment by vcavallo** [comment]
https://github.com/srid/neuron/issues/312#issuecomment-668432892 Sort of relates here, too.

**Comment by Coda-Coda** [comment]
@vcavallo yes it definitely does relate.

For what it's worth, my opinion and how I currently have my Zettelkasten is to name notes similar to their title (indeed to an extent I just use the filename as a title). So I can link inline with `[MacOS tips and tricks](macos_tips_and_tricks.md)`.

The key advantage of this is that it is both readable in a plain text editor as well as any standard markdown preview and the links are clickable in any markdown editor (PC and mobile). Even the list of files themselves is readable.

The disadvantage you mention @srid
> The problem with duplication is that - when you change your note title down the line, you would have to remember to change all the backlinks to use the new title, and this is an annoying and error prone process.

Is not that much of an issue (at least for me), because:
 - Zettel titles like mine don't change often.
 - If they did change, it would be as simple as renaming the file and replacing all occurences of `[Title](filename.md)` with `[New title](new_filename.md)` which can easily be done in Notepad++, VSCode, or other tools.

    (Alternatively the content between `[...]` could be left unchanged, just replacing `](filename.md)`, particularly if treating the filename as the title and the content between `[...]` as a context dependent comment.)
 - I imagine this process could be implemented automatically when renaming files in Neuron.

**Comment by srid** [comment]
We now support regular Markdown links. Also see #373 for the `[[shave a dog | abc123]]` syntax proposal.
