### ISSUE TITLE
Make Docker image that is compatible with Whalebrew

### ISSUE THREAD

**Issue by colindean** [srid/neuron#307]
[Whalebrew](https://github.com/whalebrew/whalebrew) is a [Homebrew](https://brew.sh)-like system that uses Docker under the hood. When you install a program through Whalebrew, you're really just pulling the container and adding a script executable that invokes the Whalebrew binary with some configuration which is used to launch a Docker container.

There are only two requirements when [creating a Whalebrew package](https://github.com/whalebrew/whalebrew#creating-packages): 

* The command must be set as the entrypoint.
* The command must only work with files in the image's working directory.

There are some optional labels to set that tell Whalebrew more about how to install and open/limit interactions with the outside world.

**Comment by colindean** [comment]
Taking some notes here in case someone else gets to this before I do.

https://github.com/srid/neuron/blob/master/docker.nix is what needs to change

https://nixos.org/nixpkgs/manual/#ssec-pkgs-dockerTools-buildImage documentation

Might need to add some things to the `config` block there: https://github.com/moby/moby/blob/master/image/spec/v1.2.md#container-runconfig-field-descriptions

It's not clear to me how to set labels in the `dockerTools.buildImage` block.

**Comment by srid** [comment]
`config.Label = "..."`? Looks like you can just do `config.<WhateverDockerConfig>`.

**Comment by srid** [comment]
This is being done in #528
