### ISSUE TITLE
Support non-flat filesystem hierarchy

### ISSUE THREAD

**Issue by NightMachinary** [srid/neuron#309]
I already have my notes in markdown, but I organize them in a hierarchy of directories. It seems to me that supporting this shouldn't be very hard? As I have encoded a lot of information in the hierarchy, I don't wish to move them to a flat structure. The hierarchical organization is also supported by generic software very well; I use WorkingCopy on iOS to edit my notes, and it's quite up to the task, even though it's just a general git client.

**Comment by NightMachinary** [comment]
After playing with neuron for a bit, I see its special sauce as its tree visualizer and the backlinking. I think this should be implementable on a normal directory, as it only needs to scan the directory and build a graph of the links. I think giving up the directory structure is a very costly move for people who don't like being limited to a specialized tool. I can now do things like this, with a few lines of shell:
![image](https://user-images.githubusercontent.com/36224762/88774142-520c6680-d198-11ea-878e-a0bd0a4c94bc.png)

Implementing such a thing with neuron would require a lot of special software, because the hierarchy is opaque. Of course, the flat structure has the advantage that you don't need to put things under a prespecified category; But my experience is that a lot of stuff lend themselves best to such top-down categorization. Since the two approaches can co-exist (everything goes by default into the uncategorized root, but the user can move them freely into subdirectories.), why not offer them both?

**Comment by srid** [comment]
Are you asking about supporting note files recursively (discarding the hierarchy)
 ? Or, are you asking about mapping the filesystem hierarchy as-is to neuron's [folgezettel heterarchy](https://neuron.zettel.page/2017401.html)?

**Comment by jared-w** [comment]
Neuron already supports hierarchical tags. Perhaps the file system tree could be mapped 1:1 with tags and otherwise zettels would link to each other normally?

**Comment by NightMachinary** [comment]
[**@jared-w**](https://github.com/jared-w) commented on [Jul 31, 2020, 5:22 PM GMT+4:30](https://github.com/srid/neuron/issues/309#issuecomment-667104080 "2020-07-31T12:52:06Z - Replied by Github Reply Comments"):
> Neuron already supports hierarchical tags. Perhaps the file system tree could be mapped 1:1 with tags and otherwise zettels would link to each other normally?

This is a good idea. I think to facilitate the linking, neuron might need to change its linking scheme a bit. As far as I understand, currently, neuron uses IDs as filenames to make changing the title of notes costless. A better approach might be to allow both an ID and a title. The title won't be included in the links, only the ID. The title's only use is to allow interoperability with other tools. (For example, I use fzf to jump between my notes, and I need meaningful names for each note for this to work.) This title can be further used as the last tag in the hierarchy of tags. To illustrate:

`/dev/zsh/testing/ZUnit.SOMEID.md` would be a note with ID `SOMEID` and in the hierarchy `dev -> zsh -> testing -> ZUnit`.

**Comment by srid** [comment]
> Neuron already supports hierarchical tags. Perhaps the file system tree could be mapped 1:1 with tags and otherwise zettels would link to each other normally?

This is what I was thinking. One could write an import script that converts the hierarchical notes directory, recursively, to a flat list of files each tagged accordingly, in addition to creating "portal zettels", for intermediate directories, that [queries](https://neuron.zettel.page/2011506.html) it's contents by tag. 

So, for example, given `/dev/zsh/testing/ZUnit.md`, this would create 4 zettels:

* `ZUnit.md` tagged `dev/zsh/testing`
* `dev-zsh-testing.md` tagged `dev/zsh` (and queries `dev/zsh/testing/*`)
* `dev-zsh.md` tagged `dev` (and queries `dev/zsh/*`)
* `dev.md` (queries `dev/*`)

**Comment by srid** [comment]
@NightMachinary There is no good reason to change the ID scheme. You can use title (slug) as the ID if you want. Neuron doesn't care as long as they are unique, and are alphanumeric (with hyphen and underscore).

**Comment by jaysnoddy** [comment]
I would like it if neuron could eventually support at least one level of subdirectories.  I use four "bins" or subfolders that really seldom need cross-referencing among the bins. It was annoying to me if kept in the same folder. My bins/subdirectories are, as follows:  Academic work, personal technology notes (e.g. program documentation, cheat sheets, boilerplate, etc.), Cooking/Recipes, and Current News.  I have made some aliases to take away some of the complexity. However, serving a localhost for each seems messy. Others might, of course, have different bins. Others may only use neuron for one type of notes.  

(Analog-analogy or pseudo-joke: Given the presence of slipnote paper, I would not be surprised if the Luhmann household used slipnotes for recipes, but I would be surprised if 'how to make Aunt Gertrude's apple strudel' ended up in the same zettlelkasten as his academic work.)

**Comment by srid** [comment]
@jaysnoddy I think the cross-links idea mentioned at https://github.com/srid/neuron/pull/339#issuecomment-674328371 may very well cover your use case.

**Comment by babygau** [comment]
i think this would be cool if you could implement something like [dendron](https://www.dendron.so/notes/f3a41725-c5e5-4851-a6ed-5f541054d409). so we don't really sub folders. just name the file based on our conversation

**Comment by fiatjaf** [comment]
I think this issue should be considered if neuron is to become a "complete" note-taking system that tries to support all kinds of workflows. If it wants to remain close to the Zettelkasten idea, then this is a distraction. I say this without deep knowledge of Zettelkasten, but I think doing less things is better.

**Comment by felixyz** [comment]
I would be perfectly happy if Neuron simply recursively picked up all markdown files from all subdirs and then proceeded to handle them just as if they were all in a single directory. Of course, then the problem is possible name clashes, so the id of `foo/bar/qux.md` would have to be `foo/bar/qux`.

A bit of sugar on top of that would be to the ability resolve links relative to the current file's location, like how module references work in most programming languages. So `foo/bar/baz.md` could refer to `foo/bar/qux.md` with `[[qux]]` *or* [[foo/bar/qux]], `foo/guz.md` could refer to it with `[[bar/qux]]` etc. This would make it easier if one decided to change the file hierarchy (although it would still not be free), and very intuitive I'd say, at least for programmers.

Finally, it would be a _nice to have_ if Neuron would optionally tag all files with their path, so that `qux` would get the tag `foo/bar`.

For all of us who already keep our notes in a file tree, I think the above would let us get productive with Neuron right away without having to change anything about our existing notes.

**Comment by c-dante** [comment]
@felixyz I agree with everything but the relative path sugar -- it implies that you can do directory style pathing `[[../baz]]`, adds ambiguity if you have something like `/help.md` and `/foo/help.md` (so, the same id-collision problem).

Personally, I think keeping the markdown id to be the filename and simply discard the path by default would be the safest parallel -- `/` is an awkward symbol to add to the id, refactoring and restructuring would be hard if one decides to move or rename their folders, and it will falsely draw a parallel to the filesystem.

I do think that an added config or flag to push paths into tags would be a good solution to capture the semantic intention behind the directory structure.

**Comment by srid** [comment]
For those interested in this feature, I've pushed **experimental** support in the `master` branch. I'm not advertising it widely (yet) because this feature is likely to change, or even go away (if it proves to be problematic in some way).  I'm publishing it for testing and feedback before we finalize anything.

To use this feature, install latest neuron and add `recurseDir = True` to your neuron.dhall.

**Comment by felixyz** [comment]
Just tried this out and works great. As expected, I got warnings about id clashes. Are you leaning towards not doing anything to help resolve these? (By eg taking the file path into account?) I'd say that's reasonable, would introduce complexity to support what seems to be a rather small group of users who already have or want hierarchical file organization.

Auto-tagging might still be a helpful thing, and doesn't really affect anything else?

**Comment by srid** [comment]
A notion of "namespaced linking" could be considered. So [[qux]] can *also* be explicitly linked to as [[bar/qux]] (from a note inside foo/ directory) or [[foo/bar/qux]]. This should take cross links proposal in #355 into consideration. We should combine them, and come up with a simple proposal - that satisfies the two use cases.

Auto-tagging is a separate feature, possibly to be implemented as a plugin. cf. https://github.com/b0o/neuron-extras#demo
