### ISSUE TITLE
Document org-mode support

### ISSUE THREAD

**Issue by srid** [srid/neuron#313]
- [ ] How to enable org-mode support in neuron.dhall
- [ ] How to link between notes
- [ ] Mention limitations if any (are there? @felko ?)

**brief explanation**

Org-mode support is disabled by default. To enable it, add `formats = ["markdown", "org"]` in the neuron.dhall file. Then neuron will pickup .org files as well as .md files. To link to notes, use `[[z:/efja2hs3]]` syntax (explain why this particular syntax).

**Comment by felko** [comment]
> Mention limitations if any

Yes there are, so far I found only those two:
- Headline links (`[[*Headline title]]`): not even generated as links
- Fuzzy linking (`[[file:path.org::Some sentence somewhere in the file]]`):: generated as links but doesn't work as expected

I'm not an org-mode power user so I suspect many other features that I didn't notice won't work. I think the support it is good enough for basic usage but it is just impossible to reimplement org-mode entirely within neuron. I'll try to investigate alternatives such as letting emacs handle itself the HTML generation through a custom exporter tailored for neuron.
