### ISSUE TITLE
How do backlinks work? 

### ISSUE THREAD

**Issue by Nimor111** [srid/neuron#314]
Hello,

I noticed in the neuron docs site there is a backlinks section at the bottom of some pages: [example](https://neuron.zettel.page/2011502.html). In my local neuron however, I don't notice such a thing, and I don't see it documented anywhere ( that might be me being oblivious to something ). Since backlinks ( e.g. notes that link to the current note I'm reading ) are quite important to my workflow and i'd like to see them there, could you share some information about how they work in neuron? 

Thanks in advance,
Nimor

**Comment by srid** [comment]
@Nimor111 In neuron, there are two kinds of backlinks:

* Folgezettel backlink, also called "uplink": these appear **on top** of the zettel card, as an inverted tree.
* cf backlinks, created using `?cf` query flag: these appear in the "More backlinks" section below

See https://neuron.zettel.page/5e41fd32.html

Does that clarify it? If not let me know.

It looks like the documentation is not very clear on this, and we should improve it (cf. #199).

**Comment by srid** [comment]
(To suppose, to avoid this confusion, we should display both kinds of backlinks in the section below ...)

**Comment by Nimor111** [comment]
Yes, I had missed the different types of links. I understand it now.
What you wrote down here would be a good addition to the docs, yeah. 

Thank you!
