### ISSUE TITLE
proposal: introduce environment variable configuration like NEURON_ROOT_DIR

### ISSUE THREAD

**Issue by aca** [srid/neuron#319]
If you are not using default directory ~/zettelkasten.
We always have to use --zettelkasten-dir (-d) flags.
It will be helpful if we can configure it with environment variable like NEURON_ROOT_DIR.

With tooling like "direnv". It will also be possible to move around multiple zettelkasten directory and use neuron cli without -d options.

**Comment by srid** [comment]
See also #161 -- looks like we need one or the other, not both.

**Comment by aca** [comment]
@srid Oh, thanks.

@maralorn comments look reasonable. 
> Use the directory given with -d, if given.
Check if the current directory contains a .neuron directory. If yes use this directory.
Go one directory up and go to 2. If / is reached continue.
~Check if there is a default directory defined in a neuron.dhall config file somewhere. Use that if given.~
Use ~/zettelkasten.

If this is possible, we might not need this. No configration is always much better.

**Comment by srid** [comment]
Since there is no convincing argument to favor this over #161, I'll close this.
