### ISSUE TITLE
Dangling zettles not displayed in the forest

### ISSUE THREAD

**Issue by gillchristian** [srid/neuron#32]
Looks like after #30 was merged dangling zettles are not displayed in the forest (z-index).

But they should be displayed as top level, if I understood the docs write ([Top-level zettels](https://neuron.srid.ca/2012301.html)).

**Adding one zettle to the guide**:

It doesn't show in the forest.

<img width="623" alt="Screenshot 2020-03-28 at 17 08 19" src="https://user-images.githubusercontent.com/8309423/77827683-60c60c80-7117-11ea-97f6-5f674ce3e9e0.png">
<img width="721" alt="Screenshot 2020-03-28 at 17 08 27" src="https://user-images.githubusercontent.com/8309423/77827676-5b68c200-7117-11ea-9908-699b3f409bd5.png">

**Adding another one and linking**:

Now that there's one link it shows.

<img width="620" alt="Screenshot 2020-03-28 at 17 09 12" src="https://user-images.githubusercontent.com/8309423/77827680-5efc4900-7117-11ea-9a77-c8a7d814048f.png">
<img width="719" alt="Screenshot 2020-03-28 at 17 09 24" src="https://user-images.githubusercontent.com/8309423/77827682-602d7600-7117-11ea-92cd-415b6e4ff31b.png">

**Comment by srid** [comment]
Good catch! I thought I had tested it, damn. I guess I definitely must add unit tests at this point.

**Comment by gillchristian** [comment]
I was trying to open a PR but you'll probably solve it faster :)

**Comment by srid** [comment]
I think this bug existed even before #30.

**Comment by gillchristian** [comment]
They would show as "Dangling Zettles"

<img width="273" alt="Screenshot 2020-03-28 at 19 11 19" src="https://user-images.githubusercontent.com/8309423/77830307-e9e53f80-7127-11ea-930b-fda3e0416c14.png">

**Comment by srid** [comment]
Right. Before, dangling zettels were determined _without_ the help of the graph (there was some code that processed zettels _outside_ of graph, and it got removed in #30). Now, they are handled implicitly with the graph, which exposed this bug.

**Comment by gillchristian** [comment]
Ohh makes sense 👌
