### ISSUE TITLE
VSCode with ghcide fails in WSL2

### ISSUE THREAD

**Issue by clojj** [srid/neuron#322]
this happens, when doing "nix-shell --run "code ."

![grafik](https://user-images.githubusercontent.com/4367963/89310764-71fac900-d675-11ea-9091-09308c5beeb3.png)

the neuron installation went well and neuron is working after installing it with nix

**Comment by srid** [comment]
What's the output of `nix-shell --run ghcide`?

**Comment by clojj** [comment]
> 
> 
> What's the output of `nix-shell --run ghcide`?

at the end it is this:
![grafik](https://user-images.githubusercontent.com/4367963/89316781-d1a8a280-d67c-11ea-86bf-bf666e1056a5.png)

**Comment by srid** [comment]
That's what I see as well. (The error needs to be fixed, but not relevant to current issue). For some reason I can't even get nvim to work on WSL 2.

**Comment by srid** [comment]
This might be related: https://github.com/microsoft/vscode-remote-release/issues/554

**Comment by srid** [comment]
>  For some reason I can't even get nvim to work on WSL 2.

False alarm. After [creating coc-settings.json](https://github.com/digital-asset/ghcide#cocnvim), nvim works on WSL2

**Comment by srid** [comment]
@clojj Okay, try the extension I linked to above - and select the `shell.nix` environment, which will prompt you to restart Code. Then it will work. 

It would be great to document all of this in CONTRIBUTING.md.

**Comment by srid** [comment]
I just added the extension config to git. Pull the latest `master` and try this:

- Install https://marketplace.visualstudio.com/items?itemName=arrterian.nix-env-selector in vscode
- Run `nix-shell --run "code ."`.

**Comment by clojj** [comment]
> 
> 
> I just added the extension config to git. Pull the latest `master` and try this:
> 
>     * Install https://marketplace.visualstudio.com/items?itemName=arrterian.nix-env-selector in vscode
> 
>     * Run `nix-shell --run "code ."`.

success!
(although I had to fiddle with that extensions settings and restart s few times, in the end it worked with no further modifications anywhere)

**Comment by clojj** [comment]
btw, since I noticed that ghcide is updated very frequently: is the nix-config always pulling the latest ghcide version ? or is it currently fixed at (what?) version ?

**Comment by srid** [comment]
It uses whatever is in nixpkgs, and as such depends on what revision we have it pinned (I update is semi-regularly): https://github.com/srid/neuron/blob/8f3c7c6752b17f18b71eb4e76dfef74e854b2f59/project.nix#L2-L5

The ghcide in nixpkgs should match the default compiler; so it shouldn't break.

**Comment by srid** [comment]
Note: in latest master I switched from ghcide to LSP (now requires [this extension](https://marketplace.visualstudio.com/items?itemName=haskell.haskell)), as well enabled auto format on save.
