### ISSUE TITLE
Help needed hardcoding ghc version

### ISSUE THREAD

**Issue by 573** [srid/neuron#324]
I am trying to set ghc to a specific version for a workflow I created to add aarch64 binary bundle.

As you can see [here](https://github.com/573/neuron/issues/1#issuecomment-669100425) my efforts were placed in the wrong direction so far.

**Comment by srid** [comment]
The `compiler` was never used (as far as I can tell), so it wouldn't be surprising if it is broken. 

Changing it should string should fix it, I think. Basically do this: https://github.com/juspay/jrec/blob/152d2bbfdf7b0d04b22d63b59d6ce0b0d962ea18/default.nix#L12-L19

**Comment by srid** [comment]
[Deleting irrelevant comment]

Looking at your diff, https://gist.github.com/573/fb04128458ea41851837ea6feec16cf7 that doesn't seem right. Did you try passing `pkgs = pkgs; compiler = pkgs.haskell.compiler.ghc883` when invoking neuron's (unmodified) default.nix/project.nix? I would think that should have worked.

**Comment by 573** [comment]
Tried passing it
```
nix-instantiate --strict --json --eval -E 'import ./project.nix { pkgs = pkgs; compiler = pkgs.haskell.compiler.ghc883; }'
```
>error: undefined variable 'pkgs' at (string):1:31

**Comment by srid** [comment]
Create a separate foo.nix, and then `import` the project.nix from inside. In your foo.nix, you can define `pkgs = import <nixpkgs> {}` (or whatever pinned nixpkgs).

**Comment by 573** [comment]
Just
```
# foo.nix
# nix-instantiate --strict --json --eval -E 'import ./foo.nix {}'
import ./project.nix 
```
still gives me ([see](https://github.com/573/neuron/issues/1#issuecomment-669100425))

>error: cannot import '/nix/store/j3lwbasppdsngpqkq7f05lnw88mxs7x5-cabal2nix-neuron', since path '/nix/store/rrpq1qsj2a1nrclvdh91y572d4312lww-cabal2nix-neuron.drv' is not valid, at /nix/store/54qqg9k8z49ay0b9ycgf9fdhqaxf97h6-source/pkgs/development/haskell-modules/make-package-set.nix:83:54
(use '--show-trace' to show detailed location information)
{"neuron":}

**Comment by Infinisil** [comment]
Should be `(import <nixpkgs> {}).haskell.packages.ghc883` instead
