### ISSUE TITLE
running bin/test leaves the terminal text-color green

### ISSUE THREAD

**Issue by clojj** [srid/neuron#333]
![neuron-test](https://user-images.githubusercontent.com/4367963/90024434-24094500-dcb5-11ea-8ff4-ede7940c0a95.png)

**Comment by srid** [comment]
This seems more a https://github.com/hspec/hspec/issues issue than a neuron one. 

You can reset your terminal by running [`reset`](https://askubuntu.com/questions/25077/how-to-really-clear-the-terminal).
