### ISSUE TITLE
URLs in text are not generated as links.

### ISSUE THREAD

**Issue by leira** [srid/neuron#334]
Neuron doesn't generate links for text `https://github.com/srid/neuron`, it just treats it as normal text. It only generate links for explicit links like `[neuron](https://github.com/srid/neuron)`. I suppose it is not wrong in a strict sense. But I suppose it is good user experience to generate implicit links for URLs.

I'm using version 0.6.0.0.

**Comment by srid** [comment]
Make them an [autolink](https://spec.commonmark.org/0.16/#autolinks) and they will work: `<https://github.com/srid/neuron>`

Neuron uses commonmark, which does not seem to support the semantics of magically detecting links.

From https://commonmark.srid.ca/ 
![image](https://user-images.githubusercontent.com/3998/90079152-1c599880-dcd5-11ea-99a8-f4cb7cd0b139.png)

**Comment by leira** [comment]
This solves my problem. Thanks!
