### ISSUE TITLE
Unhelpful error message after deleting ~/zettelkasten

### ISSUE THREAD

**Issue by codygman** [srid/neuron#338]
The first run of neuron worked fine:

```shell
mkdir ~/zettelkasten
neuron new "my first zettel" -e 
# save file
neuron open
```

Then I wanted to start fresh and deleted ~/zettlekasten. Now I'm stuck with this erro seemingly perpetually:

```shell
[cody@nixos:~]$ neuron open
neuron: user error (Zettelkasten directory /home/cody/zettelkasten does not exist.)
```

I guess there is a cache directory somewhere that I need to delete so neuron thinks its a fresh install?

**Comment by srid** [comment]
@codygman This is expected, but I wonder if the error message can be improved to prevent confusion.

Neuron will refuse to proceed if the zettelkasten directory does not exit (the user is expected to create it). So if you wanted to start afresh, normally you would do:

```
rm -rf ~/zettelkasten
mkdir ~/zettelkasten
neuron rib  # Do one off generation on empty zettelkasten
neuron open
```

**Comment by codygman** [comment]
Maybe a `neuron reset` with error message and confirmation prompt would be best. An error saying maybe you want to run `neuron rib` would have let me keep trying out neuron.

As is though, I haven't touched it since that error.

The annoyance with neuron cli ironically led me to want to try out the web version and sponsor you 😅

**Comment by srid** [comment]
Well, the error message can certainly be improved. I'll keep this issue open as a reminder of that.

> The annoyance with neuron cli ironically led me to want to try out the web version and sponsor you 

Hehe, nice - and thanks! Note that I whitelisted your account yesterday. There is no formal email invite (especially as GitHub doesn't reveal the email address of sponsors); you can start using it right now, by signing in using GitHub (see the login button at the bottom of http://www.cerveau.app). [More instructions here](https://guide.cerveau.app/ac48f1d0.html).
