### ISSUE TITLE
Specifying the notes dir with an absolute path causes InvalidRelDir error

### ISSUE THREAD

**Issue by DataWraith** [srid/neuron#35]
Hi.

I started playing with Neuron a couple of days ago. When I updated to master today, I noticed that I could no longer specify the notes directory as an absolute path:

```bash
$ neuron /home/$USER/zettelkasten new "foo"
neuron: InvalidRelDir "/home/$USER/zettelkasten/"
```

Relative paths work fine:

```bash
$ cd $HOME
$ neuron zettelkasten new "foo"
zettelkasten/2012606.md
```

I assume this is unintended behavior, because it seems strange to only allow relative paths.

I ran git bisect, and commit 7b6c112edca7e84d52d65ef9a63efa43ee6d75b2 appears to be the one causing the problem. I don't know Haskell very well, but the changes to `inputDir` and `directoryAside` look related.

Thanks!

**Comment by srid** [comment]
Support for absolute paths (temporarily) got removed in https://github.com/srid/rib/pull/134

--

I'd like to add back support for absolute paths, but only after carefully thinking about the location of the Shake database directory - which at the moment is always in the current working directory. So if you are currently under `~/somedir` and do `neuron ./foo/bar ...`, then the Shake database directory will be stored under `~/somedir/.shake`. But if you are elsewhere, and run neuron with `~/somedir/foo/bar` - that database won't be used.

This behavior is normal for static sites written in rib (as current working directory is always the git repo), but for a tool that extends it (like neuron) I think we should have to be explicit in saying where the Shake database has to be stored. I'm inclined to store it the notes directory itself; assuming that won't be problematic, support for absolute paths can be restored (internally neuron would convert that relative path before passing it to rib).
