### ISSUE TITLE
Blockquote paragraphs appear in reverse order in footnotes

### ISSUE THREAD

**Issue by srid** [srid/neuron#350]
A footnote like this:

```markdown
Hello[^test]

[^test]:
    > first
    >
    > second
    >
    > third
```

will render as:

![image](https://user-images.githubusercontent.com/3998/90547657-de87c480-e159-11ea-8612-647433a52228.png)

**Comment by srid** [comment]
First step is to figure out whether this is an issue in the parser ([commonmark-hs](https://github.com/jgm/commonmark-hs) - with extensions enabled) or the renderer ([reflex-dom-pandoc](https://github.com/srid/reflex-dom-pandoc)).

**Comment by hagl** [comment]
Is an issue in the footnote extension of [commonmark-hs](https://github.com/jgm/commonmark-hs). 
I've created an [issue](https://github.com/jgm/commonmark-hs/issues/63) and [PR](https://github.com/jgm/commonmark-hs/pull/64) there.
