### ISSUE TITLE
Allow hiding query result header

### ISSUE THREAD

**Issue by Remich** [srid/neuron#359]
Hi,
when creating automatic links using queries, Neuron always displays the tags as some kind of headline.

It would be nice to have a option in the link (something like `?cf`) to disable the displaying of the tags.

In my Zettels I often have a headline followed by some automatic links. It does not look very nice, if the tags act as a "second headline".

**Comment by srid** [comment]
Tags are actually not displayed in the zettel query results ([see here](https://www.srid.ca/356bec10.html) for example). What version of neuron are you using?

**Comment by Remich** [comment]
Sorry, I might have explained it wrong.

In your example there is an additional divider being inserted:
`<div class="ui horizontal divider" title="Neuron ZettelQuery">All zettels</div>`

If one would specify some tags in the automatic link, this divider would display those tags, defined in the automatic link.
It would be cool to have a option to disable said divider.

Your example also fits my description of the use case: There are somewhat two headlines: "Recently Created Zettels" and below "All Zettels".

**Comment by srid** [comment]
A better approach would be to allow the user to specify a custom .css file that gets used in addition to builtin css. And add a `class` to this divider div, which this custom.css can hide by setting `display: none`.

**Comment by Remich** [comment]
This approach would hide the divider div always.
But it should still be possible to display the divider div sometimes.

**Comment by srid** [comment]
I'm hesitant to add too specific a behaviour to the more general link query feature. Here's an alternative approach, one that is more general:

```
[[z:zettels?tag=foo&class=bare]]
```

i.e.; allow link queries to accept an argument for a custom CSS class (here we specify `class=bare`). Then wrap the resulting view in either a `span` or a `div`, with that class. Then you can specify a custom CSS using #362 to style that div/span however you want. To hide the header for the above query for example you would the write CSS like:

```css
div.query-result.bare div.divider {
  display: none !important;
}
```

**Comment by srid** [comment]
Actually, wait. We can use the attributes extension from #176 to inject this class (no need to add `class=bare`):

For example, the following will add the classes "ui" "red" and "message" to a wrapping div:

```
:::{.ui .red .message}
[[z:zettels?tag=timeline/**&timeline]]
:::
```

![image](https://user-images.githubusercontent.com/3998/91373272-f90a0f80-e7e3-11ea-9345-1916b8e650be.png)
 
Then, all we need to implement is #362.

**Comment by Remich** [comment]
Why would that be to specific and why are you hesistant to add that kind of option? You already implemented something like `?cf` for regular links. It don't see much difference to have some kind of customization for auto-linking.

While your approach would work, it seems kind of overkill:

1. It introduces a lot of unnecessary markup in the zettels, which impairs readability in the markdown file itself.
2. With this approach we are adding markup, to remove/hide other markup. (This does not sound right).
3. We have to rely on another technology (CSS) which should not be concerned with what gets rendered to the DOM.
4. Users without CSS knowledge might run into problems.

**Comment by srid** [comment]
Don't [complect](https://www.infoq.com/presentations/Simple-Made-Easy/) UI configuration and data querying.

The link query syntax has one purpose -- to query zettels from the zettelkasten for establishing connections to. Piling it with UI features is just unnecessary complexity; I consider the existing `?timeline` and `?showid` to be a bad idea already, and I wouldn't want to make that situation worse. 

Your point (3) and (4) can be addressed by providing the CSS classes as builtin (eg: `.neuron-hideheader`, `.neuron-showdate`), then users only need to use the commonmark attributes syntax to hide the various elements of the results view -- header, timeline dates or IDs.

---

Anyway, I'm not convinced with any of the proposed ideas so far. Commonmark attributes extension is Markdown-only, and it can't be used in org-mode. 

I'm inclined to remove the header completely, unless someone can think of strong reasons not to.

**Comment by srid** [comment]
@Remich You can achieve this by putting the following in your [head.html](https://neuron.zettel.page/custom-head):

```html
<style>
    /* Hide the query divider */
    div.pandoc section.tag-query-results .divider {
        display: none !important;
    }
</style> 
```

I'll close this issue, but with a reminder to document this "recipe" in https://github.com/srid/neuron/issues/565

**Comment by srid** [comment]
If you wanted to hide the divider from just a selected list queries, then I suggest filing a new issue. One way to address that is to have the queries take a `class=foo` argument, and then pass that as a CSS class in generated html (so you can hide it as shown above).
