### ISSUE TITLE
Add special type of automatic link to show a cluster of the heterarchy.

### ISSUE THREAD

**Issue by Remich** [srid/neuron#360]
Hi,

it would be cool to have a special kind of automatic link (like `<z:zettels>`) but for displaying a (sub-)cluster of the heterarchy.

**Comment by srid** [comment]
@Remich A coupe of questions:

1. What's the actual use case for this feature?
2. How would you define the URI for this kind of query? i.e., What are its parameters/values?

**Comment by Remich** [comment]
1. To display some kind of sitemap / navigation. Basically the same kind of link-structure which is displayed in the z-index.html .
2. `<z:index?ZETTELID>`

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).

Also see https://github.com/srid/emanote/discussions/106
