### ISSUE TITLE
Enable different MathJax URL

### ISSUE THREAD

**Issue by vizziv** [srid/neuron#361]
Right now the URL to the MathJax Javascript file is hard-coded, but there are several possible options one might want to use (e.g. to use SVG rendering instead of CHTML).

One way to support this would be to switch the `mathJaxSupport` Dhall configuration option from a bool to an optional URL.

**Comment by vizziv** [comment]
Note: this is related to #212, but I think this is much simpler to implement.

More generally, one might imagine giving the user more control over what lives in the `<head/>` of their pages, e.g. to load custom scripts. One can use such a script to solve the repeated `\newcommand` problem brought up in #348.

**Comment by srid** [comment]
> More generally, one might imagine giving the user more control over what lives in the <head/> of their pages, e.g. to load custom scripts. 

I like this. Opened #362.

**Comment by vizziv** [comment]
This seems subsumed by #362, so closing.
