### ISSUE TITLE
Why is there no support for sub-directories?

### ISSUE THREAD

**Issue by peti** [srid/neuron#365]
I would like organize my content in a meaningful directory structure, but it seems like `neuron` completely ignores anything beyond the `--zettelkasten-dir`. Is there any particular reason why I can't have a zettel called, say, `chess/london-opening.md`? It seems to me like Neuron could process that note pretty much the same way it would process a zettel called `chess-london-opening.md`, no? Am I missing something?

**Comment by srid** [comment]
@peti There was some discussion on this in #309 

What would be the zettel ID of `chess/london-opening.md`? Would you link to it as `[[chess/london-opening]]` or `[[london-opening]]`? What about multiple levels of directories, as in `[[foo/bar/baz/qux/quz]]`?

**Comment by peti** [comment]
> What would be the zettel ID of `chess/london-opening.md`? Would you link to it as `[[chess/london-opening]]` or `[[london-opening]]`? 

The former. The link must include the full path so that one can have both `chess/london-open` and `tennis/london-open` without any ambiguity.

> What about multiple levels of directories, as in `[[foo/bar/baz/qux/quz]]`?

I see no reason to stop at any particular depth. I'd say recursively find and process any files that live in `--zettelkasten-dir` or at any depth below it. I guess one could ignore directories that start with a `.` so that we don't accidentally pick up stuff from `.git` et al.

**Comment by srid** [comment]
Let's move the discussion to #309 (duplicate).

**Comment by fiatjaf** [comment]
If I were to ever want subdirectory support then I think I would want the id of the zettels to be their basename (filename without path), as my use-case for subdirectories would be not stuffing the main directory with too many files, but perhaps separate them by year or something, not actual categories.

Just saying this to show there is no consensus on how to better support subdirectories.
