### ISSUE TITLE
homebrew package?

### ISSUE THREAD

**Issue by babygau** [srid/neuron#367]
i'm wondering if you could make this available for `homebrew`? not everyone is familiar with `nix` imho

**Comment by srid** [comment]
As I understand, you will need #183 (help wanted on this!) before a homebrew package can be made.

Also, there is #307 for a Docker-based workflow if you do not want to go the Nix route.

Generally speaking, I'd highly recommend going with Nix.

**Comment by babygau** [comment]
tks u for amazing effort to this great project, i will consider about migrate to `nix`.
