### ISSUE TITLE
support dot `.` in file name

### ISSUE THREAD

**Issue by babygau** [srid/neuron#369]
i'd like to have `.` support in file name, for example `learn.me.some`.

**Comment by srid** [comment]
To implement this, modify this function:

https://github.com/srid/neuron/blob/7140f96ae3f3e787bbdf6e5018ea3816ebb6613d/neuron/src/lib/Neuron/Zettelkasten/ID.hs#L121-L123

And add expand the test coverage.

**Comment by srid** [comment]
Dot is possibly going to be used to signify hierarchy in #379
