### ISSUE TITLE
Allow custom link text in wiki links

### ISSUE THREAD

**Issue by srid** [srid/neuron#373]
**Proposed syntax**:

```
[[ foo | a foo note ]]
```

**Open question**:

Does this play well with notable plain-text Zettelkasten apps (Obsidian, Zettlr)? If not, what would be a more suitable syntax?

**Comment by MaienM** [comment]
It works as expected in Obsidian and Foam. Zettlr isn't showing my wikilinks at all in the output, not sure what's going on there.

**Comment by srid** [comment]
@MarienM Thanks for checking -- so it looks like we should just go with the proposed syntax `[[ foo | a foo note ]]`.

As for Zettlr, well I guess Zettlr users should just refrain from using custom link text then. /cc @EyebrowHairs

**Comment by EyebrowHairs** [comment]
We could use [this kind of custom text](right.md)?

**Comment by srid** [comment]
@EyebrowHairs That already works in neuron, however those links will be always 'cf'. 

With wiki-links, you can make them folgezettel, i.e., `[[[right | this kind of custom text]]]`.

**Comment by MaienM** [comment]
Just to clarify: Zettlr wasn't showing any of my wikilinks, regardless of whether I was trying to name them. I looked into it briefly and found out it does not support this syntax, and they intend to keep it that way. I've updated my previous post to include this.

**Comment by linusboyle** [comment]
May I know the progress on this? It seems like the last missing feature I need.
