### ISSUE TITLE
Add a flag that turns zettel errors into runtime errors

### ISSUE THREAD

**Issue by peti** [srid/neuron#374]
At the moment `neuron` diagnoses that a linked-to zettel does not exist and complains about it, but `neuron rib` still returns exit code 0, which signifies no error. I would like neuron to return error code 1 in such a case, though. Maybe a flag like `--pedantic` could be used to control this behavior?

**Comment by srid** [comment]
This was done explicitly so someone can leave `neuron rib -w` running as a long-running process in the server. However, we should make `neuron rib` (i.e., without `-w`) exit with a non-zero return code if there are errors (while behaving the same, in regards to static site generation, as the watch mode). Does this do what you want? I don't see a reason to add a flag.

**Comment by srid** [comment]
And this might have to be done in rib, possibly around here: 

https://github.com/srid/rib/blob/615ce3e80205b42e855ce774a7f419aa7fa0ec69/rib-core/src/Rib/App.hs#L79-L83

**Comment by srid** [comment]
Note to self: possibly to be done as part of #321

**Comment by srid** [comment]
neuron doesn't use rib anymore; so this can be done quite straightforwardly. Just exit after `reportAllErrors` here unless running in watch mode. Or better return the error status in the return Event and do it in `generateSite` (requires a bit of reflex knowledge).

https://github.com/srid/neuron/blob/49d1a46456f041ee20a7e2f1aeae7f0a216395e8/neuron/src/app/Neuron/Reactor.hs#L90-L91

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, in the context of Emanote, [post here](https://github.com/srid/emanote/issues/new/choose).
