### ISSUE TITLE
Tag zettels

### ISSUE THREAD

**Issue by srid** [srid/neuron#379]
**Proposal**

Treat tags as zettels. 

Every tag `#foo` (see inline tags in #189) is, conceptually speaking, also a zettel, with ID `foo`, and as such gets the associated `foo.html` generated page (with an implicit `[[z:zettels?tag=foo]]` query in it, for listing tagged zettels). 

Now here comes the interesting part: if the user already has a zettel file `foo.md`, then that zettel is used as the "tag zettel" - and all instances of inline tags will link to it. This is useful if you want to take custom notes on the tag *itself*. 

**Brainstorming / open questions**

- At this point, one might ask - why not *unify* the tagging and linking syntax? For example, why not link to some zettel "ef324s3" as `#ef324s3` (i.e. no different to "tagging")? Because, now, both tagging and linking creates an edge in the zettel graph. Consequently, the tag query `z:zettels?tag=foo` becomes equivalent to the (yet to implement) backlinks query `z:zettels?to=foo`.

- How do we deal with hierarchical tags? What does `foo/bar/baz` map to? What about its intermediaries (eg: `foo/bar`)?

**Comment by srid** [comment]
This might also take some inspiration from the hierarchical index of @b0o's https://github.com/b0o/neuron-extras

**Comment by srid** [comment]
> How do we deal with hierarchical tags? What does `foo/bar/baz` map to? What about its intermediaries (eg: `foo/bar`)?

Switch to `foo.bar.baz` format, and create 3 associated zettels with IDs: `foo`, `foo.bar` and `foo.bar.baz`. So when using hierarchical tags you get "free" index zettels for each level of the tag, which index zettels can latter be converted if desired to a regular zettel note whilst still being treated as tag(node) zettels.

**Comment by srid** [comment]
`vscode-memo`'s author operates on a similar idea: https://github.com/svsool/vscode-memo/issues/60#issuecomment-673544023

**Comment by srid** [comment]
If tags are treated as just another link, we can still identify which links are tags by using an edge label on the graph. Currently we have two edge labels -- cf & folgezettel -- now, we simply add a third label to denote tags. 

```
#foo 
is equivalent to,
<z:link/foo?label=tag>
```

just as:

```
[[foo]]
is equivalent to
<z:link/foo?label=cf>
```

or:

```
[[[foo]]]
to:
<z:link/foo?label=branch>
```

**Comment by srid** [comment]
And hierarchical tags can delineate into *multiple* links, one for each level of hierarchy:

```
#foo.bar.baz 
is equivalent to having 3 links:
<z:link/foo?label=tag>
<z:link/foo?label=tag>

**Comment by ericapisani** [comment]
I really like the ideas that you've outlined so far! I have a question regarding your comment on dealing with hierarchical tags:

> How do we deal with hierarchical tags? What does foo/bar/baz map to? What about its intermediaries (eg: foo/bar)?

This could be due to me being newer to the whole concept of zettelkasten, but could we not view tags (and their zettels) as having a folgezettel relationship with the zettels that use those tags? 

It seems like you're kind of suggesting that in [this comment](https://github.com/srid/neuron/issues/379#issuecomment-689155895) around free index zettels for each level of tag in a hierarchy, but I guess I'm slightly confused around what makes a tagging relationship distinct from that of a folgezettel relationship.

**Comment by srid** [comment]
@ericapisani 

> could we not view tags (and their zettels) as having a folgezettel relationship with the zettels that use those tags?

Right, that was my thinking - for the default *generated* tag zettels.

I suppose the following folgezettel relationships can be implicitly created, in the generated zettels:

* `foo.md` contains `[[[foo.bar]]]` & `[[[z:zettels?tag=foo]]]`
* `foo.bar.md` contains `[[[foo.bar.baz]]]` & `[[[z:zettels?tag=foo.bar]]]`
* `foo.bar.baz.md` contains `[[[z:zettels?tag=foo.bar.baz]]]`

Basically a tag(node) zettel "branches off" to both child-tag(node) zettels and zettels that are tagged with it. I think this is exactly what https://github.com/b0o/neuron-extras does.

---

However, if the user creates `foo.bar.md` (for example) themselves, then neuron won't autogenerate it, and any folgezettel relationships from it is up to the user. That said, any zettels tagged `#foo.bar` will appear in the Backlinks of the `foo.bar.md` zettel. 

This is why I'm increasingly moving towards relegating folgezettel relationships as cherry-on-top, and focus more on non-folgezettel (i.e, normal) relationships. In that sense, tagging == linking. And "zettels tagged foo" == "backlinks of foo".  So, in theory, tagging can be eliminated entirely, and re-added simply as a syntatic alias to the existing zettel/linking functionality. In my personal zettelkasten, I'm increasingly moving towards simple linking (i.e., `[[foo]]`) rather explicit tagging (`#foo`), and based on that I try to come up with ideas for improving backlinks support in neuron. 

Not sure if that answers your question. In any case, I have not made any 100% concrete proposal here; just throwing some general ideas. This issue is still open for alternative suggestions, or new ideas. One thing is sure: tags should be unified with linking, as that is what they are in essence. How we implement that is what needs to be speced out.

**Comment by ericapisani** [comment]
What you've written makes a lot of sense, thanks for the explanation and the additional context!

**Comment by srid** [comment]
While making progress on #497, I realized that this proposal can be vastly simplified to mean just one thing: tagging, (`#foo`), is the _same_ as linking (`[[[foo]]]`), except the folgezettel relationship is *reversed*. Plus, it will obviate having to write the query `[[[z:zettels?tag=foo]]]` (thanks to the upcoming plugin mechanism).

(We will discard hierarchical tags with a slash, as those are not relevant - based on the design decisions made on #497, which the tag zettel plugin would likely be based on)

**Comment by srid** [comment]
> We ignore hierarchical tags with a slash, as those are not relevant 

Actually, we may be able to use them. By having the [dirtree](https://neuron.zettel.page/dirtree.html) plugin automatically tag child zettels with their parent folder; then, the the tag-zettel plugin can do the rest of the job, of forming links and rendering them. 

For example, the dirtree plugin can automatically tag `Tech/Software/Browsers/Vivaldi.md` with `#Tech/Software/Browsers`, and finish its job. Then, the tag-zettel plugin can automatically link to, and render, the contents -- along with other folgezettel connections made with `[[[` -- of the Browsers foler in the `Browsers` zettel.

**Comment by RoyiAvital** [comment]
In my University time I used to have the following files tree:

```
- Courses
  - <CourseName1>
    - Notes/
    - Exercises/
    - Exams/
    - Books/
  - <CourseName2>
     - Notes/
    - Exercises/
    - Exams/
    - Books/
  - <CourseName3>
    - Notes/
    - Exercises/
    - Exams/
    - Books/
```

What I'd expect tagging system which takes into account the folder tree hierarchy is to tag each file by each folder name in its tree.

So if I search for `Books` / click on the `Books` tag I will see all files inside all `Books` folders.
Even if I didn't explicitly added the tag `Books` to each (As I want the folder tree hierarchy to serve me, not me serving it).

I'd be happy if you give it a thought.

Thank You.

**Comment by srid** [comment]
Splitting this "mega" proposal into individual units:

- #497 (Automatic folgezettel heterarchy creation - based on directory tree, however, rather than tags)
- #514 (Labelled directional plugins; acts as a replacement for tag cum query-links workflow)
- #521 (Leaving tags untouched, but moving it off core) 

Closing this one, in favour of the above.
