### ISSUE TITLE
Group orphan zettels, instead of displaying them as individual "clusters"

### ISSUE THREAD

**Issue by fiatjaf** [srid/neuron#380]
I have many notes that don't belong to any cluster because I didn't find a way to link them yet. That causes my z-index page to show each in its own cluster. It is ugly.

Or maybe this is just a sympton of how my zettelkasten is new yet, otherwise everything would be properly linked?

**Comment by srid** [comment]
Connect your zettels using `[[[...]]]` to tidy up your z-index. Or, if you don't want to curate but just want a compact list, create a new zettel, say `index.md`, containing `[[[z:zettels]]]`.

**Comment by srid** [comment]
Oh, I just realized you said "many notes". You might be interested in #204

**Comment by srid** [comment]
I suppose we can group those "orphan" zettels (not linked to other zettels) and list them compactly in one visual group.

**Comment by fiatjaf** [comment]
Just a suggestion. Not critical. I think I'm probably going to link them to an index or sub-index somehow.
