### ISSUE TITLE
[Feature Request] Inserting custom HTML into static web site generation

### ISSUE THREAD

**Issue by leonardt** [srid/neuron#383]
Hi there, thanks for your great work on this project!

I'm using this as a part of my personal website, and I have a top-bar linking to it as a "notes" section.  I'd love to be able to include the same top bar in the generated static web site, that way I have a consistent "theme" (mainly I want to have a button back to the homepage that links to a portion of the website outside of the statically generated content from neuron.

I'd be happy to look into implementing this myself, but was hoping I could get a pointer to where in the code I could insert the logic.  Also I'm open to suggestions on how to integrate this from a user perspective in an extensible way (ideally beyond my use case).  For example, do we simply provide some configuration option for some static HTML snippets to insert? This would cover my use case.  A more general solution might be to provide some hooks for the user to provide arbitrary code to insert content during the page generation process.  This seems more useful in a broader context, but not sure how hard this is to achieve in the existing code.

**Comment by srid** [comment]
@leonardt See #253 (for general theming).

What you are asking is simliar to #362.

We want to figure out a simpler solution, without adding too many configuration points.

See here for all theming related requests: https://github.com/srid/neuron/labels/case-for-themes

**Comment by srid** [comment]
> I'd be happy to look into implementing this myself, but was hoping I could get a pointer to where in the code I could insert the logic.

https://github.com/srid/neuron/blob/d3e69a91b5542ec47eeee733b6e6d4e015c55546/neuron/src/app/Neuron/Web/View.hs#L99-L128

Doing it in a general way is gonna be a challenge, as we use Haskell for UI.

**Comment by vizziv** [comment]
I started looking into #362 myself, but I wasn't able to figure out how to insert arbitrary HTML using Reflex.

Would a possible first-draft solution to this and #362 be to allow adding up to one `script` tag to the `head`? (Possibly but not necessarily replacing the MathJax script.) A single `script` could use JavaScript to add more elements (including loading more JS and CSS files) while leaving the Reflex code relatively clean.

More generally than adding one `script`, one could imagine allowing a list of `script`s and a list of CSS `link`s. But there are so many attributes for each such tag (`async`, `deferred`, `integrity`, etc.) that the dhall configuration would get unwieldy.

The single-`script` solution wouldn't necessarily be as fast as the multiple-`script`/`link` solution, but it's simpler to configure and would have perfectly acceptable performance for a personal zettelkasten.

**Comment by srid** [comment]
@vizziv You can add raw html using [`elPandocRaw`](https://github.com/srid/reflex-dom-pandoc/blob/259c7a881dd4ba69f82ac2fdec83ddf8f5ee0fc5/src/Reflex/Dom/Pandoc/PandocRaw.hs#L52) (it can be exposed if it isn't already). This is what the zettel renderer uses (indirectly via reflex-dom-pandoc's `elPandoc`) to render the [raw html blocks](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/raw_attribute.md) in notes.

**Comment by srid** [comment]
You can now do this in JS using #385? If not reopen.

**Comment by leonardt** [comment]
Worked for me, thanks!!
