### ISSUE TITLE
[Question] Can you reference zettles in a subfolder?

### ISSUE THREAD

**Issue by ssanj** [srid/neuron#384]
Hi, 

I've got the following structure for a Zettelkasten:

```
├── index.md
├── september-2020
│   ├── c1e72a9b.md
│   └── ff1539ba.md
```

While I can reference Zettles in `september-2020` as:

```
[[[september-2020/c1e72a9b]]]
```

And while it does render as valid

![Screen Shot 2020-09-10 at 2 58 38 pm](https://user-images.githubusercontent.com/366640/92683530-7736ec00-f376-11ea-8825-73bc9d1add1a.png)

When I click-through `rib` can't find the files:

![Screen Shot 2020-09-10 at 2 58 46 pm](https://user-images.githubusercontent.com/366640/92683593-a0577c80-f376-11ea-9a77-a487956a7b4e.png)

So my question is:

> Is it possible to have Zettles in sub folders?

The reason I want to do this sub folder structure, is that I don't want to pollute the root directory with too many files.

**Comment by srid** [comment]
Neuron doesn't support this, but there was a request for it at #309 (closing this one as duplicate).

> I don't want to pollute the root directory with too many files

Has this ever been a problem in practice though?

**Comment by ssanj** [comment]
> Has this ever been a problem in practice though?

Yes, I have this issue with my current Hakyll blog. Over two hundred entries in the same folder 😱
