### ISSUE TITLE
Sequential seemingly random identifiers

### ISSUE THREAD

**Issue by fiatjaf** [srid/neuron#387]
I like the idea of having random identifiers for each zettel. However, I think it would be nice if they were sequential, mimic'ing in the zettelkasten directory the organization a physical zettelkasten would have.

Using a library like https://usecuid.org/ to generate the ids would accomplish this.

**Comment by fiatjaf** [comment]
I now realized cuid would either have to generate big identifiers, which is not the best thing, or if using the `Slug` they wouldn't be sequential anyway, so I'm trying to come up with a better encoding.

**Comment by fiatjaf** [comment]
Maybe this is not ideal because then all filenames would start with the same characters most of the time so it would be hard to autocomplete them from the terminal.

Or maybe this isn't really problem, as today I don't type filenames directly already.

**Comment by srid** [comment]
Should this be in scope of neuron? You can always script it using `neuron query` to get a set of all IDs, and then using that to create a new unique ID using whatever scheme you want.

**Comment by fiatjaf** [comment]
I don't know, I think it is in the scope since should (and does!) provide good defaults from its main CLI tool.

But I don't think this feature specifically is a nice default anymore. I'll experiment with it using my own id generator first.
