### ISSUE TITLE
Change the default of `-d` to be current directory, and require `neuron.dhall`

### ISSUE THREAD

**Issue by srid** [srid/neuron#389]
The default value for `-d / --zettelkasten-directory` is `~/zettelkasten`. Change that to always be the current working directory. This allows users to run `neuron` in multiple zettelkastens without having to specify `-d` all the time; they only have to `cd` to the directory before running neuron.

Neuron must error-out if a ` neuron.dhall` file does not exist in the current directory. This means, we make neuron.dhall a requirement. Because, we don't want users to run neuron accidentally on some non-zettelkasten directory, such as project directories with README.md.

In effect, neuron will behave like Git, treating `neuron.dhall` as `.git`, and `-d` behaving like Git's `-C`.

This will affect editor extensions, by @aca @felko @ihsanturk @fiatjaf

**Comment by fiatjaf** [comment]
Well, that was fast.

**Comment by bryan4887** [comment]
Fast, indeed. `neuron search` doesn't work though, while `neuron -d . search` does...

**Comment by srid** [comment]
@bryan4887 Works for me https://asciinema.org/a/1B3gyEhiAqK8FHWkgX9kw0XJu
