### ISSUE TITLE
[nix-bundle] neuron now defaults to /

### ISSUE THREAD

**Issue by MaienM** [srid/neuron#390]
Using the latest version of neuron (from https://github.com/srid/neuron/releases/download/nightly/neuron-linux-bundle) it now seems to default to using `/`. Probably related to #389.

```
❯ neuron --version                                                              
0.6.8.1         
                                                                
❯ pwd                                                                           
/home/maienm/zettelkasten    
                                                   
❯ neuron rib                                                                    
[Rib] Generating / (rebuildAll=False)                                           
[Rib] Unhandled exception when building <unknown>: Error when running Shake build system:                                                                       
  at action, called at src/Development/Shake/Forward.hs:123:5 in shake-0.19.1-1FdWp2zMJy65OeP1Lz81bk:Development.Shake.Forward                                  
* Raised the exception:                                                         
user error (not a neuron notes directory (no neuron.dhall found under /))       

❯ neuron rib -d "$PWD"                                                          
[Rib] Generating /home/maienm/zettelkasten/ (rebuildAll=False) 

```

**Comment by srid** [comment]
Something about your system is causing [`getCurrentDirectory`](https://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:getCurrentDirectory) to function improperly. What is unique about it?

**Comment by srid** [comment]
Per https://github.com/srid/neuron/issues/371#issuecomment-691652727 you are using the nix-bundle. So it looks like the issue is with the [nix-bundle](https://github.com/matthewbauer/nix-bundle) not propagading PWD.

**Comment by MaienM** [comment]
My system is a pretty standard ArchLinux install, nothing stands out to me as potentially related to this.

Seems fair to suspect `nix-bundle`, yeah. Looking at the issue tracker I see a [pull request](https://github.com/matthewbauer/nix-bundle/pull/51) that attempted to support preserve `$PWD` but perhaps this doesn't work in all cases, or it was broken by a later change.

**Comment by srid** [comment]
Let's just not recommend nix-bundle to users then.

https://github.com/srid/neuron/commit/7d57e45aa0135501975131bf760b04fa9f6bad08
