### ISSUE TITLE
Links with `#` anchors are sometimes parsed strangely

### ISSUE THREAD

**Issue by Lysxia** [srid/neuron#397]
For example https://neuron.zettel.page/2017401.html

It looks like this, where the "zettel" link is not parsed as a link:

![Screenshot_2020-09-14 Folgezettel Heterarchy](https://user-images.githubusercontent.com/2515201/93042626-8a1f1a00-f61d-11ea-9416-53a86237bd30.png)

**Comment by srid** [comment]
Regression introduced in https://github.com/srid/neuron/pull/375

**Comment by srid** [comment]
A fix could be to parse an inline tag only if the `#` is preceded by whitespace (or beginning of line).

**Comment by srid** [comment]
https://github.com/srid/neuron/blob/c5ad7eb01e3496b1b68d276ed8ebe35d02b9d97a/neuron/src/lib/Neuron/Reader/Markdown.hs#L145-L152

**Comment by srid** [comment]
This seems like a strange bug in the CommonMark parser. It cannot be reproduce in normal links, like: `<http://google.com/#foo>`. Perhaps something to do with the placement of the hyphen between the two links.

Worked around in https://github.com/srid/neuron/commit/9a89a51bb73870197d0239a888262178f908d45d

**Comment by srid** [comment]
Closing, because I strongly suspect this has to be a bug in commonmark-hs; if not, please re-open.
