### ISSUE TITLE
Allow title as Zettel IDs

### ISSUE THREAD

**Issue by srid** [srid/neuron#399]
Allow arbitrary text in Zettel IDs, so that people can use title in place of some cryptic identifier. For example,

```markdown
Most “storage-oriented” notes will never be useful again. [[Most people take only transient notes]].
```

So we allow whitespace, as well as any other character (except `[` and `]`) that can be used in filenames on macOS and Linux.

A couple of changes will be needed on top of this:
- Generated pages should use a more "clean" URL, however. So the link in the above example should map to `Most_people_take_only_transient_notes.html`.
- Now that title is allowed in ID - if the note has no level-1 heading, use that ID as its rendered title (instead of extracting the first paragraph snippet).

Wouldn't this make the title "static"? Yes, but users can use a refactoring tool to "rename" (for eg: vscode-memo provides one) the references in one-click. Though, this would invalidate the previously published URLs. If that's important, then users should use random IDs along with a custom title in the note, which would still be supported. The documentation should mention this tradeoff clearly.

**Parts**

- [x] Allow whitespace in IDs; slugifying where appropriate (#404)
- [x] Treat title IDs as the title to fallback to when one is not specified
- [x] Allow punctuation marks and other letters

**Comment by srid** [comment]
This adds a bit to the future-proof property. You can open the .md files on any computer, without neuron installed or the generated site available, and still be able to make sense of the plain-text note by reading it on its own.

**Comment by srid** [comment]
> users can use a refactoring tool to "rename" 

Perhaps neuron should provide such a refactoring tool (`neuron rename`).

**Comment by srid** [comment]
Done, and documented at https://neuron.zettel.page/id.html - as well as deployed to [Cerveau](https://www.cerveau.app/).

**Comment by fiatjaf** [comment]
I was going to suggest a rename tool a while ago but I thought some perl regex would do the job.

But now I think a rename tool that keeps the previous name cached somewhere (in the own zettel attributes as an alias, for example) and then gets generated as a redirect link in the site's HTML.

**Comment by srid** [comment]
VScode gif demo of title ID in action: https://neuron.zettel.page/editor.html#vscode
