### ISSUE TITLE
Can I install neuron from a tarball made from contents in my local repo?

### ISSUE THREAD

**Issue by jcborras** [srid/neuron#400]
The official way to install `neuron` is to run:
```{sh}
nix-env --verbose --install --file https://github.com/srid/neuron/archive/master.tar.gz
```
Is there some way to build a tarball from the contents of my local repo so that I could install it with `nix-env -if mytarball.tar.gz`?

**Comment by srid** [comment]
`nix-env -if .` from your local repo?

**Comment by jcborras** [comment]
Thank-you!
