### ISSUE TITLE
Redundant build

### ISSUE THREAD

**Issue by Lysxia** [srid/neuron#402]
When you install neuron, the library gets built 3 times:

- Once by the library
- Once by the executable
- Once by the test suite

This is because both the executable and the test suite mention `src/lib` in `hs-src-dirs`. They should not. Similarly, the test suite should not use the executable's `src/app`. If two or more components need to depend on the same thing, it should be put in a library; this seems a good use case for a private library in `neuron.cabal`.

**Comment by srid** [comment]
@Lysxia This was done on purpose, sothat the ghcid of `bin/run` or `bin/test` would reload when any of the sources change. See https://www.srid.ca/2012605.html

**Comment by Lysxia** [comment]
> Does your PR maintain this feature while improving build time?

Not yet!
