### ISSUE TITLE
support citations via pandoc-citeproc

### ISSUE THREAD

**Issue by boutil** [srid/neuron#405]
Hi,
Would it be possible to implement support for bibliography/citations using pandoc-citeproc?
This would allow to make references to scientific articles or books in zettels, which would be useful for research projects.

Thanks in advance.

**Comment by srid** [comment]
@boutil Is your request a duplicate of #134 ?

**Comment by srid** [comment]
Yup, looks like it - closing as dup.

**Comment by boutil** [comment]
Yes indeed, it is the same. The search I did among the open issues was not thorough enough.

By the way, great project!
