### ISSUE TITLE
Template functions syntax

### ISSUE THREAD

**Issue by srid** [srid/neuron#407]
contd. from https://github.com/srid/neuron/issues/312#issuecomment-666313401

Deprecate 

```
[[z:zettels?tag=foo&timeline]]
```

in favour of

```
{{ zettels | tag=foo | timeline }}
```

- Folgezettel type would use `{{...}}#`
- Template function syntax maps to URIs underneath (the two types are isomorphic)
- The URI syntax will be deprecated but continue to be supported (as it is used as the underlying format in the Pandoc AST)
  - This enables us to do tag queries without the [need to encode them](https://github.com/srid/neuron/issues/446#issuecomment-720001775).
- Template function syntax can be used to provide non-link-query related extensible features like https://github.com/srid/neuron/issues/348#issuecomment-675579685

**Comment by srid** [comment]
Wiki-links can simply become an alias for the 'link' template function, and we can rename 'zettels' to 'linkMany' for naming consistency:

```markdown
{{ linkMany | tag = foo | cf }}
{{ link | some-note | cf }} is equivalent to [[some-note]]
```

```

**Comment by srid** [comment]
Can't say I'm totally convinced about doing this, but will leave it here as a concrete proposal for the record.

**Comment by srid** [comment]
I think we should prevent the folgezettel type here, `{{{ ... }}}`. Allow templates to create ordinary links only.

For folgezettel tagging, use #514 

This constraint will allow us to define template functions that operate on the graph itself, for example:

```
{{ linksFrom | some-note | label=# }} 
```

That will list all noted from `some-note.md` using the `[[Foo]#` syntax (which is an alias to `[[[...]]]`).

**Comment by srid** [comment]
Perhaps we should ditch this syntax entirely and do what Obsidian does; search query in a particular codeblock: https://help.obsidian.md/Plugins/Search

**Comment by ratsclub** [comment]
Would it be possible to add a syntax to include text files in another file? As far as I know mdBook has [this feature](https://rust-lang.github.io/mdBook/format/mdbook.html#including-files).

**Comment by srid** [comment]
Emanote uses Obsidian style queries, which makes this proposal outdated.

Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).
