### ISSUE TITLE
Allow level-1 headers as sub-headings

### ISSUE THREAD

**Issue by srid** [srid/neuron#412]
Use level-1 header as Zettel title only if it exists with a count of exactly 1.

If the first block element is something other than header, then allow (multiple) level-1 headers in the middle of note, while treating them as non-zettel-title-heading in the rendered HTML.

For example the following note should be accepted without requiring the user to change from level-1 to level-2 headers:

```markdown
Some paragraph text.

# Sub-heading

More text
```

Of course, if "Some paragraph text." did not exist and if the heading was the first block element, then we would treat it as zettel title, requiring level-2 headers in the following text.

**Comment by Neurrone** [comment]
Curious about what the motivation for this use case is? This would encourage less semantic documents and potentially more complexity.

I was about to open an issue suggesting that the backlinks header should be a `<h2>` to be more semantically accurate, currently it is a `<h3>`

**Comment by srid** [comment]
@Neurrone I think the current behaviour is rather confusing. For the example above, the zettel's title will be "Some paragraph text", but that's not what an user would intent. At minimum, the title here should be gathered from the zettel ID (filename), and H1 header should be used only if it appears as the very first thing in the note.

**Comment by jenny787** [comment]
Would the appearance of the H1 header be different than the title?  That would be nice.  Because right now, I don't ever use H1 for neuron because it looks the same as the title.  So I use H2+ only.  It would be nice to resolve this.

**Comment by srid** [comment]
@jenny787 That definitely makes sense. 

(PR welcome, of course.)

> Because right now, I don't ever use H1 for neuron because it looks the same as the title. 

This is pretty much what I do. I always use H2, H3, ... (the title comes from filename, via title IDs).

**Comment by srid** [comment]
New behaviour:

![image](https://user-images.githubusercontent.com/3998/109334949-5fbdc380-782f-11eb-9681-6f512cbc0cd0.png)
![image](https://user-images.githubusercontent.com/3998/109334966-66e4d180-782f-11eb-9241-39e7cb655039.png)
