### ISSUE TITLE
"unshare(): Invalid argument" in WSL1

### ISSUE THREAD

**Issue by benjaminhmtan** [srid/neuron#414]
Using the packaged neuron executable on WSL2 Ubuntu gives the error "unshare(): Invalid argument".
This happens with any command.

**Comment by srid** [comment]
I don't have access to a Windows machine right now, but it would be interesting if somebody can [git bisect](https://stackoverflow.com/a/4714297/55246) to find the commit that introduced this.

**Comment by srid** [comment]
cf. https://github.com/microsoft/WSL/issues/2981
