### ISSUE TITLE
Can't install from cachix cache on Darwin

### ISSUE THREAD

**Issue by anka-213** [srid/neuron#415]
It looks like it was pushed to cachix: https://github.com/srid/neuron/runs/1168754575?check_suite_focus=true
```
compressing and pushing /nix/store/9bxxszzvjwqc1lz5b91wshm343yaw325-neuron-0.7.2.4 (57.42 MiB)
```
But it is not there anymore:
```
curl https://srid.cachix.org/9bxxszzvjwqc1lz5b91wshm343yaw325.narinfo
404 - Not Found
```
Maybe it has been garbage collected or something?

--- 

This is what happens if I try to install it

```
$ cachix use srid
$ nix-env -if https://github.com/srid/neuron/archive/f5ebc89652b5ccfaad3bd1ccc463ba2160bf1e68.tar.gz --dry-run | head
(dry run; not doing anything)
installing 'neuron-0.7.2.3'
these derivations will be built:
  /nix/store/6c1jivr6mi96gjympmdgryqvcncfyb6p-neuron-0.7.2.3.drv
these paths will be fetched (309.38 MiB download, 3832.08 MiB unpacked):
  /nix/store/01d3cnjgzrycjdggqb0qn7n3m32v34cp-profunctors-5.5.2-doc
  /nix/store/01g54g8aq7kmsmcl8qr0zx2crajy14is-doclayout-0.3-doc
  ...
```

**Comment by anka-213** [comment]
Maybe the problem is that the docker images are pushed to cachix?

**Comment by anka-213** [comment]
Or that the garbage collection checks what has been used and only keeps the paths that has been used, which is exactly `neuron` and `neuron-data` on ubuntu, which are both being used by CI. Since most mac builds are never used, the get thrown away first.

**Comment by srid** [comment]
Hmm. I have no clue. Perhaps @domenkozar might have ideas -- is this expected behaviour? Or a bug?

**Comment by anka-213** [comment]
What does https://app.cachix.org/garbage-collection say for you? Does it show that it has been collected?

**Comment by srid** [comment]
Looks like it got GC'ed in an hour:

![image](https://user-images.githubusercontent.com/3998/94354510-ba1ce300-0049-11eb-9284-3a0955ada227.png)

**Comment by srid** [comment]
I wonder why the neuron should take >10GB of cache? I don't push anything else to srid.cachix.org.

**Comment by domenkozar** [comment]
Here's what's happening: 

Cachix GC will order paths by last accessed date, then by creation date.

That works really well, until you have 10GB of store paths with last accessed date, so all newly created store paths will get GC-ed right away.

I'm thinking to change to order by (last accessed date OR created date), but need to do testing first to see how that will behave for everyone.

Give me a couple of days to address this.

**Comment by domenkozar** [comment]
I have the prototype ready, going to do testing tomorrow.

**Comment by domenkozar** [comment]
@srid the new GC has been deployed, could you check https://app.cachix.org/garbage-collection shows items that are a few months old under the "Next" section?

**Comment by srid** [comment]
@domenkozar I see items from as far back as May that were GC'ed recently, eg:
 
![image](https://user-images.githubusercontent.com/3998/94493984-0e47d480-01bc-11eb-878b-3dad987092dd.png)

I've pushed a dummy commit https://github.com/srid/neuron/commit/94d57c1e1c5690fb43aac7e79a985cec78ce5c2a - so CI will re-run allowing @anka-213 to test the macOS cache ...

**Comment by domenkozar** [comment]
How does it look? :)

**Comment by anka-213** [comment]
Yes, it works for me now! 🙌

**Comment by domenkozar** [comment]
Thanks for the feedback :)
