### ISSUE TITLE
[Question] markdown link semantics?

### ISSUE THREAD

**Issue by linusboyle** [srid/neuron#418]
Hi all, I'm new to `neuron`, and I'm bewildered by how it handles the builtin link syntax of markdown.

Suppose I have a note `foo.md`. If I write this in `bar.md` :

~~~
[foo](foo)
~~~

then `neuron` regards this link as a folgezettel link. If I change the title:

~~~
[foo2](foo)
~~~

then `neuron` regards this link as a normal link. 

This seems strange to me. Is this behavior intended?

**Comment by srid** [comment]
`[foo](foo)` is effectively an autolink (written as `<foo>`). And neuron treats all autolinks as special, so `<foo>` is a folgezettel link to foo.md; whereas `<foo?cf>` is a cf link. 

The development version and upcoming release adds wiki-links as alias to these autolinks.

I'm curious why you would want to create a link like `[foo](foo)`? First of all, that's a broken link in Markdown, as you linking to "foo" and not "foo.md" (or "foo.html").

**Comment by linusboyle** [comment]
Thank you. I don't know anything about `commonmark` and usually went with the github favored version. The concept of an autolink is interesting though.

> I'm curious why you would want to create a link like `[foo](foo)`? First of all, that's a broken link in Markdown, as you linking to "foo" and not "foo.md" (or "foo.html"). Do you have an actual example?

I actually write my zettels in vim using [vimwiki](https://github.com/vimwiki/vimwiki), and this is the behavior of it. I used to use [gollum](https://github.com/gollum/gollum) for generating the site, and it works very well. It is not necessary to contain a `.html` in the url, so I don't care about link without extension being technically broken.

Well, seeing your explanation, `neuron` is really strict about this. Maybe I'm just accustomed to the old specs.
