### ISSUE TITLE
cannot use Unicode in filename

### ISSUE THREAD

**Issue by linusboyle** [srid/neuron#419]
To reproduce, simply create a zettel named `计算机.md` (the content does not matter), and link to it in another zettel by `[[计算机]]`. `neuron` then complains that `links to non-existant zettel: 计算机`

 I think languages with wide characters should all have this problem.

**Comment by linusboyle** [comment]
If I use the markdown builtin syntax, `neuron` does not give error. But when I click the link it says **File not found**.

**Comment by srid** [comment]
Did you create the zettel using `neuron new`? If so, it is possibly the same as #381 - and you would want to try creating the file manually (eg: `echo Hello > 计算机.md`) to see if the problem goes away.

(FWIW, this doesn't happen in [Cerveau](https://www.cerveau.app/), which uses the same code used to create the new zettel file if not its CLI parsing).

**Comment by linusboyle** [comment]
> Did you create the zettel using `neuron new`? 

No, I created it manually. The problem is not that neuron-cli would mess up the content of the file, but that the note with unicode in its filename is not even recognized by neuron. It's not in any search or query result, and the generated site does not contain it.

PS: I tried `Piemērs` as in #381 and it's the same, so this happens to any unicode.

**Comment by srid** [comment]
I see a different error here:

![image](https://user-images.githubusercontent.com/3998/94950412-9a097b80-04b0-11eb-93ea-dcf0cfe188ac.png)

**Comment by srid** [comment]
Okay so - [modern-uri](https://github.com/mrkkrp/modern-uri), which is used to parse the content inside wiki-links, is unable to deal with unicode:

![image](https://user-images.githubusercontent.com/3998/94950725-13a16980-04b1-11eb-98bc-4c0358debedb.png)

**Comment by srid** [comment]
@linusboyle I think I have a fix for this. Could you try the `unicode-path` branch and let me know it if it fixes the issue for you?

You can install it with:

```
nix-env -if https://github.com/srid/neuron/archive/unicode-path.tar.gz
```
