### ISSUE TITLE
Enable queries from the CLI

### ISSUE THREAD

**Issue by felko** [srid/neuron#42]
Add a `neuron ... query` command to the CLI, which would ease editor support. It would return a list of Zettel IDs that match the specified query. Example: `neuron ... query --tag=science`

Maybe use this to find zettels by title or content with ripgrep, sort of like `neuron ... search` does but returning only the list of IDs instead of starting a fzf interface.

**Comment by srid** [comment]
Closed by https://github.com/srid/neuron/pull/51

**Comment by srid** [comment]
Documented: https://neuron.srid.ca/2013501.html
