### ISSUE TITLE
makefile required to build without nix

### ISSUE THREAD

**Issue by pedramos** [srid/neuron#426]
Hi,

I think a makefile would greatly improve how this software can be distributed. 

For example, I which to build this on freebsd (or at least try) and I would rather not depend on nix to do so. 

I'm not an expert on such topic but I believe that if some distro want to include this they will also benefict from the makefile as well. 
 
I could write one myself and send a PR but, to be honest, I don't know nix language so I don't understand what are the steps to build

BR

**Comment by srid** [comment]
@pedramos This is a Haskell project, and nobody uses plain makefile to build them. The three options to build Haskell projects are: plain cabal, stack and Nix. 

> I believe that if some distro want to include this they will also benefict from the makefile as well.

Distros don't have to use Nix. They can build neuron in a manner similar to they build other Haskell packages. Pandoc for example is written in Haskell, and is available in all popular Linux distros. How do they build Pandoc?

**Comment by srid** [comment]
> They can build neuron in a manner similar to they build other Haskell packages.

This might require #392

**Comment by srid** [comment]
Not gonna step outside of Nix. Static binaries are an exception.

**Comment by pedramos** [comment]
Pandoc at least has an INSTALL.md where it is documented how to install from source.

**Comment by srid** [comment]
Added instructions to install from source (via nix) in d12a9b8.

Sans nix, you can use cabal to build it much like how distros build Haskell software (such as the popular Pandoc); but that might require first addressing #432.
