### ISSUE TITLE
[Feature Request] Tag feed

### ISSUE THREAD

**Issue by leonardt** [srid/neuron#427]
Not sure if this is already possible, but didn't see it mentioned in the documentation.

It would be cool if you could insert a feed of the latest notes for a specific tag (e.g. display the latest 5 notes with the tag `#news`).

This could provide a simple way to develop a useful home/index page that allows for visitor discovery (browse the latest notes on a certain topic of interest)

**Comment by srid** [comment]
Something like this?

```
[[z:zettels?tag=news&timeline&limit=5]]
```

Should be fairly straightforward to implement, beginning with adding an extra parameter (`Int`) to `ZettelQuery_ZettelsByTag` here:

https://github.com/srid/neuron/blob/888aebeabf5a8c79ff5f81700c3d2fac0e83ac66/neuron/src/lib/Neuron/Zettelkasten/Zettel.hs#L44
