### ISSUE TITLE
search fails on macOS 10.15

### ISSUE THREAD

**Issue by adamnbowen** [srid/neuron#430]
I'm getting a strange error when I try to use the search:

```
$ neuron search
envsubst: invalid option -- 'n'
Try 'envsubst --help' for more information.
```

I'm not familiar enough with how the project is built, but I just upgraded to 1.0.1.0 a few minutes ago (search didn't work yesterday for me, but I imagine that's because of the static linking issue resolved in 1.0.1.0).

Let me know if you need more help getting a reproduction of this issue: I only have a handful of notes in my ~/zettelkasten directory, so it's probably not a problem with scale.

**Comment by srid** [comment]
Crap. This is what you get for stepping outside of Nix. Reverting in #431

Properly fix coming later.

**Comment by srid** [comment]
Revert fixed it. Proper fix in  #432

**Comment by fiatjaf** [comment]
I'm experiencing this on binary release 1.0.1.0. Was it supposed to be fixed there?

**Comment by adamnbowen** [comment]
> I'm experiencing this on binary release 1.0.1.0. Was it supposed to be fixed there?

That's the release this issue is talking about, so it was not fixed yet in that release.

**Comment by srid** [comment]
@fiatjaf That's a different issue. You can't bake runtime dependencies like fzf and envsubst (`nix-env -i envsubst` should resolve your issue) into a static binary. If you are using the static binary, it is up to you as the user to install the runtime dependencies manually (we should document this).

Or just use Nix, so you don't have to deal with this annoyance.

**Comment by srid** [comment]
Clarified the static binary limitations here: https://neuron.zettel.page/install-static.html

**Comment by jmiskovic** [comment]
I'm getting same error message on Fedora 32.

Pulling in whole package manager for single tool is not an option for me. Resolving dependencies is ok **if** there is a clear list of dependencies, preferably with minimal versions.

Going from `project.nix` those are: fzf, ripgrep, gawk, bat, findutils and envsubst. I have all of those installed and I'm still getting the error. Looks like envsubst is referring to [this repo](https://github.com/a8m/envsubst) which seems completely unrelated to my [OS-installed tool](https://linux.die.net/man/1/envsubst)?

**Comment by fiatjaf** [comment]
I have `fzf`, `bat` and `envsubst` (is there any other dependencies included in the "etc"?), but still my `neuron search` fails:

```~> neuron search
envsubst: invalid option -- 'n'
Try 'envsubst --help' for more information.
```

Maybe I have a different `envsubst` version than needed? The one I have is `envsubst (GNU gettext-runtime) 0.20.2`.

(Sorry for poisoning your life with non-nix issues.)

**Comment by jmiskovic** [comment]
My workaround was downloading [release](https://github.com/a8m/envsubst/releases) of envsubst, putting it into `~/tools` and adding this to `.bashrc` to make sure it is used instead of gettext one:

`alias neuron='PATH=~/tools:$PATH neuron'`

**Comment by fiatjaf** [comment]
Ok, I did download a new envsubst release and now it opens the fzf search screen, but it is not populated. There are zero zettels in there! And I'm in my zettelkasten directory. It is also empty if I specify `-d`.

**Comment by srid** [comment]
One way to workaround this problem is to get rid of `envsubset` entirely, and resolve the environment variable in Haskell, right about here:

https://github.com/srid/neuron/blob/f760bdc1e95cc34607b07228f487e11667f7dba0/neuron/src/app/Neuron/CLI/Search.hs#L37
