### ISSUE TITLE
Alt text in images does not render

### ISSUE THREAD

**Issue by Neurrone** [srid/neuron#434]
I was able to get an image to render by doing something like `![some alt text](https://some-domain.com/image.jpg)`

However, the generated HTML has no alt attribute as I'd expect.

Doesn't it use Pandoc for the markdown generation?

**Comment by srid** [comment]
Rendering is done by reflex-dom-pandoc, which does seem to pass the attrs: https://github.com/srid/reflex-dom-pandoc/blob/19d81f48643f26deb74ef606a511da7dd8873385/src/Reflex/Dom/Pandoc/Document.hs#L218-L220

What's the Pandoc AST representation of images with alt text? Perhaps [commonmark-hs](https://github.com/jgm/commonmark-hs), which is used for parsing, is not generating the correct AST.

**Comment by astynax** [comment]
I see what Pandoc stores in the `Image` an *alt* text. But [for now](https://github.com/srid/reflex-dom-pandoc/blob/19d81f48643f26deb74ef606a511da7dd8873385/src/Reflex/Dom/Pandoc/Document.hs#L219) this text is forming a `title`.

In MDown we usually define the title *after* the URL: `![alt](url "title")`. So I see a misinterpretation here.

**Comment by astynax** [comment]
```
$ echo '![alt](file.png)' | pandoc -f gfm -t html
<p><img src="file.png" alt="alt" /></p>

$ echo '![alt](file.png "title")' | pandoc -f gfm -t html
<p><img src="file.png" title="title" alt="alt" /></p>

$ echo '![alt](file.png "title")' | pandoc -f gfm -t native
[Para [Image ("",[],[]) [Str "alt"] ("file.png","title")]]
```

**Comment by srid** [comment]
> Looks like the alt text is becaming the inner element...

Strange. If that is indeed the expected semantics of the Pandoc AST, then we whould change `reflex-dom-pandoc` accordingly. [Instructions here](https://github.com/srid/neuron/blob/master/CONTRIBUTING.md#hacking-on-pandocs-html-layout).

**Comment by srid** [comment]
https://github.com/srid/reflex-dom-pandoc/pull/12
