### ISSUE TITLE
search file/title naming inconsistency producing bad links

### ISSUE THREAD

**Issue by LATBauerdick** [srid/neuron#438]
Best explained by example:
- create zettel with file name, say, `<path>/HowTo neuron-vim.html`
- `neuron rib` produces html file `file:///<path>/.neuron/output/HowTo_neuron-vim.html`, replacing the blank with an underscore
- however, using search to find the zettel refers to `file:///<path>/.neuron/output/HowTo%20neuron-vim.html`, i.e. does not replace the blank in the link with an underscore, so the zettel can't be opened.
- the backlink URLs etc are produced correctly though (with the underscore).

I'm sure this is straight forward to fix and it would have been better for me to produce a PR instead of an Issue, but I'm not (yet) setup for that, sorry!

**Comment by srid** [comment]
> I'm not (yet) setup for that, sorry!

So, you basically just need two things here:

1. Nix 
2. VSCode

Then follow https://github.com/srid/neuron/blob/master/CONTRIBUTING.md

It even works on Windows, via WSL 2 remote.
