### ISSUE TITLE
exclude punctuation marks from inline tags

### ISSUE THREAD

**Issue by linusboyle** [srid/neuron#441]
Inline tags are convenient compared with metadata, but the current parsing method is not intuitive.

For example, I would naturally write something like this:

```markdown
.....It seems that the best tool I can find is #Zotero, which is very helpful for academic #writing.
```

And the comma and period is included in the tags, which is not intended.

Another example is that when exported from some other tools, the note is very likely to list tags like this:

```markdown
# An introduction to language

## Metadata

* Type: Book
* Authors: Victoria Fromkin, Robert Rodman, Nina M. Hyams
* Date: 2014
* Date added: 2020-08-15
* Cite key: fromkinIntroductionLanguage2014
* Related: 
* Tags: #Zotero, #ToRead, #Language and Languages, #Linguistics

```

**Comment by srid** [comment]
Added 'good first issue' label.

Those characters (all punctuations?) can be added here: https://github.com/srid/neuron/blob/e7568ca5f51609bb406a48527b5ba52d31d11f9c/neuron/src/lib/Neuron/Reader/Markdown.hs#L224-L226

See CONTRIBUTING.md for instructions.

**Comment by wbadart** [comment]
Came to the issue tracker to open this exact ticket. Beat me to the punch, @linusboyle!

**Comment by linusboyle** [comment]
@wbadart what a coincidence! :smile:
