### ISSUE TITLE
Nightly release falling behind

### ISSUE THREAD

**Issue by wbadart** [srid/neuron#444]
Hey team-

I think something's off with the nightly release process. Looks like the job is running -- since the current [Neuron nightly] was released 9 hours ago -- but it's 245 commits behind master (the most recent commit it includes is from July: a70a532f06d54fdc13510a711a110c3fe41f9e02).

I'm not sure where to start attacking this, but I just thought I'd bring some attention to it.

Thanks!

[Neuron nightly]: https://github.com/srid/neuron/releases/tag/nightly

**Comment by srid** [comment]
The tag is not being updated for some reason: https://github.com/srid/neuron/commits/nightly

![image](https://user-images.githubusercontent.com/3998/96611137-63ae6780-12ca-11eb-9f57-d3b90c10edc4.png)

**Comment by srid** [comment]
CI job:

https://github.com/srid/neuron/blob/b5f9e3acbcbd2e34a632a9c9067683dfbff5318c/.github/workflows/ci.yaml#L49-L62

**Comment by srid** [comment]
It looks like that GitHub action doesn't really update tag. @TheMatten ?

I've manually updated the tag `nightly` for now. 

Fortunately, the actual linux bundle asset has always been pointing to `master`.

**Comment by TheMatten** [comment]
So bundle itself was updated, but description wasn't?

**Comment by srid** [comment]
It doesn't automatically advance the `nightly` git tag, basically, which is what I had always expected it to do (advance `nightly` to point to that revision) since #295.

**Comment by forketyfork** [comment]
Hey, this should fix the issue - please check out my PR #540

**Comment by srid** [comment]
Thanks @forketyfork! Looks like it worked: https://github.com/srid/neuron/runs/1763419420
