### ISSUE TITLE
Unicode support in tags

### ISSUE THREAD

**Issue by flyinggrizzly** [srid/neuron#446]
I have tried to add the following as a tag to a new note: `#日本語/おかもと先生/宿題` (the slashes here are 'normal' slashes, input by changing back to my English input mode).

Instead of rendering out a link with the same content, it is rendering the following html:

```html
<a href="z:tag/日本語/おかもと先生/宿題">z:tag/日本語/おかもと先生/宿題</a>
```

I have tried this with both hierarchical and flat tags, with the same issue.

If it matters, the tag was originally created using the iOS Japanese input keyboard, but I have since redone it on Ubuntu, and it hasn't worked in either case.

**Comment by srid** [comment]
@flyinggrizzly That's expected HTML, actually. Everything, from wiki-links to inline tags, are internally converted z: URIs. 

What do you see in the browser?

**Comment by srid** [comment]
Tag URIs are handled here: https://github.com/srid/neuron/blob/c7d2a3f030eb640f1bd1031679e6cffe06ca974a/neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs#L102-L105

and produced here: https://github.com/srid/neuron/blob/c7d2a3f030eb640f1bd1031679e6cffe06ca974a/neuron/src/lib/Neuron/Reader/Markdown.hs#L148-L152

I suppose a fix is to URI encode the `tag` in line 151. Any takers?

**Comment by flyinggrizzly** [comment]
Thank you for the fix! Links are now working fine in Japanese.

It seems I may have missed a related issue though, since creating links from a tag query doesn't work with Unicode on the latest version of Neuron:


```example
[[[z:zettels?tag=日本語/おかもと-先生/授業]]]
```

```html
<a href="z:/%5bz%3azettels%3ftag=%e6%97%a5%e6%9c%ac%e8%aa%9e%2f%e3%81%8a%e3%81%8b%e3%82%82%e3%81%a8-%e5%85%88%e7%94%9f%2f%e6%8e%88%e6%a5%ad">z:/%5bz%3azettels%3ftag=%e6%97%a5%e6%9c%ac%e8%aa%9e%2f%e3%81%8a%e3%81%8b%e3%82%82%e3%81%a8-%e5%85%88%e7%94%9f%2f%e6%8e%88%e6%a5%ad</a>
```

**Comment by srid** [comment]
@flyinggrizzly So this is a natural limitation of using URIs. The URI spec disallows unicode characters. So you would have to manually encode them. The following should work:

```markdown
[[[z:zettels?tag=%E6%97%A5%E6%9C%AC%E8%AA%9E%2F%E3%81%8A%E3%81%8B%E3%82%82%E3%81%A8-%E5%85%88%E7%94%9F%2F%E6%8E%88%E6%A5%AD]]]
```

You can use https://www.urlencoder.org/ to encode the `日本語/おかもと-先生/授業` in your z query. 

This is annoying, but it should go away once we implement #407 - which would allow `{{{ zettels | tag = 日本語/おかもと-先生/授業 }}}` without any need to encode.

**Comment by flyinggrizzly** [comment]
Ahhh that's good to know, if frustrating. And thanks for the pointer to the encoder!
