### ISSUE TITLE
`|` breaks lists

### ISSUE THREAD

**Issue by eigenzeugs** [srid/neuron#465]
If `|` ist placed somewhere in a list, it is not rendered correctly but instead produces a paragraph in HTML:

```markdown
- a
- |
- b
```
```html
<div class="pandoc">
  <ul>
    <li>a</li>
  </ul>
  <p>- |</p>
  <ul>
    <li>b</li>
  </ul>
</div>
```
I noticed this because I have a list containing mathematical expressions, such as `$|x|$`. If I run pandoc directly to output HTML it works as intended.

**Comment by srid** [comment]
Bug in [commonmark-hs](https://github.com/jgm/commonmark-hs)?

**Comment by eigenzeugs** [comment]
I just tried with the example from the commonmark readme

```haskell
#!/usr/bin/env nix-shell
#! nix-shell -i runhaskell -p "haskellPackages.ghcWithPackages (p: with p; [commonmark])"
{-# LANGUAGE ScopedTypeVariables #-}
import Commonmark
import Data.Text.IO as TIO
import Data.Text.Lazy.IO as TLIO

main = do
  res <- commonmark "stdin" <$> TIO.getContents
  case res of
    Left e                  -> error (show e)
    Right (html :: Html ()) -> TLIO.putStr $ renderHtml html
```

which outputs 

```html
<ul>
<li>a
</li>
<li>|
</li>
<li>c
</li>
</ul>
```

So I guess it's not a bug in commonmark

**Comment by srid** [comment]
If you enable extensions, however, you might be able to reproduce the bug. FTR, [here](https://github.com/srid/neuron/blob/2614d071538cbf92279ef39961fce6ee17ad0073/neuron/src/lib/Neuron/Reader/Markdown.hs#L118-L142) are the extensions used by neuron.

**Comment by srid** [comment]
Probably `pipeTableSpec`. cf. https://github.com/jgm/commonmark-hs/issues/52

**Comment by eigenzeugs** [comment]
Thanks for the hint, I will open a pull request

**Comment by srid** [comment]
Re-opening, because this PR will be reverted. See #473
