### ISSUE TITLE
Web UI overflows horizontally on mobile

### ISSUE THREAD

**Issue by kkga** [srid/neuron#468]
When viewed on an iPhone, the web UI has a slight overflow which makes the page scrollable horizontally.

Here's a screen recording from iPhone 11:
https://ttm.sh/dSk.MOV

**Comment by srid** [comment]
Could use some help from CSS folks.

**Comment by kkga** [comment]
I'm quite comfortable with CSS and would love to contribute, however it looks like you're not using CSS directly here. If you could pinpoint me where and how the CSS is generated, I can play around.

**Comment by srid** [comment]
@kkga Sure, happy to help.

The Haskell DSL for CSS is fairly straightforward to learn. We use [clay](http://fvisser.nl/clay/). neuron's CSS definitions are in these files.

![image](https://user-images.githubusercontent.com/3998/99585417-4c8b9400-29b4-11eb-9926-92448e2272f0.png)

You need to first get neuron running out of Git repo, with auto-compile and auto-reload. VSCode is also handy to use (to get real-time feedback from compiler). Basically install Nix, VSCode, clone the neuron repo, and run `bin/run -d $(pwd)/guide rib -wS`. Then you can edit one the above the files, and neuron would reload and regenerate the HTML files. See CONTRIBUTING.md for dev instructions.

**Comment by kkga** [comment]
Thanks for the instructions, unfortunately I'm unable to run neuron locally: I'm using a non-systemd distribution, so Nix cannot be installed.

I investigated the problem a little: it's 2 elements that are causing the overflow.
1. The footer (with the neuron logo);
2. The ribbon tag labels (on the right of backlinks).

Here are possible solutions.

**1. Footer**
I assume what's causing it to overflow is that it's using a `.grid` class, but it's not inside a `.container`.
Using a grid doesn't seem necessary in this case, as it can be simply replaced with a centered container:
```
<div class="ui center aligned container footer-version">
  <div class="ui tiny image">...</div>
</div>
```

**2. Ribbon tag labels**
The problem here is that the parent `#zettel-container` element has an override for margin (`0.4em` instead of `1em`), but the ribbons are designed for the default `1em`. It's possible to hack around with their positioning, but then they're not aligned with the container visually, as intended.
I guess the solutions here would be either removing the custom margin on `#zettel-container` (less ideal) or replacing the ribbons with simpler inline labels (`.ui .basic .label`) at the bottom of backlinks: 
<img width=400 src=https://user-images.githubusercontent.com/1460122/99652753-43a8ca00-2a69-11eb-906e-e33a48d420d0.png>

**Comment by srid** [comment]
@kkga All of that sounds pretty good to me, thank you. I'll take a look once I have some time.
