### ISSUE TITLE
Commonmark-hs Autolinks (URL) not recognized

### ISSUE THREAD

**Issue by kkga** [srid/neuron#471]
Commanmark-hs autolink extensions [says](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/autolinks.md) that URLs are automatically recognized without requiring the use of `<` and `>`:

```
www.commonmark.org
.
<p><a href="http://www.commonmark.org">www.commonmark.org</a></p>
```

---

However, this doesn't seem to work in Neuron:

```
Visit www.commonmark.org/help for more information.

www.commonmark.org/help.

Visit <www.commonmark.org/help> for more information.
```
... produces the following output:
![image](https://user-images.githubusercontent.com/1460122/99246511-773fe600-2816-11eb-9c71-dd0b111561c3.png)

**Comment by srid** [comment]
Here's a patch that will add this feature, but we must make sure that it doesn't affect existing functionality.

```diff
diff --git a/neuron/src/lib/Neuron/Reader/Markdown.hs b/neuron/src/lib/Neuron/Reader/Markdown.hs
index dd32805..910703f 100644
--- a/neuron/src/lib/Neuron/Reader/Markdown.hs
+++ b/neuron/src/lib/Neuron/Reader/Markdown.hs
@@ -130,6 +130,7 @@ neuronSpec =
       CE.rawAttributeSpec,
       CE.fencedDivSpec,
       CE.bracketedSpanSpec,
+      CE.autolinkSpec,
       CM.defaultSyntaxSpec
     ]
   where
```
