### ISSUE TITLE
brew package

### ISSUE THREAD

**Issue by aca** [srid/neuron#476]
Creating this issue based on https://github.com/srid/neuron/issues/183#issuecomment-705803815
For non-developers, current way of installing neuron for mac is quite a pain.
Hope to see it in brew. 

Really appreciate your hard work srid.

**Comment by srid** [comment]
#307 is probably easier, @aca.

(Why do you think installing on mac is a pain? Do [these instructions](https://nixos.org/manual/nix/stable/#sect-macos-installation) not work?

**Comment by aca** [comment]
@srid I didn't know there's something like that, I will try it later.

Instructions work fine. But it takes quite long, and also had a problem with fish shell (which is nix's issue). 

I understand that nix is great. But, It feels too much to install another package managing system just only for neuron, especially for non-developers.

**Comment by srid** [comment]
For the fish shell issue, see https://github.com/NixOS/nix/issues/440

As for using Nix just for neuron: you can resolve that by using Nix for everything else :-) Basically, as an alternative to homebrew. People who did that report great satisfaction, eg: https://lobste.rs/s/rtluby/macos_nix_setup_alternative_homebrew

**Comment by srid** [comment]
#528

**Comment by srid** [comment]
Closing in favour of #528
