### ISSUE TITLE
`neuron open` fails to open index zettel

### ISSUE THREAD

**Issue by srid** [srid/neuron#477]
![image](https://user-images.githubusercontent.com/3998/99911884-3f78e880-2cc5-11eb-98aa-ea8d15a68db4.png)

**Comment by yeldiRium** [comment]
To avoid confusion with possible contributors: The `--id` flag is called `--slug` since d0b9cccf. However, the bug still exists.
![image](https://user-images.githubusercontent.com/11889637/100928716-dbd19500-34e6-11eb-8840-01d3ce01f763.png)

**Comment by srid** [comment]
Not reproducible anymore.
