### ISSUE TITLE
Provide a flake.nix

### ISSUE THREAD

**Issue by lboklin** [srid/neuron#485]
Offer a Nix flake so that neuron can be added to flake-based system configurations. `nix flake`s is an experimental feature of Nix so it would have to be optional, but it's a great feature that will become the standard method for revision control in nix stable eventually.

I was unsuccessful in adding neuron to my flake-based system - it appears the niv pinning is incompatible with flakes.

https://nixos.wiki/wiki/Flakes

Edit:
I managed to add neuron by adding a nixpkgs revision to my inputs which has a working neuron in haskellPackages and put it in an overlay:
```nix
{
  inputs = {
    # ...
    nixpkgs-neuron.url = "github:NixOS/nixpkgs/c83e13315caadef275a5d074243c67503c558b3b";
  };

  outputs = inputs: with inputs; {
    nixosConfigurations.my-machine = nixpkgs.lib.nixosSystem {
      # ...
      modules = [
        ({...}: {
          nixpkgs.overlays = [
            (final: prev: {
              # ...
              inherit (nixpkgs-neuron.legacyPackages.x86_64-linux.haskellPackages) neuron;
            })
            # ...
          ];
      })
      # ...
      ];
    };
  };
}
```

After that I just used it as a top-level package in my home-manager (as a NixOS module) config.

**Comment by srid** [comment]
I'm not famliar with flakes. But would you like to contribute a PR for adding to documentation? We can add it under https://neuron.zettel.page/2012401.html

**Comment by DerGuteMoritz** [comment]
FWIW, since the version in `nixpkgs` is a bit old, I wanted to use a more recent one from upstream. Here's how I was able to make it work with the current `master` at the time of writing:

```nix
{
  inputs.neuron-notes-src = rec {
    url = "https://github.com/srid/neuron/archive/2547c2132783c6909b6f15837ccd92988c389e8e.tar.gz";
    flake = false;
  };
  # ...

  outputs = { neuron-notes-src, ... }: {
    nixosConfigurations.my-machine = nixpkgs.lib.nixosSystem {
      # ...
      modules = [
        ({...}: {
          nixpkgs.overlays = [
            (final: prev: {
              neuron-notes = (prev.callPackage "${neuron-notes-src}/project.nix" { }).neuron;
            })
            # ...
          ];
        })
        # ...
      ];
    };
  };
}
```

Using version `733e537a8ad76fd355b6f501127f7d0eb8861775` of `nixpkgs`.

**Comment by srid** [comment]
I have been playing with flakes lately, and would be interested in seeing this happen. How would this impact the thunks in [./dep](https://github.com/srid/neuron/tree/master/dep)?

**Comment by srid** [comment]
Could steal some ideas from here: https://github.com/soywod/himalaya/pull/73

**Comment by srid** [comment]
https://github.com/srid/neuron/commit/833ab699e1ec3d8644130e7ac5f1539f118a1552 should allow you to use neuron as a non-flake input,

```nix
{
  inputs = {
    neuron = {
      url = "github:srid/neuron";
      flake = false;
    };
  }

  outputs = inputs@{ .. }:
    utils.lib.eachDefaultSystem (system: 
      let pkgs = import nixpkgs { inherit system; };
           neuron = import inputs.neuron { inherit pkgs system; };
      in { devShell = pkgs.mkShell { buildInputs = [ neuron ]; }; };
}
```

Adding a flake.nix to neuron (PR welcome) would make things simpler though.

**Comment by TheKK** [comment]
Hi, I'd like to help with the flake.nix!
