### ISSUE TITLE
Umlaute break zettel queries

### ISSUE THREAD

**Issue by yeldiRium** [srid/neuron#487]
This example zettel query:

```
[[[z:zettels?tag=abcdeföhij]]]
```

Is rendered to this html:

```html
<a href="z:/%5bz%3azettels%3ftag=abcdef%c3%b6hij">z:/%5bz%3azettels%3ftag=abcdef%c3%b6hij</a>]
```

The URL-encoding of the umlaut (and probably other special characters) seems to break the query parsing and subsequently the generated lists.

**Comment by srid** [comment]
Duplicate?

https://github.com/srid/neuron/issues/446#issuecomment-720001775

At minimum, we can document this limitation.

**Comment by yeldiRium** [comment]
Ah yes. I did not see that issue when searching. Thanks!
