### ISSUE TITLE
Links in search.html are broken for zettels with slug

### ISSUE THREAD

**Issue by srid** [srid/neuron#488]
For eg., in https://www.srid.ca/search.html the links to these zettels are broken, because search.html's JS is not building the link from the "slug" property introduced in #483.

![image](https://user-images.githubusercontent.com/3998/101196936-55899000-3659-11eb-8ec8-bcc8f96343f2.png)

---

Fix should likely go in https://github.com/srid/neuron/blob/9dc3bbd2ce7d91caf633c9ba71c54f51e30ac79b/neuron/src-js/search.js#L16-L17 if anybody is interested in tackling this.

**Comment by jmiskovic** [comment]
This seems to be fixed only in statically generated (`neuron rib`) page? I still see the issue  in server version (`neuron rib -S`) search result page in version `1.1.12.0`.

**Comment by srid** [comment]
Cache problems? Try full browser refresh. Nuke `.neuron` and re-run the command.

**Comment by srid** [comment]
Oh, you should run `neuron rib -w` at least once, to update search.html, of course. Just `-S` won't do any generation.
