### ISSUE TITLE
Google fonts do not use `font-display: swap`

### ISSUE THREAD

**Issue by vizziv** [srid/neuron#493]
The ampersand on the following line of code gets incorrectly escaped to `&amp;` in the generated HTML.
 https://github.com/srid/neuron/blob/f3454ac48aa6e5f33819d478c2cd9df6c969e922/neuron/src/lib/Neuron/Web/Widget.hs#L31

**Comment by srid** [comment]
The browser will recognize `&amp;`. https://stackoverflow.com/questions/12444605/is-it-okay-to-use-html-entities-in-attributes

Check chrome browser inspector:

![image](https://user-images.githubusercontent.com/3998/102291560-4a790e80-3f3b-11eb-9e8c-b4efdb97375e.png)
