### ISSUE TITLE
Directory folgezettels [plugin]

### ISSUE THREAD

**Issue by srid** [srid/neuron#497]
Neuron has an experimental [feature](https://neuron.zettel.page/subdir.html) (disabled by default; [see here](https://github.com/srid/neuron/discussions/309)) for storing notes in sub-directories recursively. We can take it one step further by treating these directories as the folgezettel parent of its contents.

Consider the following directory layout:

```
foo/
foo/bar/qux.md
```

In this proposal, Neuron determines 3 zettels, with `foo` branching to `bar` that in turn branches to `qux`. Only `qux` exists as a file on disk; the other two are created on demand (similar to #379 in concept). The contents of `foo` and `bar` will be populated with the appropriate link query that displays their contents. Users may override this content by adding a `foo.md` and `foo/bar.md`, which will continue to (implicitly) branch of to their contents.

**Comment by srid** [comment]
Addendum:

- The zettel ID of these auto-created zettels should reflect the entire path. So `foo/bar/` should have the ID `foo__bar`. If the user creates a `foo/bar.md`, then the zettel ID would just be `bar`. Why? Because it allow us to have duplicate directory names in the tree; eg: `Archive/2020` and `Tax/2020`. You can create a `Tax/2020.md` without conflicting with the `Archive/2020` directory zettel.

**Comment by srid** [comment]
And,
- There will auto-generated hierarchical tags based on the path. Eg: `foo/bar`. That's how directory folgezettel relationships will be established.

CC @b0o especially as this is looking similar to her [neuron-extras](https://github.com/b0o/neuron-extras)

**Comment by srid** [comment]
https://neuron.zettel.page/dirtree.html

**Comment by RoyiAvital** [comment]
In my opinion this project has 2 layers:

1. The graph generation engine.
2. The generation of the consumption form of the data (The website).

I think it will make sense to tag issues based on which layer they act on.
For instance, having an automated generation of a web page per tag which by default shows the cloud of the Zettels using this tag ("Cloud" in the form of the result of the query `[[z:zettels?tag=foo]]` is a great idea in my mind.  

Changing the graph and relations by adding a new object into the graph which is not user generated, is wrong in my opinion.

But regardless of my opinion, making easy to understand on which layer we're talking, in my opinion will generate a better discussion between the users.
