### ISSUE TITLE
Impulse: add extra shortcut for interop with likes of Vimium

### ISSUE THREAD

**Issue by srid** [srid/neuron#501]
`/` is reserved by Vimium by default. Use an extra shortcut, such as `\` or `s`.

**Comment by gillchristian** [comment]
Maybe `t` which is GitHub's shortcut to the search view.

**Comment by srid** [comment]
Actually, `t` is also reserved by default in Vimium (for opening tnew tab).

**Comment by RoyiAvital** [comment]
The Impulse page also misses the lower bar of other pages (Link to `Home`, `Edit`, etc...).
It would be great to have it there as well (In results as well).
