### ISSUE TITLE
Failed to build .drv file on install.

### ISSUE THREAD

**Issue by frenchdonuts** [srid/neuron#504]
I'm getting this error: `build of '/nix/store/hykjg8d315cj6d1kpv3iwzp8vvc49hzm-neuron-1.9.1.5.drv' failed` when running `nix-env -if https://github.com/srid/neuron/archive/master.tar.gz`. It looks like ZettelSpec.hs isn't compiling because Neuron.Zettelkasten.Zettel doesn't export MetadataOnly(MetadataOnly). I've attached a screenshot below:
<img width="726" alt="Screen Shot 2020-12-29 at 1 43 42 AM" src="https://user-images.githubusercontent.com/2016045/103264149-de090100-4977-11eb-848f-068baf0325dd.png">

**Comment by frenchdonuts** [comment]
Oh, and thank you for your work on this!

**Comment by srid** [comment]
My bad, I pushed a commit yesterday without doing a full build.

Fixed in master.
