### ISSUE TITLE
Impulse: tags with emoji or spaces

### ISSUE THREAD

**Issue by gillchristian** [srid/neuron#505]
Links to tag search don't work on Impulse when the tag contains emoji or spaces.

- Emoji: https://gillchristian.github.io/digital-garden/impulse.html?q=tag:%F0%9F%8C%B1
- Spaces: https://gillchristian.github.io/digital-garden/impulse.html?q=tag:Foo%20bar

<img width="600" src="https://user-images.githubusercontent.com/8309423/103275848-5ba72e00-49c5-11eb-9a7e-889ff7be01f1.png" />

<img width="600" src="https://user-images.githubusercontent.com/8309423/103275811-43371380-49c5-11eb-9ab1-88f6d12c28b7.png" />

Searching directly in Impulse for a tag that includes emoji works. But it doesn't for tags with spaces.

<img width="600" src="https://user-images.githubusercontent.com/8309423/103274715-98bdf100-49c2-11eb-8da9-6ff6012eabb1.png" />

As a side note, links containing emoji, spaces or both do work on Cerveau:

<img width="450" src="https://user-images.githubusercontent.com/8309423/103274463-04538e80-49c2-11eb-9457-2385f22e1532.png" />

<img width="450" src="https://user-images.githubusercontent.com/8309423/103274535-36fd8700-49c2-11eb-8eb3-e77f8c5be18f.png" />

<img width="450" src="https://user-images.githubusercontent.com/8309423/103274486-13d2d780-49c2-11eb-9e82-4d28ad28f433.png" />

**Comment by srid** [comment]
Can emojis be used in zettel IDs and filenames?

(Soon enough, tags can contain exactly what's allowed in zettel ID)

**Comment by srid** [comment]
Spaces ... we should definitely support. 

Might have to allow quotting in the search query (as it gets improved), i.e.: `tag:"Foo Bar"`

**Comment by gillchristian** [comment]
> Can emojis be used in zettel IDs and filenames?

At least not in file names. So I guess it makes sense they don't work on tags either.

> Spaces ... we should definitely support.
>
> Might have to allow quotting in the search query (as it gets improved), i.e.: `tag:"Foo Bar"`

Should I close this issue and open one specific for spaces? Or is that already under the radar?

**Comment by srid** [comment]
Yes, spaces will have to get supported as part of #379. Some things to consider:

- Inline tags (`#foo`) may not support spaces. 
- However, we can "extend" inline tag syntax so that it can support full range of zettel IDs. eg: `#[[Foo bar]]`. 
  - Basically the syntax is same as for links, but we tack in a `#` at the beginning.
  - This means, we would have three types of links: `[[` (cf), `[[[` (folge), `#[[` (reverse-folge).
- In YAML metadata, you can already use spaces by quoting, `tags: [ "Foo bar"]`

**Comment by gillchristian** [comment]
Yeah, there are several cases to cover to fully support spaces in tags.

Closing this since #379 will cover it. 

Will checkout the conversation at Matrix :eyes:
