### ISSUE TITLE
dirtree: rename `index/**` tags

### ISSUE THREAD

**Issue by srid** [srid/neuron#508]
The dirtree plugin reserves `index/**` tags for its own purpose. However. `index` is not an uncommonly user chosen tag ("index" can refer to "index zettels" in Zettelkasten-speak). So we must rename it to something else. 

This tag semantically connotes a filesystem path, with the top-level tag representing all notes in the top-level path. 

Perhaps rename it to `root/**`. And explain the tagging behaviour well in docs.

**Comment by RoyiAvital** [comment]
I would even add an option for `dirtree` not to add _Root Level_ tag.
