### ISSUE TITLE
Keyword intersection query

### ISSUE THREAD

**Issue by dpwiz** [srid/neuron#509]
I'd like to have listings for pages that contain tag intersections, like "pages about a **package** that is related somehow to **vulkan** ecosystem. Or "**game** that has **multiplayer** aspect".

```
[[z:zettels?tag=package&tag=vulkan]]

[[z:zettels?tag=game&tag=multiplayer]]
```

And on "multiplayer" page, have a list of everything about multiplayer: packages, games, tutorials etc. (this is solved by tags as they are now)

Current syntax only has "union" lists and I could not find other valid options.

**Comment by srid** [comment]
Dup? https://github.com/srid/neuron/issues/358

**Comment by dpwiz** [comment]
Ah, yes. Missed it somehow.
