### ISSUE TITLE
Labelled directional links

### ISSUE THREAD

**Issue by srid** [srid/neuron#514]
Deprecate (while still supporting) `[[[` in favour of labelled & directional links. 

A folgezettel link would look like: `[[Some note]]#`. That is, the `#` signifies the connetion **label** (called "folgezettel"); and its position (here, being at the *end* of the link) signifies the **direction** of the folgezettel connection.

The same link with *reversed* direction would look like: `#[[Some note]]`. This creates a folgezettel connection *from* `Some note.md` to the current note. 

In effect, this is similar to tagging of #379. Unlike inline tags, this syntax allows whitespace in tag names. This proposal can also act as an alternative to the use of tags in #379.

Open question: automatically list branching links? Consolidate with dirtree plugin's view? Or keep them separate?

---

Custom labels becomes possible with this proposal, eg: `[[Some note]]$`.

---

A more general proposal would be "glued links", and making the above an alias to it. 

That is, `[[Some note]]#` becomes an alias for `[[Some note]][[Folgezettel]]`, where "Folgezettel" becomes a special zettel indicating the label of the glued connection (one might treat this as a hyperedge of 3 vertices). This way, users may introduce custom connection labels if they so wish; and the backlinks panel can group the backlinks by connection label zettel.

**Comment by jenny787** [comment]
great idea.  I would use this and normal links to cover all my linking needs.

**Comment by jdcola** [comment]
It's a great proposal but the link direction metaphor looks odd to me.
Intuitively, `[[some note]]#` seems like `[[some note]]->[[current note]]` which means from `some note.md` to the current note. While `#[[some note]]` seems like `[[current]]->[[some note]]` which means from current to `some note.md`.
(Reading from left to right and intepret `#` as `-->`.)

**Comment by srid** [comment]
Visualize the label (`#`) as a magnet, that pulls the node in that direction, leaving the other node in its position.

I favour this position, only because it matches the semantics of inline tags (`#foo`). But I'm open to other ideas and approaches.

**Comment by srid** [comment]
Summary https://gab.com/srid/posts/105601439790477782

**Comment by MaienM** [comment]
You summary link appears to be dead.

**Comment by srid** [comment]
@MaienM Just check the official docs https://neuron.zettel.page/folgezettel

I don't usual social media anymore. Micro updates on neuron will be made available in https://www.srid.ca/microblog and more specifically under https://www.srid.ca/neuron (both these links have Atom feed in them).
