### ISSUE TITLE
In-title Zettel IDs not converted to their titles.

### ISSUE THREAD

**Issue by ihsanturk** [srid/neuron#523]
neuron version: `1.0.0.0`

Should I not link a zettel in a title or is this a bug?

### Steps to Reproduce
1. Create a zettel let's name "Banana" (and the file name is: "1234abc.md")
2. Create another zettel named "Eating [[1234abc]]"
3. Run `neuron rib -S`
4. Open your web browser and go the "Eating Banana" zettel
5. Look at the zettel roots or backlinks and see `z:/1234abc?cf` instead of its title

### Example
<img width="765" alt="Screenshot 2021-01-11 at 22 28 17" src="https://user-images.githubusercontent.com/24369769/104229403-4d452180-545d-11eb-8362-4f0b33a462c0.png">
<img width="717" alt="Screenshot 2021-01-11 at 22 06 33" src="https://user-images.githubusercontent.com/24369769/104229420-5209d580-545d-11eb-9a59-e04fcb1bf9a4.png">

It looks right on the zettel that titled with zettel ID though:
<img width="715" alt="Screenshot 2021-01-11 at 22 40 59" src="https://user-images.githubusercontent.com/24369769/104230163-436fee00-545e-11eb-871a-240bd14ab7a4.png">

**Comment by srid** [comment]
> Create another zettel named "Eating [[1234abc]]"

Filename and contents of this zettel?

**Comment by ihsanturk** [comment]
`1234abc.md`
```md
---
date: 2020-01-12
---

# Banana

A fruit

See also: [[[5678def]]]
```

`5678def.md`
```md
---
date: 2020-01-12
---

# Eating [[1234abc]]
```

**Comment by srid** [comment]
Right. Zettel title, along with other metadata, are "computed" ahead of the graph generation, so query links are not resolved. This is why you see them zettel title only. Basically this is unsupported.

I would suggest not using wiki-links in title; use plain text, and put the wiki-link in the body (usually the first sentence/paragraph)

**Comment by srid** [comment]
Opened #525 so to make the uptree render as `[[foo]]` instead of `z:/foo`.
