### ISSUE TITLE
Searching for tags in impulse has opposite of expected effect

### ISSUE THREAD

**Issue by yeldiRium** [srid/neuron#524]
When searching for a tag via impulse by inputting `tag:tagname` into the searchbox, it filters out all zettels that match the given tag. I.e. matching zettels are *not* shown.

It should be exactly the opposite.

[This line](https://github.com/srid/neuron/blob/5c67c037099f08ca810d970618d388a816362de2/neuron/src/lib/Neuron/Frontend/Impulse.hs#L162) should contain a `not`.

Edit: I don't have my dev environment set up right now, otherwise I'd open a PR. Sorry for that.

**Comment by srid** [comment]
I will fix this. 

Note that for PRs like this, the `bin/build-impulse.hs` script must be run before committing, so as to update the generated JS file.
