### ISSUE TITLE
impulse has link problems with certain filenames

### ISSUE THREAD

**Issue by zettelzottel** [srid/neuron#535]
Example zettel name that contains an error

> 082dee3bafde0c3da3d1c249128eefb9-Prufung_Durch_US-Arzneimittelbehorde_Biontech_Und_Pfizer_Beantragen_Notfallzulassung_Fur_Covid-19-Impfstoff_in_Den_USA_by_handelsblatt.com.md-note1

The missing link in the example zettel is 

> 082dee3bafde0c3da3d1c249128eefb9-Prufung_Durch_US-Arzneimittelbehorde_Biontech_Und_Pfizer_Beantragen_Notfallzulassung_Fur_Covid-19-Impfstoff_in_Den_USA_by_handelsblatt.com.md

It seems that all links that have **something.something.md** have problems. I cannot say 100% percent for sure.

The errors also can be directly looked up at https://lost-frequenceis.eu/impulse.html

**Comment by srid** [comment]
I can't reproduce this. @zettelzottel 

I used the exact filename.

What's the output of your neuron server? (command line, in the server)
