### ISSUE TITLE
I don't understand what a "Folgezettel Heterarchy" is

### ISSUE THREAD

**Issue by ckp95** [srid/neuron#537]
Hi, I found this project from a HN comment, it looks interesting. I'm reading through the docs, and I'm really confused by this:

https://neuron.zettel.page/linking.html

> 
> Neuron supports branching links, which can be created using [[[..]]]
> 
> [...]
> 
> The 3-bracket syntax creates a special link (called a folgezettel) to the specified zettel. When a zettel has a folgezettel relationship to another zettel, it is said to “branch of” to the other zettel. Folgezetel relationships define the Folgezettel Heterarchy of your zettel graph.
> 
> Branching links affect the linked zettel’s Uplink Tree where the linking zettel is displayed.

Then I read the ["Folgezetel Heterarchy page"](https://neuron.zettel.page/folgezettel-heterarchy.html) and the pages about "Impulse" and "Uplink Tree" ... and I just don't get it! Seriously I've been staring at these pages for 10 minutes trying to figure out what they actually mean and I'm just stumped. It's like a self-referential collection of made up Dr Seuss jargon and totally impenetrable for an outsider.

Can anyone just tell me, practically speaking, what the difference is between the double-brackets and the triple-brackets? What does it mean to "branch of" and how is that different from just a normal link?

**Comment by srid** [comment]
Hey there!

Thanks for your feedback. I can see that the documentation around folgezettel is confusing to new comers. We should improve it.

Conceptually, think of folgezettel links (`[[[..]]]`) as being **no different** to regular wiki-links (`[[...]]`), except that folgezettel links get the *label* called "folgezettel". Links with the "folgezettel" labels are used to build a category-tree like hierarchy ("heterarchy" specifically, as multiple parents are allowed) that gets rendered on top of a zettel page. See for examples,

- https://alien-psychology.zettel.page/S01E04.html 
- https://www.srid.ca/veg.html

Note the inverted tree on top of these pages; that's the folgezettel heterarchy leading up to that zettel.

If all of that makes sense, take a look at https://github.com/srid/neuron/issues/514 which generalizes further on this "link labelling" concept.

**Comment by ckp95** [comment]
So they are just for more important or "hub" notes or something?

What happens if the uplink graph has a cycle in it?

**Comment by srid** [comment]
Hub notes are part of the kind of things you can define, yes. Cycles are handled by [algorithmically](https://hackage.haskell.org/package/algebraic-graphs-0.5/docs/Algebra-Graph-AdjacencyMap-Algorithm.html#v:bfsForest) breaking them.

**Comment by srid** [comment]
Improved docs a bit: https://neuron.zettel.page/folgezettel.html

PR welcome for further improvements
