### ISSUE TITLE
Allow running neuron commands from subdirectories

### ISSUE THREAD

**Issue by chiefnoah** [srid/neuron#544]
With the new directory plugin, I've found myself `cd`-ing into a subdirectory from my zettelkasten root. This prevents command such as `neuron new` from working. Similar to how git searches upward for a `.git` folder, I think it should be possible to have neuron search parent directories for a `neuron.dhall`.

**Comment by srid** [comment]
As an aside, I'm starting to wonder if we need `neuron new` at all.

The following works:

```
$ echo "Hello Word" > "New Zettel.md"
```

The main advantage with `neuron new` is that it auto-sets today's date. 

But yes, making `neuron` work like `.git` is a good thing. It would be the natural next step to #389

**Comment by chiefnoah** [comment]
I just used `neuron new` as an example, other subcommands such as search are also effected and should be relative to the zettel root.

As an aside, `neuron new` also fills in the frontmatter and assigns a random ID file name, which I personally like. I have a shell alias setup to `nn` to create and edit a new zettel. It doesn't necessarily need to be part of neuron, I could simply have a script like this instead:
```shell
#!/bin/bash

ID=${1:-$(date | base64 | cut -c1-8)}
FILENAME=$(echo "$ID" | sed -e 's/[^A-Za-z0-9._-]/-/g' | tr '[:upper:]' '[:lower:]').md

cat <<EOF > $FILENAME
---
date: $(date '+%FT%R')
tags: []
---

# $ID

EOF

exec $EDITOR $FILENAME
```

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next
