### ISSUE TITLE
ANSI colors in emacs look ugly

### ISSUE THREAD

**Issue by arkoort** [srid/neuron#555]
When [neuron-mode](https://github.com/felko/neuron-mode) uses neuron executable for generating HTML, its output in the `*compilation*` buffer look like:

    [90m   Plugins enabled: links, tags, uptree[0m
    [90m   Loading directory tree (84 .md files) ...[0m
    [90m   Building graph (84 notes) ...[0m
    [90m   Building route data ...[0m
    [90m   Rendering routes (85 slugs) ...[0m
    [94m💾 impulse.html[0m
    [94m💾 forth.html[0m
    [94m🥅 2 files updated in /home/ark/zettelkasten/.neuron/output[0m

If I understand right, [System.Console.ANSI](https://hackage.haskell.org/package/ansi-terminal-0.10.3/docs/System-Console-ANSI.html) has function `hSupportsANSI`, which can determine this situation. Maybe it would be better not to use colors if this function returns False.

**Comment by srid** [comment]
Agreed; this would be a good candidate for a PR.

**Comment by srid** [comment]
neuron uses the `co-log` library; so perhaps try to figure out how other co-log users achieve this in an idiomatic way.

https://github.com/srid/neuron/blob/master/neuron/src/app/Neuron/CLI/Logging.hs

**Comment by forketyfork** [comment]
Hey, please check out my PR that fixes the issue.
