### ISSUE TITLE
`neuron … search` misbehaves when there is only one note

### ISSUE THREAD

**Issue by Gabriel439** [srid/neuron#56]
To reproduce:

```
$ mkdir test
$ neuron test new Test
$ neuron test search
```

It will misbehave in a few ways:

* There will be a `[bat error]: 'title': No such file o…` error message
* Attempts to refine the query will generate 0 results
* Selecting the single note will return `./test/title` instead of the path to the note

Once you add more than one note, though, the problem disappears

**Comment by srid** [comment]
Looks like a bug in [this script](https://github.com/srid/neuron/blob/7d52fab/src-script/neuron-search/default.nix).
