### ISSUE TITLE
Use emojis only if terminal supports it

### ISSUE THREAD

**Issue by srid** [srid/neuron#563]
This is an extension of #555

On GitHub actions, we see emojis getting replaced with question marks, which is obviously useless and confusing.

![image](https://user-images.githubusercontent.com/3998/108866167-f2592b00-75c1-11eb-918b-35cb2cddb52d.png)

https://github.com/srid/neuron-template/runs/1962405074

We should display error/warn/etc. markers in absence of emojis.

**Comment by forketyfork** [comment]
I noticed that emojis worked fine in GitHub actions before the build was dockerized: https://github.com/srid/neuron-template/runs/1942559665?check_suite_focus=true
And starting with "Build using docker", there are only question marks: https://github.com/srid/neuron-template/runs/1962405074?check_suite_focus=true
So this may as well be a dockerization issue, e.g. wrong or absent LANG setup in Dockerfile.

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).
