### ISSUE TITLE
`neuron` command should instantly spawn a server and open web browser

### ISSUE THREAD

**Issue by srid** [srid/neuron#573]
Make `neuron` an alias to `neuron gen -wS --pretty-urls --open` which in effects runs neuron generation/server and opens the URL in the browser instantly. This will require implementing the following:

* `--open`: equivalent to running `neuron open` after the server is up
* `-S`: if the default port (8080) is already bound, pick something that's available.

The idea is to be able to `cd` to any zettelkasten directory, and run `neuron` to get its web interface opened without any fuss.

**Comment by dpwiz** [comment]
What would it do if ran outside a neuron directory?

**Comment by srid** [comment]
Nothing special; behave like neuron does currently (error out due to missing neuron.dhall unless -d is passed).

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, in the context of Emanote, [post here](https://github.com/srid/emanote/issues/new/choose).
