### ISSUE TITLE
`cache.json` not available from server in local environment

### ISSUE THREAD

**Issue by flyinggrizzly** [srid/neuron#574]
In a local server (e.g `localhost:8080`), the `cache.json` file does not appear to be served by Neuron/rib. It is generated and present (and accessible in a site hosted from S3), but not accessible from the browser when served locally.

Neuron version: 1.9.19.0
OS:
  server: WSL2 running Ubuntu 20.04
  browser: Firefox on Windows 10

This is a change in behavior--I've been using `cache.json` on Neuron v. 1.9.3.0 in a custom browser script, but it no longer works after updating.

The browser script isn't important, but this will make work on #568 difficult if there isn't a cache file to work with to build the search index.

If this is an intentional change, feel free to close--I'll figure out a way to work with localfiles instead of the rib dev server for #568.

**Comment by srid** [comment]
Fixed in 1.9.20.0. This was a regression introduced in #564
