### ISSUE TITLE
tags: web listing enhancements

### ISSUE THREAD

**Issue by lucab** [srid/neuron#588]
Thanks for developing this project, it's a very interesting tool! I have a couple of wishlist items related to how `neuron` handles tags listing / exploring / linking in the generated webpages.

In my usecase I have a pile of daily notes, with a random assortment of topics in each one. I do make heavy use of nested hierarchical tagging in order to navigate and link them. Right now the webpages rendered by `neuron` are suboptimal to navigate because they are lacking a way to 1) automatically generate indexing pages for each tag, and 2) generate an overall listing of all known tags.
In short, it would be great to have something similar to `dirtree` for tags.

As a real example, let's say I have two notes which are tagged one as `formal-methods/smt/cvc4` and the other as `formal-methods/smt/z3`.
I'd like to see the following set of webpages autogenerated:
 * `formal-methods.html`
 * `formal-methods/smt.html`
 * `formal-methods/smt/cvc4.html`
 * `formal-methods/smt/z3.html`

Strictly related, I'd like to have a tag-query syntax (or any other embeddable way) to produce a tree listing/index of known tags, linking each entry to the autogenerated pages above, like this:
```
+ [formal-methods](formal-methods.html) (2)
  + [smt](formal-methods/smt.html) (2)
    - [cvc4](formal-methods/smt/cvc4.html) (1)
    - [z3](formal-methods/smt/z3.html) (1)
```

**Comment by srid** [comment]
I agree this would be very good to have in neuron. Meanwhile you might want to checkout @b0o's https://github.com/b0o/neuron-extras ([linked here](https://neuron.zettel.page/extras)).

> I'd like to have a tag-query syntax (or any other embeddable way) to produce a tree listing/index of known tags, linking each entry to the autogenerated pages above, like this

Try `[[z:tags]]` query - but that won't be useful (due to lack of linking) until either this feature or #567 is done.

**Comment by srid** [comment]
@lucab Checkout [Emanote, next-gen neuron](https://neuron.zettel.page/next) which has this feature. Demo https://www.srid.ca/-/tags

Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).
