### ISSUE TITLE
Files with `§` in title not recognized

### ISSUE THREAD

**Issue by danymat** [srid/neuron#595]
I'm currently using the `§` character to add structure to my ZK (`§§`, `§1`, etc). 
I think this character is not recognized by neuron

Steps to reproduce

1. Create a file test.md
2. Create a second file `§2\ test.md`
3. Link the second file in the first file 
4. Only the first file will be recognized

**Comment by srid** [comment]
How are you linking to it?

See also https://github.com/srid/neuron/issues/446

**Comment by danymat** [comment]
For example I have a file called: `202102241246 §1 Zettelkasten.md`

In its content I have:
```md
## Objectif

- [[202102081550 L'objectif d'un slip-box]]
```

which is linking the file `202102081550 L'objectif d'un slip-box.md`

The problem is that even neuron query doesn't return any file with a `§` on it.

**Comment by srid** [comment]
Okay. That character is not allowed in the whitelist:

https://github.com/srid/neuron/blob/833ab699e1ec3d8644130e7ac5f1539f118a1552/src/Neuron/Zettelkasten/ID.hs#L81-L99

I'm trying to recall the rationale for that. Filesystem filepath and URI limitations are the main reason I think.

**Comment by danymat** [comment]
Nice, I was wondering where you defined the parsing whitelist.
I propose to add this special character to the whitelist (except if there is a way to add personal whitelist in the config file)

**Comment by srid** [comment]
Sounds good to me, feel free to open a PR (the CI will catch any errors).
