### ISSUE TITLE
Can't get dirtree to show up

### ISSUE THREAD

**Issue by pinpox** [srid/neuron#599]
Hey, this might be more of a question than an issue but I couldn't figure it out form the documentation:

I'm trying to get a the `dirtree` plugin to work, if I understand correctly it should tag (sub-)folders according to their name. 

Here is my simple example: https://github.com/pinpox/zettelkasten

It containes two subfolders (categories) with 2 posts each, how do I show that correctly in the `index.md`? It looks like this currently (no posts shown): 
![image](https://user-images.githubusercontent.com/1719781/115224666-71c03200-a10d-11eb-9fc1-a951fd411260.png)

How would I make the main `index.md` page show some predefined header + the cathegories with a list of all files in them (or maybe the last 10 of them)?

**Comment by srid** [comment]
> `[[z:zettels?tag=Motorcycles]]`

I believe this should instead be:

```
[[z:zettels?tag=root/Motorcycles]]
```

The dirtree plugin prefixes every hierarchical tag it generates with `root/` (so as to avoid conflict with user's tags).
