### ISSUE TITLE
Error when using queries and custom ids

### ISSUE THREAD

**Issue by Nadrieril** [srid/neuron#60]
I use a different ID scheme (with letters instead of numbers to encode the date) than the one neuron uses. So far I have had no problems, except when using `zquery://`. Specifically, this line:
https://github.com/srid/neuron/blob/f7f0c134a4e7f7f947486bac5261b4157c83298e/src/Neuron/Zettelkasten/Link/View.hs#L35
tries to parse the zettel ids to sort them, but obviously that fails for me. Since sorting ids alphabetically should do the same as sorting them by date, would it be possible to not try to parse the ids here ?

**Comment by Nadrieril** [comment]
In case anyone is curious, here's the scheme I use:
```
20 dt b vs
        ^^ minute*10 + second/6 encoded in base 26
      ^ hour in base 26
   ^^ (month-1)*31 + day-1 in base 26
^^ year
```
The above corresponds to 2020/04/05 1:56:24am.
This gives me a precision of 6s in an id of 7 chars, which is short enough to be memorable but enough that in practice I don't need to know which zettel ids exist to generate a new one. I need that to be able to create zettels from my phone. I could get a better precision by adding digits as well, but having just letters makes it easier to type on phone an laptop.

**Comment by srid** [comment]
The "ID is a timestamp" assumption is hard coded into Neuron, however I'm open to considering the possibility of supporting arbitrary text, as long as it doesn't complicate things. How does #59 affect this? Would neuron have to consider any arbitrary `<foo>` and try to lookup the `foo.md` zettel?

**Comment by srid** [comment]
> Since sorting ids alphabetically should do the same as sorting them by date, would it be possible to not try to parse the ids here ?

I think this is fine, as an immediate workaround to address your problem.

**Comment by Nadrieril** [comment]
> The "ID is a timestamp" assumption is hard coded into Neuron

Not that much actually. Apart from new note generation and this issue, I haven't notived other places where this mattered.

> Would neuron have to consider any arbitrary `<foo>` and try to lookup the `foo.md` zettel?

I think that would make sense. I would say we allow any `[a-zA-Z0-9_-]+` as an id.

> How does #59 affect this?

Assuming the restriction above, #59 doesn't change anything

**Comment by Nadrieril** [comment]
https://github.com/srid/neuron/commit/090147f831a2698973b2e397b69787d4ba3ac8af fixes my issue, thanks !
