### ISSUE TITLE
Feature Request: Conjunctive, Disjunctive, and Negative Tag Filtering

### ISSUE THREAD

**Issue by samwalls** [srid/neuron#602]
Is there currently a way to make more complex tag queries involving AND, OR, and NOT operations?

Example:
- `?tag=todo/urgent/**`, all zettels marked as urgently TODO
- `?tag=todo/important/**`, all zettels marked as importantly TODO
- `?tag=todo/**&tag=!todo/urgent/**&tag=!todo/important/**`, all _other_ zettels (i.e. marked as TODO _and not_ urgent _and not_ important).

The syntax could look different in practice, but hopefully this is easy enough to understand.

Could we expand the tag filtering system to include:
- conjunctions of tags: `tag=blah_A&tag=blah_B`, or `tag=blah_A+blah_B` etc.
- disjunctions of tags: `tag=blah_A|blah_B`
- negations of tags: `tag=!blah`

**Comment by srid** [comment]
Dup of #358
