### ISSUE TITLE
Support for named links

### ISSUE THREAD

**Issue by pgronkievitz** [srid/neuron#606]
Hi, In many languages some words are spelled differently depending on context (declension and probably more in other languages than Polish). That would be really nice to be able to name links. E.g. like in obsidian `[[note-id]]` displays note's title, but it's possible to link like `[[note-id|displayed text]]`. I know it's possible to use regular markdown links, but those are not as nicely integrated in most cases as this custom syntax.

**Comment by srid** [comment]
Dup of #373
