### ISSUE TITLE
Feature Request: File inlining (in Markdown)

### ISSUE THREAD

**Issue by ratsclub** [srid/neuron#613]
As noted on Neuron's Matrix room, it'd be nice to have *File Inlining* as a feature.

Considering the following file called `main.py`:

```py
# ANCHOR: main
def main():
    print("Hello, World!")
# END_ANCHOR: main
```

One should be able to inline it inside other markdown files with the following syntax:

```md
# Include the whole file
![](main.py)

# Line range
![](main.py:2:3)

# Everything between anchors
![](main.py:main)
```

Note this is just an abstract. Syntax and feature ideas are welcome

**Comment by srid** [comment]
See also https://github.com/srid/neuron/discussions/620 by @RoyiAvital

How does Obsidian behave when embedding source code using this syntax? Does it support extracting a subset based on line rage?

**Comment by srid** [comment]
Adding general embedding `![[..]]` in https://github.com/srid/emanote/issues/24

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose). Specifically continue discussion in https://github.com/srid/emanote/issues/24

**Comment by srid** [comment]
https://github.com/srid/emanote/pull/719
