### ISSUE TITLE
Feature request: first class support for regular markdown links

### ISSUE THREAD

**Issue by aignas** [srid/neuron#614]
I really dig this tool, however, one thing that is half-working for me is the regular markdown links, which would point to the `md` file as it is on the file system. Reasons for why I think markdown links may be good:
* I want my notes to be in a private github repo and having some support for the built-in markdown rendering in a mobile browser is a huge plus.
* Having standard markdown links allows to use `[some context](actual-link.md)` syntax, which can make the text more natural to read.
* Not having a specific linking syntax makes the notes more future-proof.

Currently the links work intuitively if all zettels are in the same directory. The user stories I would like to see supported:
* Given a file `foo.md` and `dir/inside.md`, as a user I would like to link to `inside.md` file by using `[some text](dir/inside.md)`
* Given a file `dir/foo.md` and a `dir2/inside.md`, as a user I would like to link to `inside.md` file by using `[some text](../dir2/inside.md)`

I personally think that allowing links `[some text](inside.md)` when the `inside.md` is not in the same directory is confusing, but I think it may be worth to decide this outside the scope of handling the two cases above.

**Comment by srid** [comment]
By half-working you mean #543?

I don't understand what the connection of regular markdown links to the dirtree/uptree plugin is.

As for your point no. 2, see #373

But yes, overall having full support for regular markdown links is a good thing.

**Comment by aignas** [comment]
Thanks for the references. In order to illustrate the differences between the behaviours, I have created https://github.com/aignas/srid-neuron-614.

The dirtree works as expected, however links to zettels is not what I would expect. I would expect `[my link](dir/inside.md)` to work, however, `[my link](inside.md)` is what works instead and this is not how I would expect markdown links to work.

The uptree plugin as shown in the screenshot is only built when using standard `[[my-zettel]]#` links.

**Comment by srid** [comment]
Supporting links like `[my link](dir/inside.md)` or even `[my link](../dir/inside.md)` (if you are trying to link from a subfolder to to something in its sibling) were never thought of, but yea - it'd be good to have that.

The uptree plugin behaves as expected, as it looks only at the folgezettel subset of the graph, and as such it looks only at folgezettel links, which is what links with a `#` do. See https://neuron.zettel.page/folgezettel

**Comment by aignas** [comment]
I see. It seems that having propper uplinks requires the `neuron`-specific syntax but I guess in this case it may be better not to overload the markdown syntax with support for `[foo](bar.md)#` and `#[foo](bar.md)` because markdown would look really weird with that.

Shall we set the scope of the feature request only on the link supporting then?

**Comment by srid** [comment]
See https://github.com/srid/neuron/issues/373 for folgezettels with custom link text.

Markdown links will remain non-folgezettel.

**Comment by aignas** [comment]
Makes sense, thank you for clarification.

**Comment by srid** [comment]
Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).

Regular Mardown links should work on Emanote, if not please open an issue in that repo.
