### ISSUE TITLE
Feature Request: Support for ruby text (furigana) with markdown syntax

### ISSUE THREAD

**Issue by Morgawr** [srid/neuron#619]
So, I admit I am not very familiar with markdown or what kind of markdown engine neuron uses/supports, however I maintain a neuron site that deals with a lot of Japanese text and I'd love to get a way to add furigana readings (see something like [this](https://github.com/iltrof/furigana-markdown-it) as an example of what I mean if you aren't familiar with it).

Is there a simple way to do this?

It might be possible to maybe add some special CSS rules or something (I'm not good with CSS) to the head.html file, but I'd like to avoid that if possible, does anyone know? Any ideas?

**Comment by srid** [comment]
With https://github.com/srid/neuron/issues/363 - it can be done using a pandoc filter, eg: https://github.com/konn/pandoc-japanese-filters/blob/master/Spec.md

You can use raw html in your Markdown; failing that, perhaps some JS that replaces the DOM like https://github.com/samwalls/neuron-citation does ....

**Comment by srid** [comment]
> what kind of markdown engine

It uses commonmark-hs to parse, and produces a Pandoc AST.

https://github.com/srid/neuron/blob/83ffa9f3f8700d60882a1f83e10dab53daca4dea/src/Neuron/Markdown.hs#L113

**Comment by Morgawr** [comment]
Oh this is interesting, it might be worth looking more into it.

At the moment I have found a solution just using direct HTML with `<ruby>Word<rt>furigana</rt></ruby>` tags which appear like this: <ruby>Word<rt>furigana</rt></ruby>.

I guess this fits my needs for the time being, so we can probably close this feature request? Unless there is actual interest to implement something more ad-hoc/user-friendly down the line.

**Comment by srid** [comment]
Yea, let's close this because a more general feature can be done as #363
