### ISSUE TITLE
Zettel ID influences clustering behaviour

### ISSUE THREAD

**Issue by LightAndLight** [srid/neuron#632]
B.md:
```
# Topic One

Content
```

C.md:
```
# Topic Two

See also: [[B]]
```

Impulse:

![2021-07-01-083712_1419x586_scrot](https://user-images.githubusercontent.com/2536121/124040220-d7069c80-da47-11eb-9c6a-f2f22c7e0ba6.png)

---

After renaming C.md to A.md:

B.md:
```
# Topic One

Content
```

A.md:
```
# Topic Two

See also: [[B]]
```

Impulse:

![2021-07-01-083738_1421x586_scrot](https://user-images.githubusercontent.com/2536121/124040286-f9001f00-da47-11eb-85eb-d6b3fa8f5f2d.png)

---

It's got something to do with lexicographic ordering of IDs. If I rename C.md to D.md, then the impulse matches the first image.

**Comment by srid** [comment]
I think it was the because of a bug in the way data for Impulse is computed. Could you try latest `master` to confirm if that fixes the bug? @LightAndLight

**Comment by srid** [comment]
Actually, try out `1.9.33.0`, and you should expect to see this:

![image](https://user-images.githubusercontent.com/3998/124044028-6aa18400-d9da-11eb-8800-18ad1069c818.png)

**Comment by LightAndLight** [comment]
Thanks!
