### ISSUE TITLE
Small mistake in tutorial: gen should be rib

### ISSUE THREAD

**Issue by ottoborden** [srid/neuron#635]
Hey, I'm brand new to Zettelkasten and I can't thank you enough for this great software! I'm running through the tutorial now and just wanted to let you know that the tutorial instructs to use `neuron gen -wS` but it should be `neuron rib -wS`.

![2021-07-13_23-29](https://user-images.githubusercontent.com/3083164/125556717-2421200c-0758-4bca-bd13-2c4cb758be0a.png)

Thanks again!

**Comment by srid** [comment]
@ottoborden The tutorial now mentions the (deprecated) rib command, but note that neuron.zettel.page is about v2 (`master` branch) of neuron. I suppose you have v1 installed. 

v1 docs are [available here](https://github.com/srid/neuron/tree/v1/guide) but they are not hosted anywhere.
