### ISSUE TITLE
Unicode file-named notes are being ignored

### ISSUE THREAD

**Issue by FanZhen2002** [srid/neuron#636]
run `neuron gen --pretty-urls` locally on my Mac is OK.
But check github's action info, show some notes missing, only ascii named notes remain and generate htmls.

**Comment by srid** [comment]
Okay, I have a fix for this, and it will go in the Docker image. I'll close this issue once that happens.

**Comment by srid** [comment]
@FanZhen2002 Fix pushed. Let me know if that resolves it.

**Comment by srid** [comment]
Fix confirmed, http://zk.fanzhen.org/impulse
