### ISSUE TITLE
Add a server mode that renders errors

### ISSUE THREAD

**Issue by Nadrieril** [srid/neuron#75]
Right now if there is an error while running neuron, the error is displayed on the terminal and the update doesn't show on the served pages. I would like an option that makes neuron display an error message _on the served page_ instead. That way I can leave neuron running on a server and if a zettel fails to parse I will see it when I try to access the corresponding webpage.

**Comment by srid** [comment]
I've thought about this feature a few times, actually (albeit, to be able to handle more than parse errors). It'd certainly be nice to have.

**Comment by srid** [comment]
Looks like https://github.com/srid/neuron/issues/201 will obviate this.

**Comment by Nadrieril** [comment]
Yep, this has now been implemented, thanks!
