### ISSUE TITLE
Feature Request: Add host option to `rib serve`

### ISSUE THREAD

**Issue by michelk** [srid/neuron#76]
It would be nice to be able to access the http-server from a different computer than the one where the server was started.  

What I want to accomplish is: 

    neuron ZDIR rib serve --port 8888 --host 0.0.0.0

Thanks.

**Comment by srid** [comment]
This would be a good first issue for rib: https://github.com/srid/rib/issues/150 

> It would be nice to be able to access the http-server from a different computer than the one where the server was started.

Note that you can also sync the output directory via Dropbox or something, and then open the "index.html" directly on any computer. See #41

**Comment by michelk** [comment]
Thank you.
