### ISSUE TITLE
Make rib commands fail when the zettelkasten doesn't exist

### ISSUE THREAD

**Issue by felko** [srid/neuron#77]
When trying to generate the site from a nonexistent zettelkasten with `neuron nonexistent-dir rib generate`, shake will create `nonexistent-dir/.shake` and two files `nonexistent-dir.output/index.html` and `nonexistent-dir.output/z-index.html` will be generated.

It would be preferable to fail in the case where the zettelkasten doesn't exist, e.g. for editor support, to notify that the command has failed instead of generating the webapp from nowhere.

I notice however that `neuron nonexistent-dir new "title"` fails with `getDirectoryContents:openDirStream: does not exist (No such file or directory)`. Maybe the existence of the zettelkasten should be checked in all cases, and provide an pretty error message instead of a Haskell error.

**Comment by srid** [comment]
> Maybe the existence of the zettelkasten should be checked in all cases, and provide an pretty error message instead of a Haskell error.

Agreed. PR welcome.
