### ISSUE TITLE
Neuron refreshes in a loop when in watch mode

### ISSUE THREAD

**Issue by Nadrieril** [srid/neuron#81]
Using `bin/run -d ./guide rib -wS`, if I change a file neuron will correctly rebuild the files, but it will then continue to do it in a loop even if nothing else changes.

**Comment by Nadrieril** [comment]
Ah, this only happens with relative paths. I assume this is related to some of your recent commits to `rib` about absolute paths

**Comment by srid** [comment]
Culprit is probably somewhere around here: https://github.com/srid/rib/blob/master/src/Rib/App.hs#L111-L115
