### ISSUE TITLE
Vim integration

### ISSUE THREAD

**Issue by srid** [srid/neuron#9]
Some ideas here: https://github.com/aleator/Zettel-hs

**Comment by srid** [comment]
Use Haskell? https://github.com/neovimhaskell/nvim-hs

**Comment by srid** [comment]
Out of scope (and zettel-mode is sufficient)

**Comment by ihsanturk** [comment]
I've created [neuron.vim](https://github.com/ihsanturk/neuron.vim/).

**Comment by srid** [comment]
Awesome! I'll check it out -- and add to documentation.
