### ISSUE TITLE
pass custom port to rib?

### ISSUE THREAD

**Issue by ceedubs** [srid/neuron#94]
Is it still possible to pass a custom port to rib? Before some recent CLI changes I was doing something like `neuron . rib serve --port=8081`. I'm having trouble figuring out how to do the same now. If it's possible, documenting it on https://neuron.srid.ca/2011405.html and/or the CLI `--help` output would be great (and I'd be happy to help, if I can).

**Comment by srid** [comment]
@ceedubs Try `neuron -d . rib -ws :8081`.

It is already documented in the CLI (see below), and it should be added to the documentation.

```
$ neuron rib --help
Usage: neuron rib [-o|--output-dir OUTPUTDIR] [-w|--watch]
                  [(-s|--serve [HOST]:PORT) | -S]
  Generate static site via rib

Available options:
  -o,--output-dir OUTPUTDIR
                           The directory where HTML will be generated (default:
                           NOTESDIR/.neuron/output)
  -w,--watch               Watch for changes and regenerate
  -s,--serve [HOST]:PORT   Run a HTTP server on the generated directory
  -S                       Like `-s 127.0.0.1:8080`
  -h,--help                Show this help text

```

**Comment by ceedubs** [comment]
@srid ahh great thank you! I was doing `neuron --help` and didn't think to try `neuron rib --help`. I'll try to put together a documentation PR for the site.
