### ISSUE TITLE
Full support for offline browsing

### ISSUE THREAD

**Issue by felko** [srid/neuron#96]
Currently the generated site imports CSS and JS scripts from CDNs which requires an internet connection.

Some features are not fully supported offline, such as the web search and MathJax.

It would be preferable to add js-search, mathjax and semantic-ui as dependencies in the nix derivation and make the site rely on local files only.

**Comment by srid** [comment]
cf. https://github.com/obsidiansystems/obelisk/tree/master/lib/asset

**Comment by srid** [comment]
There is also the neuron logo in the footer which links directly to GitHub. We should instead copy over the logo during rib stage, to ./static/ and then link to it directly.

**Comment by srid** [comment]
Fonts too. https://github.com/rust-lang/mdBook/pull/1188/files

**Comment by srid** [comment]
Offline browsing is the default in Emanote (all assets are copied to the generated site)

Closing per https://neuron.zettel.page/next ... to further discuss this idea, [post in Emanote repo](https://github.com/srid/emanote/issues/new/choose).
